### ISSUE TITLE
Add `brew services logfile $service`

### ISSUE THREAD

**Issue by dbkaplun** [Homebrew/homebrew-services#101]

**Comment by dbkaplun** [comment]
OK? Was there any reason for closing?

**Comment by MikeMcQuaid** [comment]
You haven't written any explanation of what you want or why.

**Comment by dbkaplun** [comment]
@MikeMcQuaid I want a command that will show me the logfile for a given package so I can tail it or grep through it. Does that make sense? Is that doable?

**Comment by MikeMcQuaid** [comment]
@dbkaplun I don't know whether it's doable or not, it's probably pretty package dependent. We might accept a pull request for this but won't be implementing it ourselves. For future reference please write significantly more verbose issues, thanks.

**Comment by dbkaplun** [comment]
Thanks @MikeMcQuaid !!
