### ISSUE TITLE
How is the zsh_completion supposed to be used?

### ISSUE THREAD

**Issue by tareqak** [Homebrew/homebrew-services#105]
Does it have to be copied manually to `$(brew --prefix)/completions/zsh` e.g. `/usr/local/Homebrew/completions/zsh`? I was thinking it would be automatic once I executed `brew tap homebrew-services`.

**Comment by MikeMcQuaid** [comment]
It needs to be manually symlinked for now but there's an open PR to work on this https://github.com/Homebrew/brew/pull/1708

**Comment by tareqak** [comment]
Thanks @MikeMcQuaid!
