### ISSUE TITLE
Brew services require reboot to run?

### ISSUE THREAD

**Issue by jcrben** [Homebrew/homebrew-services#106]
I noticed today that two services (`kwm` and `syncthing`) required that I reboot the computer to properly run. This is despite the fact that `brew services list` showed them as running. This was also after I also tried to restart them with `brew services restart`. Is this working as designed, since services are run during boot / login? At least `brew services list` should be accurate...

**Comment by MikeMcQuaid** [comment]
You've not provided enough information here for me to be able to help. I don't know what "properly run" means. If a service is started but doesn't work that's almost certainly up to the upstream software creator rather than homebrew services.

**Comment by jcrben** [comment]
OK. Basically `brew services list` showed the services as running even though they were not. I believe that they did not show up as running processes when checking with `ps -ef` either.

They did work perfectly after a reboot..
