### ISSUE TITLE
Can no longer use sudo to manage tasks

### ISSUE THREAD

**Issue by pgrippi** [Homebrew/homebrew-services#108]
A recent update to homebrew seems to prevent the use of any `sudo brew` command. I get this when trying to restart httpd24:

```
$ sudo brew serivces stop httpd24
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

**Comment by ilovezfs** [comment]
What does
```
brew serivces stop httpd24
```
do?

**Comment by pgrippi** [comment]
I have apache set to listen on port 80 which is why I need root to run it. I also have dnsmasq running as root and I have the same problem with it

**Comment by MikeMcQuaid** [comment]
> sudo brew serivces stop httpd24

You typed `services` wrong.
