### ISSUE TITLE
services start does not detect Invalid property list error

### ISSUE THREAD

**Issue by johnhawkinson** [Homebrew/homebrew-services#111]
First cut on a formula that installs a plist, and it seems that `brew services start` runs `launchctl load -w` (isn't that deprecated?) and declares success based on `launchctl's` exit status, but ignores errors sent to stderr:

```
pb3:~ jhawk$ brew services start ntp
Unsetting PERL5LIB to protect you from yourself
/Users/jhawk/Library/LaunchAgents/homebrew.mxcl.ntp.plist: Invalid property list
==> Successfully started `ntp` (label: homebrew.mxcl.ntp)
pb3:~ jhawk$ ls -ld /Users/jhawk/Library/LaunchAgents/homebrew.mxcl.ntp.plist
-rw-------  1 jhawk  staff  664 Apr  1 23:38 /Users/jhawk/Library/LaunchAgents/homebrew.mxcl.ntp.plist
pb3:~ jhawk$ cat /Users/jhawk/Library/LaunchAgents/homebrew.mxcl.ntp.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>homebrew.mxcl.ntp</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/opt/ntp/sbin/ntpd</string>
	<string>-c</string>
	<string>/private/etc/ntp-restrict.conf</string>
	<string>-g</string>
	<string>-p</string>
	<string>/var/run/ntpd.pid</string>
	<string>-f</string>
	<string>/var/db/ntp.drift</string>
	<string>-l</string>
	<string>/var/log/ntp.log 
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
pb3:~ jhawk$ launchctl list|grep mxcl
pb3:~ jhawk$ launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.ntp.plist 
/Users/jhawk/Library/LaunchAgents/homebrew.mxcl.ntp.plist: Invalid property list
pb3:~ jhawk$ echo $?
0
```

```
pb3:cmd jhawk$ git log --format=short brew-services.rb
commit a5115e47b05e8d2a632ba7775599e698b240e5a2
Author: Mike McQuaid <mike@mikemcquaid.com>

    Merge pull request #107 from MikeMcQuaid/fix-run-restart
pb3:cmd jhawk$ 
pb3:cmd jhawk$ brew config
Unsetting PERL5LIB to protect you from yourself
HOMEBREW_VERSION: 1.1.11-226-g974b5e2fa2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 974b5e2fa26a162d29f97e996eb687b12a46a952
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7ee00ee0a9696f4ad88686fd5a54534d0cfc241b
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11

```

**Comment by MikeMcQuaid** [comment]
> declares success based on launchctl's exit status

How else would you suggest detecting success or failure?

**Comment by johnhawkinson** [comment]
> How else would you suggest detecting success or failure?

Any way you want / Any way that works? The end result needs to be not claiming success when the invoked command fails, otherwise there's a bug. You can't rely on the exit status of a command that doesn't set it.

The obvious choice is to check stderr for success or error indications.

Another choice is to be agnostic and claim neither success nor failure (but that would only seem right if there's no way to check, but stderr is a way).

I'm by no means a `launchd` expert, but the manpage suggests that `launchctl load` is deprecated, which makes me presume there's a better way to do the same function; perhaps a way that reports exit statuses, but I don't know.

**Comment by MikeMcQuaid** [comment]
`brew services list` looks at more information provided by `launchd`. `brew services` in general is just a thin wrapper around `launchd` and Homebrew's `plist` blocks.

> Any way you want / Any way that works?

I don't know how to improve this so I'm unfortunately closing this as not actionable from my perspective. If you disagree, please submit PRs to improve this and we can discuss those changes.

**Comment by johnhawkinson** [comment]
> I don't know how to improve this so I'm unfortunately closing this as not actionable from my perspective.

What's wrong with looking at stderr?

**Comment by MikeMcQuaid** [comment]
I'm still not sure what you're proposing; what `stderr` should constitute success/failure?

**Comment by johnhawkinson** [comment]
> I'm still not sure what you're proposing; what stderr should constitute success/failure?

Under the normal success condition, there is no `stderr` output. So probably the most general thing to do is check for any `stderr` output at all, and then throw an error if it is present.

In the alternative, you could check for `stderr` output that corresponds to known common errors, e.g.  matching "Invalid property list" and some other black(white?)list. [I don't know what other errors happen often.]

Incidentally, this exit status limitation is documented in launchctl(1):
```
LEGACY SUBCOMMANDS
...
     load | unload [-wF] [-S sessiontype] [-D domain] paths ...
...

              NOTE: Due to bugs in the previous implementation and long-standing client
              expectations around those bugs, the load and unload subcommands will only
              return a non-zero exit code due to improper usage.  Otherwise, zero is always
              returned.
```

**Comment by johnhawkinson** [comment]
Also, for what it's worth:

> I'm by no means a `launchd` expert, but the manpage suggests that `launchctl load` is deprecated, which makes me presume there's a better way to do the same function; perhaps a way that reports exit statuses, but I don't know.

This seems to have been discussed in https://github.com/Homebrew/legacy-homebrew/issues/33259 although I don't understand the resolution and why it was closed. But I found https://babodee.wordpress.com/2016/04/09/launchctl-2-0-syntax/ instructive. It appears that

```
bash-3.2# launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
```

is equivalent to

```
bash-3.2# launchctl enable system/homebrew.mxcl.ntp
bash-3.2# launchctl bootstrap system /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
```

except that it actually returns an exit status. So deliberately frotzing my plist, I get:

```
bash-3.2# launchctl print system |grep mxcl
		   90549      - 	homebrew.mxcl.ntp
bash-3.2# launchctl unload -w /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
bash-3.2# launchctl print system |grep mxcl
bash-3.2# launchctl enable system/homebrew.mxcl.ntp
bash-3.2# launchctl bootstrap system /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
/Library/LaunchDaemons/homebrew.mxcl.ntp.plist: Invalid property list
bash-3.2# echo $?
133
```

So yet another approach is to move to enable/bootstrap and then check the exit status.

**Comment by MikeMcQuaid** [comment]
> This seems to have been discussed in Homebrew/legacy-homebrew#33259 although I don't understand the resolution and why it was closed.

Basically: it wasn't a blocking issue and may provide additional functionality for us but works similarly as-is.

> So yet another approach is to move to enable/bootstrap and then check the exit status.

That seems like a good idea. My concern is that it may limit the backwards compatibility of `brew services` but 10.10 and above seems fine at this point.

**Comment by johnhawkinson** [comment]
Should I be filing another Issue here, given that this is closed but also a "good idea"?

---

**Tangent**: While looking into this, I was very confused by the fact that `brew services list` reported a service as "started" even when it was not running:

```
pb3:cmd jhawk$ brew services list
Name                       Status  User Plist
dbus                       stopped      
ntp                        started root /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
selenium-server-standalone stopped      
```

after some source-diving, I find that actually it is manipulating the result:
```
pb3:cmd jhawk$ HOMEBREW_DEVELOPER=1 brew services list
Name                       Status  User Plist
dbus                       stopped      
ntp                        unknown root /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
selenium-server-standalone stopped      
```

Because of https://github.com/Homebrew/homebrew-services/commit/b4fb83bbdf9c0c282ae53980e992c87ed7f0ae9d:

```patch
+        when :unknown
+          if ENV["HOMEBREW_DEVELOPER"]
+            "#{Tty.yellow}unknown#{Tty.reset}"
+          else
+            # For backwards-compatability showing unknown state as started in yellow colour
             "#{Tty.yellow}started#{Tty.reset}"
```

which I find very confusing. Services started as root are omitted from `launchctl list` when run as non-root, so `brew services list` doesn't find them (and regards them as `:unknown`).  Explicitly hiding this from the user hinders diagnostics, and I wish it was not done. It caused me to waste an hour of my time trying to figure out what Homebrew was doing before I got around to instrumenting the code. The above commit justifies it as as "likely indicates a badly configured Homebrew `plist`" but I'm not sure why that would be true (and does not seem to be for me).

Does this merit opening a new Issue or PR (to revert the above)?
If not, I guess I documentation PR would be appropriate to explain this behavior, yes?

**Comment by MikeMcQuaid** [comment]
> Should I be filing another Issue here, given that this is closed but also a "good idea"?

We tend to close issues that no maintainers are planning on working on. We'd consider accepting a PR which doesn't require an open issue in our process (I realise other projects differ).

> Explicitly hiding this from the user hinders diagnostics, and I wish it was not done.

We have other tools which parse `brew services` output and would be broken by this change.

The best fixes for these cases are to fix the upstream formula plist so detection is handled correctly.

**Comment by johnhawkinson** [comment]
> We tend to close issues that no maintainers are planning on working on. We'd consider accepting a PR which doesn't require an open issue in our process (I realise other projects differ).

Oh, I didn't realize no maintainers were planning on working the issue. I had proposed two straightforward solutions to the problem and you closed the PR saying "I don't know how to improve this," which I found very confusing. I presumed you closed it because you thought the proposed solutions were not viable (I don't know why), not because you thought it was not worth doing. After closure I found a third solution so mentioned it, which you then suggested was [more?] viable.

It would help if the closure case distinguished between "We would accept a PR for any of these proposed solutions" and "We would not accept a PR for anything like this" and "Please work harder to find a way to solve this that is not one of the proposed solutions." It's not so much the question of whether there's an open Issue to accept a PR, but rather the closure of the Issue tends to imply it's not worth working on a PR, and I don't want to waste my time and yours doing something that won't be accepted.

---

[`brew services list` can't find the status of certain launchd plists]

> The best fixes for these cases are to fix the upstream formula plist so detection is handled correctly.

I do not think there is an error in the formula to correct.
`brew services list` depends on `launchctl list` which does not display plists that have been loaded as root. This is not an issue with the formula.

Have I misunderstood you?

Although `launchctl print system` is a non-deprecated command that will print the loaded plists from the system context regardless of whether run as root or not (note the output format is not identical). Perhaps `brew services list` should use that as well as checking the user context.

While I'm here (again, should this be yet another Issue?), `brew services list` seems to call `launchctl list` once for each installed formula with a plist.  That's not exactly fast (I notice the delay with only 3 such services). Especially if it were to call both `launchctl print system` and `launchctl list` then it would be even slower if it continued to call them _n_ times instead of once.

(I'm not sure what the proper non-deprecated replacement for `launchctl list` in the user context is. Again, not a launchd expert. It seems to be `launchctl print user/$(id -u)` although I'm not certain.)

**Comment by MikeMcQuaid** [comment]
> It's not so much the question of whether there's an open Issue to accept a PR, but rather the closure of the Issue tends to imply it's not worth working on a PR

That may be the case in other projects but it's not on this one.

> Have I misunderstood you?

I think I misunderstood you. There's the `root` case and there's the case where formulae detach and fork which means `launchd` can't keep track of their success/failure. That case should be fixed in formulae.

> Perhaps brew services list should use that as well as checking the user context.

This sounds like a good idea we'd review a PR for.

> Especially if it were to call both launchctl print system and launchctl list then it would be even slower if it continued to call them n times instead of once.

Similarly this sounds like a good idea we'd review a PR for.
