### ISSUE TITLE
services list thinks Cellar ownership defines process runner

### ISSUE THREAD

**Issue by johnhawkinson** [Homebrew/homebrew-services#113]
I notice that if I start a service as myself, `brew services list` claims that it is running as root (!):

```
pb3:~ jhawk$ brew services start dbus
==> Successfully started `dbus` (label: homebrew.mxcl.dbus)
pb3:~ jhawk$ brew services list
Name                       Status  User Plist
dbus                       started root /Users/jhawk/Library/LaunchAgents/homebrew.mxcl.dbus.plist
ntp                        started root /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
selenium-server-standalone stopped      
```

It appears to be because of this [code](https://github.com/Homebrew/homebrew-services/blob/e02fbadb456a52b66fd43f0a23d413a803f1250b/cmd/brew-services.rb#L51-L54):

```.rb

    # Current user, i.e., owner of `HOMEBREW_CELLAR`.
    def user
      @user ||= `/usr/bin/stat -f '%Su' #{HOMEBREW_CELLAR} 2>/dev/null`.chomp || `/usr/bin/whoami`.chomp
    end
```
Can anyone explain this behavior?

Perhaps there is something wrong with my Homebrew installation for having `/usr/local/Cellar` owned by root. It seems legit and proper to me (it's group-writable), but maybe I'm missing something.

This is slightly more than cosmetic, it affects which location `brew services` looks for plist files in, and seems to cause some things to fail.

Even if this behavior is fully correct (and it sure could use some better comments!), there's probably a documentation change worth making to explain the relevance of `/usr/local/Cellar` ownership.

---

Here's a more complete transcript:

```
pb3:~ jhawk$ brew services list
Name                       Status  User Plist
dbus                       stopped      
ntp                        started root /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
selenium-server-standalone stopped      
pb3:~ jhawk$ ls -ld /usr/local/Cellar
drwxrwxr-x@ 244 root  admin  8296 Apr  2 00:19 /usr/local/Cellar
pb3:~ jhawk$ brew services start dbus
==> Successfully started `dbus` (label: homebrew.mxcl.dbus)
pb3:~ jhawk$ brew services list
Name                       Status  User Plist
dbus                       started root /Users/jhawk/Library/LaunchAgents/homebrew.mxcl.dbus.plist
ntp                        started root /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
selenium-server-standalone stopped      
pb3:~ jhawk$ brew services stop dbus
Stopping `dbus`... (might take a while)
==> Successfully stopped `dbus` (label: homebrew.mxcl.dbus)
pb3:~ jhawk$ sudo chown $USER /usr/local/Cellar
pb3:~ jhawk$ brew services start dbus
==> Successfully started `dbus` (label: homebrew.mxcl.dbus)
pb3:~ jhawk$ brew services list
Name                       Status  User  Plist
dbus                       started jhawk /Users/jhawk/Library/LaunchAgents/homebrew.mxcl.dbus.plist
ntp                        started root  /Library/LaunchDaemons/homebrew.mxcl.ntp.plist
selenium-server-standalone stopped       
pb3:~ jhawk$ brew services stop dbus
Stopping `dbus`... (might take a while)
==> Successfully stopped `dbus` (label: homebrew.mxcl.dbus)
pb3:~ jhawk$ 
```

**Comment by johnhawkinson** [comment]
I guess this code dates from @lwe's initial work in 2010 in https://github.com/Homebrew/legacy-homebrew/pull/3422. Lukas, do you have any thoughts?

**Comment by MikeMcQuaid** [comment]
> Perhaps there is something wrong with my Homebrew installation for having /usr/local/Cellar owned by root.

Yeh, that's not the default that the installer or updater will configure for you and although `brew doctor` may not complain it'd be something we'd tell you to change on a `brew update`. I'd suggest the best fix for this would be just to add a code comment to `brew services` to explain why this is the way it is. I don't think end user documentation needs changed until it's clear more people were confused by this.

**Comment by johnhawkinson** [comment]
Well, regardless of whether /usr/local/Cellar should be owned by a non-root user, something's wrong here. The ownership of that directory doesn't determine which user a LaunchAgent is run on. And what about multi-user systems? (They are not super rare) Claiming daemons are running as user1 when they're really running as user2 is no good.

I don't understand what this code is supposed to be doing.

>  it'd be something we'd tell you to change on a `brew update`

Do you mean that `brew update` should be changed to provide this warning? I'm confused by your use of the subjunctive.

**Comment by lwe** [comment]
@johnhawkinson, not sure this is still the best way to handle it IMO. It was mainly to ensure that it's always the "correct" user running the service, i.e. the one owning Homebrew. Otherwise some services (can't remember which, I guess e.g. MySQL) did have issues starting up, because /usr/local/var/mysql was owned by a different user for example. This was especially in combination with running it as `sudo brew services`.

TBH, not sure what the "right" way is, would have to dig into a few examples using `brew services` nowadays first.

**Comment by johnhawkinson** [comment]
> It was mainly to ensure that it's always the "correct" user running the service, i.e. the one owning Homebrew

Hrmm. So, of course I noticed this in `brew services list`, which it presumes that this is the user running the service. That's very different from choosing the user to start the service. Although, I'm a little confused about that, see `user` being used in that way? The code is a little hard for me to follow, though.

**Comment by lwe** [comment]
Yeah, just checked the code and `user` has IMO no effect, in fact also `UserName` keys are removed so... it should have zero effect.

**Comment by lwe** [comment]
@johnhawkinson, just to clarify that `user` was basically a crutch added back then so that `UserName` was properly set when running the service on startup (in `/Library/`).

Now since a63079af5c1a282c139fa66aa7b313c54e25cdde it was changed to always get rid of `UserName`, so it currently has no function at all and also the `user` method has no use from what I can understand.

This begs the question, does it even still work as expected...? Especially starting services at system startup?

**Comment by johnhawkinson** [comment]
> This begs the question, does it even still work as expected...? Especially starting services at system startup?

I am not sure. It does work properly for services run as root (e.g. my private fork of `ntp`).
The `dbus` formula doesn't seem to work quite right for me, but `dbus` is a complicated piece of software so I haven't looked into it. And the last time I ran `selenium-server` it broke my browser and required a reboot, so I don't want to touch that.

What's an example of a formula with a daemonized service that is good to test with?

**Comment by lwe** [comment]
I'd say good examples are databases like PostgreSQL or MySQL, which have a) rather strict permission settings and b) usually are owned by a specific non-root user. Will check when I'm back from work too and see if I can start postgres at system startup...

```bash
ls -la /usr/local/var/postgres # => drwx------  27 lukas  admin
```

**Comment by johnhawkinson** [comment]
Those are pretty heavyweight for a simple test case (and require configuration, etc.)

**Comment by lwe** [comment]
Mhhh, true, these are simply the ones that come into my mind... What I can offer you is that I'll check with postgres when I'm back from work.

**Comment by lwe** [comment]
Okay, from what I can see running services like MySQL or Postgres as root via `sudo brew services start $FORMULA` is broken in the current version of `brew services`. Tested it locally for me with postgresql.

### Reasons

1. Some services are not even allowed to run as root, e.g. postgres fails to start as root.
2. Due to change in a63079af5c1a282c139fa66aa7b313c54e25cdde there is no `UserName` anymore so it fails to start

How about when using `sudo brew services` requires a `--as=$USER` (or `--run-as` or `--user`) option, which then would allow to properly write `UserName`, without any magic invocation of ownership or similar...

**Comment by johnhawkinson** [comment]
So, the reasons you offer don't support the conclusion you derive from them.

That is, **some** services can't run as root, and there is **no `Username`**, therefore you say that "running as `sudo` is **broken**."

But for services that can run as root, it works just fine (which I suspect are the majority? My suspicion is based on no data.). Or at least, that's what my `ntp` example shows me (You'll have to go to https://github.com/johnhawkinson/homebrew-core/blob/c8d71d834ccfb3f75aa193fe8824f658204f05b5/Formula/ntp.rb since the plist was rejected for inclusion because of OS integration issues involving the native `ntpd`)

**Comment by lwe** [comment]
True, I guess it depends on the services one is running, and that's hard to tell. From my PoV - as a user that mostly runs databases - the sudo mode is not really usable at the moment.

Maybe show a disclaimer when running with sudo:

_Warning: Not all services are supported running at system start (or root) YMMV_

**Comment by johnhawkinson** [comment]
I'm still a little confused. If the issue is that `mysql` is supposed to run as a particular user, then the supplied plist should either have the username key or it should `su` or otherwise `setuid()` to the proper user. If the plist doesn't do these things, and the program is not functional when run as root, this is a bug in the plist and/or the Homebrew recipe, not in the `brew services` infrastructure. No?

The mysql plist (by inspection) runs `mysqld_safe`  without the `--user` flag, so it does not `setuid()` so the bug is in the plist. It is safe to run `mysqld_safe` as root and let it do the `setuid()` itself.

The removal of this was in https://github.com/Homebrew/legacy-homebrew/issues/18293 which cites https://github.com/Homebrew/legacy-homebrew/issues/18293. That issue...seems to present some things as fact which I am not sure are true.

I am less familiar with `postgres` so I'm not prepared to do that analysis there.

---

I guess I will have to go find my own test cases for these if I want something that is less complicated than database software.

**Comment by MikeMcQuaid** [comment]
We support running as two users: the user `brew services` is run as and `root` when it's run with `sudo`. Any leftover logic for other cases can be killed.

**Comment by lwe** [comment]
👍 makes sense, in addition I'd suggest to add a short notice / info somewhere about the supported cases.
