### ISSUE TITLE
Calling Formula.md5 is disabled

### ISSUE THREAD

**Issue by yaohuiwu** [Homebrew/homebrew-services#114]
Run the command 'brew services list' on mac, it shows:

Error: Calling Formula.md5 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:85:in `available_services'
Please report this to the homebrew/services tap!

**Comment by MikeMcQuaid** [comment]
You need to `brew update`.
