### ISSUE TITLE
Any way to uninstall a service?

### ISSUE THREAD

**Issue by vfonic** [Homebrew/homebrew-services#118]
From the docs (emphasis mine):

`$ brew help services`:

> brew services [-v|--verbose] [list | run | start | stop | restart | cleanup] [...]
>    Easily start and stop formulae via launchctl.
>    With -v or --verbose, print more detail.
> 
>    Integrates Homebrew formulae with macOS' launchctl manager. Services can be
>    added to either /Library/LaunchDaemons or ~/Library/LaunchAgents.
>    Basically, items in /Library/LaunchDaemons are started at boot, while those
>    in ~/Library/LaunchAgents are started at login.
> 
>    When started with sudo, it operates on /Library/LaunchDaemons; otherwise,
>    it operates on ~/Library/LaunchAgents.
> 
>    On start the plist file is generated and written to a Tempfile, and then
>    copied to the launch path (existing plists are overwritten).
> 
>    [sudo] brew services list
>    List all running services for the current user (or root)
> 
>    [sudo] brew services run formula|--all
>    Run the service formula without starting at login (or boot).
> 
>    **[sudo] brew services start formula|--all
>    Install and start the service formula at login (or boot).**
> 
>    **[sudo] brew services stop formula|--all
>    Stop the service formula after it was launched at login (or boot).**
> 
>    [sudo] brew services restart formula|--all
>    Stop (if necessary), install and start the service formula at login (or boot).
> 
>    [sudo] brew services cleanup
>    Remove all unused services.

How do I uninstall/unload/unregister the service that's registered with launchctl through brew services command?

Thanks!

**Comment by jbernardo95** [comment]
This make 2 of us, any way to unregister a service to start on login via `brew services` ?

**Comment by jbernardo95** [comment]
After messing around with commands I was able to do it, but don't really know if what just because I ran `brew services stop <service_name>` or because I ran `brew services stop <service_name>` followed by `brew services cleanup`, but one of them worked for me.

I think this should be more clear in the documentation.

**Comment by MikeMcQuaid** [comment]
Does `brew services stop` do what you want it to do? What are you trying to achieve here?

**Comment by vfonic** [comment]
@MikeMcQuaid actually I think it does, but the documentation made me think it doesn't.

I thought `brew services start` "installs" (in launchctl) and "starts" (now) the service, and `brew services stop` "stops" (now) the service.

I'd phrase it differently. Here's my suggestion:

>    **[sudo] brew services start formula|--all
>    Start the service formula immediately and register it to launch at login (or boot).**
> 
>    **[sudo] brew services stop formula|--all
>    Stop the service formula immediately and unregister it from launching at login (or boot).**

...or something similar.

**Comment by MikeMcQuaid** [comment]
@vfonic Can you also answer this question please: what are you trying to achieve here?

**Comment by vfonic** [comment]
@MikeMcQuaid sure.

I wanted to stop httpd24 from running and also from starting at login. I ran `brew services stop httpd24` and wasn't sure if it was unregistered/uninstalled/removed from launchctl. I read the `brew services` usage (by running `brew help services`, and was convinced that it **doesn't** unregister.

Now I'm sure it does: https://github.com/vfonic/homebrew-services/blob/85eb980fc556f8c790a4744af148257733a196b7/cmd/brew-services.rb#L329

**Comment by vfonic** [comment]
https://github.com/Homebrew/homebrew-services/pull/119

**Comment by MikeMcQuaid** [comment]
@vfonic Thanks!

**Comment by I159** [comment]
`brew services stop <formula>`
`brew uninstall <formula>`

`services` is not about uninstalling or installing, use `brew` itself to uninstall formula which used as a service.
