### ISSUE TITLE
/usr/local/var/log directory broken

### ISSUE THREAD

**Issue by hyperknot** [Homebrew/homebrew-services#121]
On a brand new, clean (`rm -rf /usr/local`) homebrew install the services log directory is broken.

1. It does not have execute bit, so it is not possible to enter it, unless with sudo:

```
drwxr--r--  2 root  admin
```

2. It is owned by `root:admin`

=> as a result, no service can ever log anything in there.

A fix on my system was to 

```
sudo chmod 777 /usr/local/var/log
```

I don't know what is the proper fix, in terms of what should be the right user and what chmod should be applied exactly. Also I don't know what should create it, either each `brew service start` command or `brew install` or `brew doctor` or something else, but the right creation / fixing of this directory should be handled by brew, I believe.

**Comment by hyperknot** [comment]
You can reproduce the broken directory, by 
1. stopping all services
2. deleting the folder via sudo
3. starting a service

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by MikeMcQuaid** [comment]
This isn't a fix that can be made in homebrew-services; it's required for individual formulae to ensure this directory is created if it's used in the `plist`.
