### ISSUE TITLE
Removing a service from the list

### ISSUE THREAD

**Issue by sodbileg** [Homebrew/homebrew-services#125]
Is there any way of removing a service from the list of services? For example,

I have 3 services which were started with `brew services start SERVICE_NAME` and I stopped one of them with `brew services stop SERVICE_NAME`. Now I have 3 services like below.

Service 1 - started
Service 2 - started
Service 3 - stopped

How can I remove Service 3 from the list even though it was stopped?

**Comment by MikeMcQuaid** [comment]
Did you try `brew services stop` again?

**Comment by sodbileg** [comment]
I just tried `brew services top SERVICE3` again and getting an error below.

`Error: Service `SERVICE3` is not started.` 

Then I run `brew services list` again and the service is still there.

**Comment by MikeMcQuaid** [comment]
Use `launchctl unload` manually on the `.plist`.

**Comment by sodbileg** [comment]
Just tried this and it's the same. Also isn't `brew services stop` doing `launchctl unload .plist` in the background? https://github.com/vfonic/homebrew-services/blob/85eb980fc556f8c790a4744af148257733a196b7/cmd/brew-services.rb#L329

What I'm trying to achieve is removing a stopped service from the list.

**Comment by sodbileg** [comment]
@pavelrad thanks for your reply. I didn't expect it to remove. The actual question was there actually a way to remove a service from the list.

**Comment by MikeMcQuaid** [comment]
@sodbileg Try `brew cleanup`

**Comment by MikeMcQuaid** [comment]
@sodbileg Apologies, `brew services cleanup`
