### ISSUE TITLE
postgre doesnt start correctly if pidfile is there, and brew services doesnt see it

### ISSUE THREAD

**Issue by jhertz** [Homebrew/homebrew-services#129]
if postgre didn't cleanup correctly (i.e. it crashed, or the system crashed), it will leave a lockfile in place, which will stop postgre from starting up next time. however, brew services doesnt detect that, and will incorrectly view postgre as running, despite it failing to run.

specifically, if the `/usr/local/var/postgres/postmaster.pid` file is still present, postgre will fail when trying to startup with the error `FATAL:  lock file "postmaster.pid" already exists`.

but, even though that happens, `brew services list` will still show postgres as running (when a `pgrep` will reveal it is clearly not). deleting the above-mentioned pidfile and issuing a `brew services restart postgresql` will fix the issue.

**Comment by MikeMcQuaid** [comment]
Nothing we can really do about this, I'm afraid, `postgresql` knowledge isn't baked into `brew services`. If there's something generic we can do better: we'll accept a pull request. Sorry!
