### ISSUE TITLE
Service name is truncated

### ISSUE THREAD

**Issue by xeron** [Homebrew/homebrew-services#13]
Example:

```
(dev) ilarionov@1078-ilarionov:~$ brew services list
chromedriv started    40792 /Users/ilarionov/Library/LaunchAgents/homebrew.mxcl.chromedriver.plist
postgresql started    40661 /Users/ilarionov/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
redis      started    40627 /Users/ilarionov/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

where `chromedriv` is actually `chromedriver`.

**Comment by gapple** [comment]
If you use the list command, I would appreciate your feedback on the changes in #12.
It includes an improvement to adjust the column widths so that the full service name would be displayed, amongst the other changes.

**Comment by gapple** [comment]
#13 is now merged to master, so the list command will adjust the column to fit longer command names.
