### ISSUE TITLE
`run` not working with `sudo`: "Path had bad ownership/permissions"

### ISSUE THREAD

**Issue by herrernst** [Homebrew/homebrew-services#130]
I'd like to start dnsmasq without enabling on reboot, but it fails:
````bash
$ sudo brew services run dnsmasq
/usr/local/Cellar/dnsmasq/2.77_3/homebrew.mxcl.dnsmasq.plist: Path had bad ownership/permissions
Error: Failure while executing: /bin/launchctl bootstrap system /usr/local/opt/dnsmasq/homebrew.mxcl.dnsmasq.plist
$ sudo brew services start dnsmasq
==> Successfully started `dnsmasq` (label: homebrew.mxcl.dnsmasq)
````
(running it with `start` works)

**Comment by MikeMcQuaid** [comment]
Does this apply for only `dnsmasq` or anything else? Can you try this with other formulae that use `sudo` and other formulae that don't. Thanks!

**Comment by herrernst** [comment]
Also happens with e.g. nginx:
```bash
sudo brew services run nginx
Password:
/usr/local/Cellar/nginx/1.12.1/homebrew.mxcl.nginx.plist: Path had bad ownership/permissions
Error: Failure while executing: /bin/launchctl bootstrap system /usr/local/opt/nginx/homebrew.mxcl.nginx.plist
```

**Comment by MikeMcQuaid** [comment]
What happens if you try `brew services run nginx`? What's your `brew doctor` output? Please answer each of my questions each time if you want me to help you, thanks.

**Comment by herrernst** [comment]
> What happens if you try `brew services run nginx`?

Works:
````
brew services run nginx
==> Successfully ran `nginx` (label: homebrew.mxcl.nginx)
````
> What's your `brew doctor` output?
````
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  node@6
````
(I've force-linked node@6 on purpose.)

----

I think it's a permission/ownership problem when the service is not installed/enabled.
````
brew services -v run nginx
/bin/launchctl bootstrap gui/502 /usr/local/opt/nginx/homebrew.mxcl.nginx.plist
````
Works because `/usr/local/opt/nginx/homebrew.mxcl.nginx.plist` is belongs to user.

----

````
sudo brew services -v run nginx
/bin/launchctl bootstrap system /usr/local/opt/nginx/homebrew.mxcl.nginx.plist
/usr/local/Cellar/nginx/1.12.1/homebrew.mxcl.nginx.plist: Path had bad ownership/permissions
Error: Failure while executing: /bin/launchctl bootstrap system /usr/local/opt/nginx/homebrew.mxcl.nginx.plist
````
Doesn't work because executing user is root (or system) and `/usr/local/opt/nginx/homebrew.mxcl.nginx.plist` still belongs to user.

----

````
sudo brew services -v start nginx
==> Generated plist for nginx:
....   

/bin/launchctl enable system/homebrew.mxcl.nginx
/bin/launchctl bootstrap system /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
==> Successfully started `nginx` (label: homebrew.mxcl.nginx)
````
Works because executing user is now root (or system) and `/Library/LaunchDaemons/homebrew.mxcl.nginx.plist` also belongs to user.

**Comment by MikeMcQuaid** [comment]
Gotcha, thanks. I'm not sure how to solve this; `sudo brew services run` will need to copy the file somewhere owned by root but `/Library/LaunchDaemons` won't work as it will mean it'll run again on startup. Thoughts?

**Comment by MikeMcQuaid** [comment]
@herrernst Thoughts?

**Comment by herrernst** [comment]
Unfortunately I cannot think of a proper solution to this neither.

**Comment by MikeMcQuaid** [comment]
Ok, thanks.

**Comment by MikeMcQuaid** [comment]
Opened a PR in https://github.com/Homebrew/homebrew-services/pull/132 to improve the error message here but I'm afraid I can't think of (or manage to implement) a better solution than this right now. If someone else want to give it a go: they are welcome.

**Comment by herrernst** [comment]
Thanks
