### ISSUE TITLE
Use Formula.sha256 instead problem 

### ISSUE THREAD

**Issue by qukankan** [Homebrew/homebrew-services#137]
![image](https://user-images.githubusercontent.com/3842940/31611499-99c3a062-b27c-11e7-8498-967af0572160.png)

I think i have the newest version but still get the "Use Formula.sha256 instead" error msg, pls take a look, thx.

**Comment by MikeMcQuaid** [comment]
The error message is wrong here; this will be with one of your formulae in your taps. Run `brew readall` to figure out which.

**Comment by qukankan** [comment]
![image](https://user-images.githubusercontent.com/3842940/31711794-99451728-b3f9-11e7-953d-4f0625bfaaa6.png)

thx for answer, but with command "readall" i can't get more information. How can i check the next step?

**Comment by MikeMcQuaid** [comment]
Try to run `brew info --installed`.

**Comment by qukankan** [comment]
```
gaok@macC02PH2FJG3QC [13:50:48] [~]  
-> % brew info --all  
40 kegs, 39,860 files, 1.3GB  
gaok@macC02PH2FJG3QC [13:50:52] [~]  
-> % brew info --installed  
40 kegs, 39,860 files, 1.3GB
```

Looks like no more useful hints. It's time to delete brew completely in my pc and reinstall it?

**Comment by ilovezfs** [comment]
@qukankan what's the output of `grep -r "sha1 " /usr/local`

**Comment by qukankan** [comment]
Thx @ilovezfs 
It's almost 3k lines @_@. Since it's failed when i call "brew services list", is there any other way to check out brew services. I think this can help to locate the problem taps.

[result.txt](https://github.com/Homebrew/homebrew-services/files/1395157/result.txt)

**Comment by ilovezfs** [comment]
I'm not seeing any use of sha1 in there. What happens if you
```
HOMEBREW_DEVELOPER=1 brew services -dv list
```

**Comment by qukankan** [comment]
yes, fund the reason:

`
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb  
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Users/gaok/Library/Caches/Homebrew/Formula/panamax.rb  
Error: Calling Formula.sha1 is disabled!  
Use Formula.sha256 instead.  
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:86:in "available_services" 
Please report this to the homebrew/services tap!  
`

By loading panamax.rb.
I installed the panamax before, use command from the official page like  
`$ brew install http://download.panamax.io/installer/brew/panamax.rb`

In this script used sha1.  
There is another script with sha256, but only in panamax Git repository:  
`https://raw.githubusercontent.com/pamri/panamax-coreos/896e6d3820c897f208ee58ba4ba2d5825b420504/panamax.rb`

omg. Thx support, it's fine now. Maybe add this Formulary name in error message (I mean as my first command try: brew services list)? It will not expose too many details but is useful to figure out the location.

-----------------------------
BTW.  
For those who has the same problem as me, after uninstall panamax from brew, and try reinstall it with brew but get another error with no permission to create soft link in /usr/local. That's another problem. I have full access rights in this order but still get error. It's strange, i think maybe because something went wrong in my environment after this series of questions.  
My workaround is install panamax using MacPorts:  
`curl http://download.panamax.io/installer/ubuntu.sh | bash`

**Comment by ilovezfs** [comment]
@qukankan you're welcome!
