### ISSUE TITLE
brew services start not actually starting services in High Sierra

### ISSUE THREAD

**Issue by 9130khz** [Homebrew/homebrew-services#144]
Running a clean install of brew on a clean install of High Sierra. Tried with both MySQL and MariaDB.

Running `sudo brew services start` will say that it is starting MySQL/MariaDB, and `[sudo] brew services list` will report its status as "started", but mysqld will not actually be running. I can successfully "stop" the service with sudo, but a start/restart will report success but again, not start the service. 

If i try to start the service without sudo, an error returns:
`Could not find domain for` 
`Error: Failure while executing: /bin/launchctl enable gui/502/homebrew.mxcl.mysql`

`brew doctor` returns a friendly "Your system is ready to brew."

Output of brew config:
`HOMEBREW_VERSION: 1.3.8`
`ORIGIN: https://github.com/Homebrew/brew`
`HEAD: 236b0172306a6f4b233d374fcc20adce5c3e3261`
`Last commit: 22 hours ago`
`Core tap ORIGIN: https://github.com/Homebrew/homebrew-core`
`Core tap HEAD: 52be327764830cbe28a524061013e3109d8e4da5`
`Core tap last commit: 27 minutes ago`
`HOMEBREW_PREFIX: /usr/local`
`HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config`
`CPU: quad-core 64-bit sandybridge`
`Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby`
`Clang: 9.0 build 900`
`Git: 2.13.6 => /Library/Developer/CommandLineTools/usr/bin/git`
`Curl: 7.54.0 => /usr/bin/curl`
`Perl: /usr/bin/perl`
`Python: /usr/bin/python`
`Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby`
`Java: N/A`
`macOS: 10.13.1-x86_64`
`Xcode: N/A`
`CLT: 9.1.0.0.1.1508540944`
`X11: N/A`

additional info: if i log into the computer with my OS user (it's a headless machine so all of the above was done while ssh'ed in after a fresh reboot, MySQL does actually start, `brew services list` reports it as started, but with a green highlight rather than yellow. Once i log out of the OS user, MySQL shuts itself down again.

**Comment by MikeMcQuaid** [comment]
> additional info: if i log into the computer with my OS user (it's a headless machine so all of the above was done while ssh'ed in after a fresh reboot, MySQL does actually start, brew services list reports it as started, but with a green highlight rather than yellow. Once i log out of the OS user, MySQL shuts itself down again.

This is the issue and it's with `launchctl` rather than `brew services` so we can't do anything about it, sorry.

**Comment by jedhassell** [comment]
@9130khz Were you ever able to find a solution for this? I'm having a similar issue.

**Comment by 9130khz** [comment]
@jedhassell Unfortunately not yet, i've just given into manually starting the database after a reboot

**Comment by vitaprimo** [comment]
I was having the same issue and the answer was actually in these posts, since it appears to be user related and brew cannot be run as root, then run it with _sudo_. 

```
web:etc webmaster$ brew services start proftpd
Could not find domain for 
Error: Failure while executing: /bin/launchctl enable gui/502/homebrew.mxcl.proftpd
web:etc webmaster$ sudo brew services start proftpd
Password:
==> Successfully started `proftpd` (label: homebrew.mxcl.proftpd)
web:etc webmaster$ 
```

I hope this helps somebody. :)
