### ISSUE TITLE
Stop all or start all option

### ISSUE THREAD

**Issue by r00takaspin** [Homebrew/homebrew-services#15]
Most of my services are databases or key-value storages, sometimes it is important to easy start all services (for example when I am starting work on project) or stop all services. It it possible out of box?

**Comment by gapple** [comment]
That isn't currently implemented, but should be possible to add.

**Comment by antstorm** [comment]
@r00takaspin it should now be possible, #28

**Comment by mikemcquaid** [comment]
Yup, fixed, thanks!
