### ISSUE TITLE
Controlling services in bulk or better/flexible --all behavior

### ISSUE THREAD

**Issue by ihorvorotnov** [Homebrew/homebrew-services#151]
The discussion started [here](https://github.com/Homebrew/homebrew-core/issues/24654).

Currently, you can only start|stop|reload services one by one or all of them at once with `--all` flag. However, in some cases, you need finer control. 

For example, now PHP migrated to homebrew/core and comes with Apache as a dependency. I'm using Nginx instead of Apache, and have a lot of other related services. Here's the list:

- dnsmasq
- mailhog
- nginx
- memcached
- redis
- mariadb
- blackfire-agent
- php
- httpd (the Apache service I don't need)

Basically, it's a local web development environment. Prior to this PHP migration, I could `brew services start --all` to bring it up, and `brew services stop --all` when done. Now I can't – it starts Apache as well.

Also, redis/memcached substitute each other in many cases, it makes sense to run only one of them at a time. Same applies to a different database engine, for example, MySQL and PostgreSQL, MongoDB etc. Also, Nginx, H2O. In most cases, you don't need them all to be running at the same time and running them one by one is annoying.

Of course, you can write a simple shell command to run required services in bulk, but wouldn't it be convenient to have a built-in command to handle some kind of "presets"?

**Comment by claui** [comment]
This may not be helpful at all but inspired by this discussion, I’ve hacked together a [really crude one-off prototype](https://github.com/claui/homebrew-services-bulk) for a lightweight implementation of presets.

It uses one custom formula per preset, runs with homebrew-services as-is, and requires nothing else. Because it’s just a formula, it also auto-detects the dependencies.

**Usage:**

    brew tap claui/services-bulk

    brew install myservers

    [sudo] brew services list

    [sudo] brew services [start | restart | stop] myservers

**To customize, just change this array:**

```ruby
  DEPENDENT_SERVICES = [
    "mariadb",
    "nginx",
    "php",
  ]
```

I’m surprised to see this actually works for me. Feel free to use it as a stop-gap until someone builds something more maintainable. (Or maybe in case the presets feature turns out too narrow to be added to homebrew-services proper.)

**Comment by ihorvorotnov** [comment]
Thank you @claui, I'll give it a shot soon. Looks promising!

**Comment by MikeMcQuaid** [comment]
This is a good idea, thanks for the detailed write up @ihorvorotnov!

**Comment by steinmb** [comment]
Do not make any sense to me too keep Apache as a dependency. As mention above. People might run Nginx, no use for a web server OR they use PHP built in web server. Do not forget that MacOS already ship with Apache installed that work flawlessly with homebrew php-versions.

**Comment by MikeMcQuaid** [comment]
@steinmb Your comment was completely unrelated to this repository. The other thread was locked for a reason.

**Comment by steinmb** [comment]
@MikeMcQuaid Thank you for getting back to me, though deleting comments is to me a unusual way of treating other developers. Ended up there because other issues got closed and linked in here. Should I create a separate issue regarding the dependency issue?

**Comment by MikeMcQuaid** [comment]
@steinmb No, we are not interested in more discussion of that issue or of Homebrew's moderation policy with non-maintainers or non-contributors (particularly when Homebrew's maintainers are currently being barraged with personal abuse).

**Comment by MikeMcQuaid** [comment]
`httpd` will not be installed any more if you use the bottle: https://github.com/Homebrew/homebrew-core/pull/24907
