### ISSUE TITLE
brew install root fails

### ISSUE THREAD

**Issue by hawkingsteven** [Homebrew/homebrew-services#157]
Hello I downloaded the root file but for some reason it failed again

[szakirov@localhost ~]$ brew install root
==> Downloading https://root.cern.ch/download/root_v6.12.06.source.tar.gz
Already downloaded: /home/szakirov/.cache/Homebrew/root-6.12.06.tar.gz
Error: No libpythonX.Y.{a,dylib} file found!

I ran brew doctor and I dont think anything is messing with the install 

[szakirov@localhost ~]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /bin/pkg-config
  /bin/brltty-config
  /bin/firewall-config
  /bin/freetype-config

**Comment by Jonathan-Abrahams** [comment]
@hawkingsteven What was your solution?

**Comment by hawkingsteven** [comment]
My solution was to uninstall homebrew and do a manual installation with the python you want to use for your software set to default.
