### ISSUE TITLE
Failed to connect to github.com port 443

### ISSUE THREAD

**Issue by DrOzturk** [Homebrew/homebrew-services#158]
Hi,
     Why am I receiving this?
(I have internet, and github is not down...)

$ brew services cleanup
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
fatal: unable to access 'https://github.com/Homebrew/homebrew-services/': Failed to connect to github.com port 443: Operation timed out
**Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-services** /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services --depth=1
Error: Failure while executing: /usr/local/bin/brew tap homebrew/services

**Comment by MikeMcQuaid** [comment]
You'll need to figure that out yourself I'm afraid.
