### ISSUE TITLE
Failed to connect to github.com port 443: Operation timed out

### ISSUE THREAD

**Issue by DrOzturk** [Homebrew/homebrew-services#159]
Hi,
    Why do you think, I have this error.
I have internet, and github service is not down.

> brew services list
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
fatal: unable to access 'https://github.com/Homebrew/homebrew-services/': Failed to connect to github.com port 443: Operation timed out
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-services /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services --depth=1
Error: Failure while executing: /usr/local/bin/brew tap homebrew/services

**Comment by MikeMcQuaid** [comment]
Don't create multiple identical issues: https://github.com/Homebrew/homebrew-services/issues/158
