### ISSUE TITLE
when i run  "brew  services   start  mongodb"  ，mongo client command does not take effect

### ISSUE THREAD

**Issue by Bodemon** [Homebrew/homebrew-services#165]
in ~ λ  :    brew services list
Name        Status       User    Plist
mongodb    started   root    /Library/LaunchDaemons/homebrew.mxcl.mongodb.plist

it's started  !    
run  "ps -ef | grep  mongo "
it's nothing?

but
use   "sudo mongod"   
then  "mongo"  
it's OK

Is my configuration problem yet?

**Comment by MikeMcQuaid** [comment]
It's a configuration problem on your end. "Started" means "we've started the daemon" not that it's currently running.

**Comment by Bodemon** [comment]
Oh，I see  
very  thanks
