### ISSUE TITLE
Re: Issue #144 - MySQL not starting with sudo.

### ISSUE THREAD

**Issue by jeffreydwalter** [Homebrew/homebrew-services#169]
@MikeMcQuaid @9130khz, just wanted to revive [issue 144](https://github.com/Homebrew/homebrew-services/issues/144) because I just hit upon it and found a way to work around it: 

I came across [this article](http://digitalhygiene.com/2014/05/09/start-mysql-as-a-daemon-on-os-x-mavericks-on-boot/) for running MySQL via brew and it worked for me. 

It seems like the problem is not just "`launchctl` rather than `brew services`", but more the plist file that `brew services` installs when calling `sudo`. 

Basically, a plist like this will work to run MySQL as root:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>homebrew.mxcl.mysql</string>
        <key>ProgramArguments</key>
       <array>
            <string>/usr/local/opt/mysql/bin/mysqld</string>
            <string>--bind-address=127.0.0.1</string>
            <string>--user=root</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>UserName</key>
        <string>root</string>
        <key>WorkingDirectory</key>
        <string>/usr/local/var/mysql</string>
    </dict>
</plist>
```

**Comment by MikeMcQuaid** [comment]
@jeffreydwalter I've unlocked that issue so you can comment ehre.

**Comment by jeffreydwalter** [comment]
Mike, I laid out the whole thing here. I'm not going to retype it. Please
feel free to fix brew services.

Cheers.

**Comment by MikeMcQuaid** [comment]
@jeffreydwalter This bug doesn't affect me so: no, you should feel free to fix it. If you can't be bothered to copy and paste: so be it. Please do not revive closed and locked issues in future unless you want to submit a pull request to fix them.
