### ISSUE TITLE
brew services start elasticsearch not working with latest macOS 10.14 (mojave).

### ISSUE THREAD

**Issue by sanketdhoble** [Homebrew/homebrew-services#173]
Gives error :
 `brew services restart elasticsearch
/Users/sanketd/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist: service already loaded
Error: Failure while executing; `/bin/launchctl bootstrap gui/789103748 /Users/sanketd/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist` exited with 133.`

**Comment by MikeMcQuaid** [comment]
Have you tried restarting your machine? What's your `brew services list` and `brew config` and `brew doctor` output?

**Comment by sanketdhoble** [comment]
Thanks alot, restart worked like a charm.
