### ISSUE TITLE
Can't start mariadb with "brew services start mariadb"

### ISSUE THREAD

**Issue by runofthemill** [Homebrew/homebrew-services#177]
When trying to start `mariadb` via launchd:

```
➜ brew services start mariadb
Error: Permission denied @ rb_sysopen - /Users/<username>/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
```

`sudo brew services start mariadb` works fine, as does `mysql.server start`. The plist doesn't exist in `~/Library/LaunchAgents`, and it's the only folder in `~/Library/` aside from `Spotlight` that is owned by `root` instead of the user, but I don't think it's a permissions issue, as there's a plist file for virtualbox that was added (today) via `brew cask`.

I've run `brew update`/`brew upgrade`/`brew doctor`, reinstalled homebrew via `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`, run `brew reinstall mariadb` all to no avail.

Output of `brew config`:

```
➜ brew config
HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3d4407ee47cec2771a6befb762ce677895de3d22
Core tap last commit: 29 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

Output of `brew info mariadb`:

```
➜ brew info mariadb
mariadb: stable 10.3.11 (bottled)
Drop-in replacement for MySQL
https://mariadb.org/
Conflicts with:
  mariadb-connector-c (because both install plugins)
  mysql (because mariadb, mysql, and percona install the same binaries.)
  mysql-cluster (because mariadb, mysql, and percona install the same binaries.)
  mysql-connector-c (because both install MySQL client libraries)
  mytop (because both install `mytop` binaries)
  percona-server (because mariadb, mysql, and percona install the same binaries.)
/usr/local/Cellar/mariadb/10.3.10 (658 files, 175.3MB)
  Poured from bottle on 2018-10-24 at 19:59:39
/usr/local/Cellar/mariadb/10.3.11 (659 files, 176.4MB) *
  Poured from bottle on 2018-12-27 at 23:38:41
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mariadb.rb
==> Dependencies
Build: cmake ✘
Required: openssl ✔
==> Caveats
A "/etc/my.cnf" from another install may interfere with a Homebrew-built
server starting up correctly.

MySQL is configured to only allow connections from localhost by default

To connect:
    mysql -uroot

To have launchd start mariadb now and restart at login:
  brew services start mariadb
Or, if you don't want/need a background service you can just run:
  mysql.server start
==> Analytics
install: 11,561 (30 days), 39,929 (90 days), 149,388 (365 days)
install_on_request: 10,980 (30 days), 37,642 (90 days), 135,761 (365 days)
build_error: 0 (30 days)
```

There is no `/etc/my.cnf` file, and none of the "Conflicts with" items are installed.

Let me know if there's any other info I can provide; this isn't a huge problem as I can run via `mysql.server start` but I thought it worth reporting. Cheers!

**Comment by MikeMcQuaid** [comment]
It is a permissions issue you’ll need to fix yourself.

**Comment by runofthemill** [comment]
@MikeMcQuaid any suggestions on what I should look into? As I mentioned, VirtualBox updated yesterday by `brew cask` was able to add a plist file to that folder without issue, so it would seem like a more nuanced issue than just folder permissions. Thanks!

**Comment by MikeMcQuaid** [comment]
It is a permissions issue. You need to chown that directory back to your user and possibly chmod it correctly.
