### ISSUE TITLE
Feature request: Please change "yellow" started to "unknown" for everyone

### ISSUE THREAD

**Issue by vfonic** [Homebrew/homebrew-services#182]
Hi,

I'm aware that I can set `HOMEBREW_DEVELOPER` to get "unknown" for...well, for unknown service status. I believe this should be the default for everyone even without the `HOMEBREW_DEVELOPER` flag.

I only found out about the `HOMEBREW_DEVELOPER` flag after digging through the issues here:
https://github.com/Homebrew/homebrew-services/issues/168
https://github.com/Homebrew/brew/issues/3227

When I first saw yellow, I really didn't pay much attention to the color. I spent much more time than I could have, if it didn't say "started" for a service that is exactly in the "unknown" state, from brew's point of view. Why write "started" then?

I understand this is a breaking change due to potentially some scripts depending on this string. Well, let's not make this bug a feature by keeping it like this. You could change it in the next major release. That would cause much less fatigue since it would represent the true what `brew services` knows about the particular service.

Even better error/help message would be:
> Pass -v argument to get more verbose output

And then, when you pass -v, you can see the reasons why brew can't know the status of each yellow-marked service.

Thanks! ❤️

**Comment by MikeMcQuaid** [comment]
> I understand this is a breaking change due to potentially some scripts depending on this string.

We need to figure out how to mitigate that.

> You could change it in the next major release.

This repository does not make releases.

I'm open to a PR that adjusts this and provides a solution to backwards compatibility concerns or continuing discussion here but closing for now.
