### ISSUE TITLE
 brew services shows inactive processes

### ISSUE THREAD

**Issue by Joellidin** [Homebrew/homebrew-services#184]
I recently installed `skhd` and `chunkwm` but had problems with `brew services start` where I got errors like this:
```
Error: Permission denied @ unlink_internal - /Users/joellidin/Library/LaunchAgents/homebrew.mxcl.skhd.plist
```
I got around that problem by copying the file and running `launchctl load ~/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist`. Now when running `brew services list` I got:
```
Name    Status  User      Plist
chunkwm started joellidin /Users/joellidin/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist
skhd    started joellidin /Users/joellidin/Library/LaunchAgents/homebrew.mxcl.skhd.plist
```
However when running `unload` I get the same output as above when running `brew services list`. I am quite new to the terminal so may be a stupid question but how would I do to either properly reinstall `skhd` and `chunkwm` without an error when starting with brew. Or how should I do to get the services list to display the processes as stopped?

**Edit:**
I now realised that `chunkwm` and `skhd` still was active when restarting the computer. So how would I do to permanently unload these?

**Comment by MikeMcQuaid** [comment]
This isn't a bug with `brew services`, sorry. Our Discourse (https://discourse.brew.sh) may be better place to ask such questions.
