### ISSUE TITLE
One formula one service 

### ISSUE THREAD

**Issue by torarnv** [Homebrew/homebrew-services#190]
Right now a single formula can’t have multiple services. And a foo.rb can’t have two formulas both depending on the same bottles or source archives, which would allow a single “formula” to have sub formulas for each service. Is there any plan to address this? See eg the icecream formula for an example. Thanks!

**Comment by MikeMcQuaid** [comment]
There's some work on this but it's stalled: https://github.com/Homebrew/brew/pull/5695

It would need changes in Homebrew/brew and Homebrew/homebrew-core.
