### ISSUE TITLE
Run multiple plists under one formula

### ISSUE THREAD

**Issue by minkyn** [Homebrew/homebrew-services#192]
I'd like to run multiple commands when `brew services start <formula>`. Putting all commands under one <Program> of the same plist works but not perfect.

Is it possible to add a new plist with different label name under that formula's directory, and then `brew services start` would `launchd` them all?

**Comment by MikeMcQuaid** [comment]
You can specify a plist path to `brew services`. The last discussion on adding multiple plists to Homebrew was in https://github.com/Homebrew/brew/issues/5691.

**Comment by minkyn** [comment]
Adding "-c" to specify a custom plist doesn't work, because you cannot `brew services start` the same formula twice with different plists.

I didn't catch the result from the previous discussion. Was the answer a _no_ for supportability?
