### ISSUE TITLE
Trying to Tap but getting 400 error

### ISSUE THREAD

**Issue by nbunneysky** [Homebrew/homebrew-services#193]
~ $ brew doctor
Your system is ready to brew.
~ $ brew -v
Homebrew 2.1.7
Homebrew/homebrew-core (git revision e64f; last commit 2019-07-17)
Homebrew/homebrew-cask (git revision c2852; last commit 2019-07-17)
~ $ brew tap homebrew/services 
==> Tapping homebrew/services 
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services '...
fatal: unable to access 'https://github.com/Homebrew/homebrew-services /': The requested URL returned error: 400
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-services\  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services\  --depth=1` exited with 128.

**Comment by nbunneysky** [comment]
Thought it was permissions related but it is not best I can tell....

**Comment by nbunneysky** [comment]
Interesting it worked this way instead....
~ $ brew services start mysql 
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 12 (delta 0), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
Tapped 1 command (41 files, 58.8KB).
Error: No available formula with the name "mysql "

**Comment by MikeMcQuaid** [comment]
You'll need to figure this out yourself as both issues are with your setup.
