### ISSUE TITLE
services - Unknown command: services still exist on MacOS 10.15.3

### ISSUE THREAD

**Issue by LYJSPEEDX** [Homebrew/homebrew-services#209]
**This error still occurred on MacOS 10.15.3.**
I have untap the homebrew/services repository and retap it, and then what shown in console proved the existence of issue.
I have update homebrew to lastest version. And I also follow the [revert instruction](https://github.com/Homebrew/homebrew-services/issues/206#issue-558905341)here, but it not works for me.

`brew services` worked perfectly properly before.
I dont know whether is the update of MacOS or homebrew-services led to this issue.
Thanks!
<img width="724" alt="service" src="https://user-images.githubusercontent.com/26499797/73999025-6f593880-499e-11ea-8022-62c5364e1cb2.png">

**Comment by yang00** [comment]
I have this problem, too. But  after I  run 'brew update' in terminal ,  'brew services' just work well. The last version was 'Updated Homebrew from a1939cfe7 to f144f6317'...

**Comment by MikeMcQuaid** [comment]
Please do not duplicate closed issues that are not locked.
