### ISSUE TITLE
Permission denied on El Captain

### ISSUE THREAD

**Issue by falmp** [Homebrew/homebrew-services#21]
Is it supposed to stop working with the new El Captain security directives?

Should I use sudo to start/stop/restart my services from now on?

```
$ brew services start redis
Error: Permission denied - /Users/falmp/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

**Comment by aried3r** [comment]
I had no problems using it. I'm not sure if I can help since I only started using it yesterday, but does `brew doctor` give any clue?

**Comment by mikemcquaid** [comment]
Working here. Perhaps you need to manually fix some permissions?

**Comment by falmp** [comment]
Sorry about the long delay on my response, but yes, I tested today and there were some permissions wrong, everything's working as expected now. Thanks!

**Comment by mhwalsh** [comment]
@falmp could you elaborate on what the permissions you needed to change? What permissions do you need to have on the LaunchAgents directory for brew services to be happy?  Thanks in advance!

**Comment by falmp** [comment]
@mhwalsh I don't actually recall, but checking my directory now I have `/Users/$USER/Library/LaunchAgent` and all files inside this directory owned by my user and group `staff`. So you could try:

`chown -R $USER: /Users/$USER/Library/LaunchAgents`
