### ISSUE TITLE
Adding completions

### ISSUE THREAD

**Issue by michaelblyons** [Homebrew/homebrew-services#212]
I notice that you're the only [external commands](https://docs.brew.sh/External-Commands) tap with completions. Is this a thing that other taps can do, too?

https://github.com/Homebrew/homebrew-services/blob/70bb37228cd73f3bdc30b971217fbdf0800e22ac/completions/bash/brew-services#L25-L35

Looking at the code above, it seems like only one tap gets to be the "special" one to use itself instead of `_brew`. I'd like to add completions to another external commands tap, but I don't want it to have to know about all of its siblings that may or may not be tapped.

**Comment by MikeMcQuaid** [comment]
> Is this a thing that other taps can do, too?

Yep.

Beyond that, I'm not sure what you're asking/how this is actionable.

**Comment by michaelblyons** [comment]
> Beyond that, I'm not sure what you're asking/how this is actionable.

Let me expand a little bit to see if I can make my question more clear:

If I make a tap that adds `brew foo`, and I do what you're doing here, I think it will _break_ completion for `brew services`...

``` sh
_brew_with_foo() { 
   if [ $COMP_CWORD -gt 1 ] && [ "${COMP_WORDS[1]}" = "foo" ] ; then 
     # brew foo xxx yyy zzz 
     _brew_foo
     return 
   fi 
  # Does not have any knowledge of `brew services`
   _brew 
 } 
  
 # Now we have a new completion f'n for `brew` that doesn't include `brew services` completions 
 complete -o bashdefault -o default -F _brew_with_foo brew
```

I could do something like this to add `brew services` completions back in:

``` sh
_brew_with_foo() { 
   if [ $COMP_CWORD -gt 1 ] && [ "${COMP_WORDS[1]}" = "foo" ] ; then 
     # brew foo xxx yyy zzz 
     _brew_foo
     return
   elif [ $COMP_CWORD -gt 1 ] && [ "${COMP_WORDS[1]}" = "services" ] ; then 
     # brew services xxx yyy zzz 
     _brew_services 
     return 
   fi 
   _brew 
 } 
  
 # Now we have a new completion f'n for `brew` that knows both tapped completions 
 complete -o bashdefault -o default -F _brew_with_foo brew
```

but if I add yet a third tap with `brew baz`, its completion function needs to know about all tapped completion functions and somehow bind them together.

Is there a way to set up completions without (a) caring about other taps and (b) ruining the completions that they've established?

**Comment by MikeMcQuaid** [comment]
> Is there a way to set up completions without (a) caring about other taps and (b) ruining the completions that they've established?

Sorry, don't know. Try it and see!
