### ISSUE TITLE
Fatal errors in starting nginx do not get detected/shown by brew services

### ISSUE THREAD

**Issue by alexweissman** [Homebrew/homebrew-services#215]
When I ran `brew services start nginx`, I would get a message saying that the service had been successfully started. This was also reflected in the output of `brew services list`. However when I checked my running processes, there was no sign of `nginx` actually running. Even more baffling, if I ran `sudo brew services start nginx`, then the `nginx` process _would_ finally appear.

What I finally realized was that `nginx` was failing to start because of a permissions issue that only occurred when I tried to start it as an ordinary user. In my case, it was because my nginx logs in `/usr/local/var/log/nginx` were owned by the root user, and my shell user did not have write access. So, nginx would fail to start.

The problem appears to be that brew is unaware when nginx fails to launch because of a configuration or permissions issue. This is a problem because I need to frequently reload nginx when making changes to configuration files, which often cause errors I need to fix. I would like to see that nginx failed to load (and the error output) when I run `brew services restart nginx`.

Is this possible?

**Comment by MikeMcQuaid** [comment]
> I would like to see that nginx failed to load (and the error output) when I run `brew services restart nginx`.

No, not really, sorry. `brew services` is a thin wrapper around `launchctl` and it does not provide that information.

**Comment by alexweissman** [comment]
Do you have an alternative suggestion for where this could be implemented, then? It's a real UX issue at the moment.

**Comment by MikeMcQuaid** [comment]
We're aware of that. If there was easy solutions: we'd have done them. We'll review PRs to make the situation better.
