### ISSUE TITLE
brew services error when running brew bundle dump

### ISSUE THREAD

**Issue by setu4993** [Homebrew/homebrew-services#218]
I am seeing this error when time I try to run `brew bundle dump` or `brew services`
> Warning: No services available to control with `brew services`

**Comment by setu4993** [comment]
Results from `brew config`, in case it helps:
```bash
HOMEBREW_VERSION: 2.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: e2bc0fa6879ce4c74ea2d8f8c654c9812f776b43
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 77b56561a896b9159b0e2990ad6cfcfb8014a5f4
Core tap last commit: 7 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_191
macOS: 10.15.3-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: 11.4.1
```

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by setu4993** [comment]
I was trying to run `brew bundle dump`, and saw the warning. I then tried running `brew services` to see what services were running, and saw the same warning (and no list).

I just started seeing this yesterday, before which everything both `bundle` and `services` worked without warnings.

**Comment by MikeMcQuaid** [comment]
Sorry, nothing has changed here in the last day, something must have changed on your machine. You'll need to figure that out yourself.

**Comment by setu4993** [comment]
Probably, but what could be wrong given that that is the error message I'm seeing? I do not run / use any services from homebrew. What are possible troubleshooting steps I can take?

**Comment by MikeMcQuaid** [comment]
You will need to figure out the rest yourself.

**Comment by MikeMcQuaid** [comment]
@setu4993 Please don't just 👎 my comments, it's rude. You have not submitted any information here that I can possibly use to debug your issues or help you in any way. You're asking me for help: it's your job, not mine, to provide the necessary information I need to help you solve your problem.

**Comment by setu4993** [comment]
@MikeMcQuaid : Sorry, but your reply was not helpful and definitely curt. I understand your point, but I shared all of the details that I had including the fact that it started appearing out of nowhere while nothing (from the homebrew perspective) had changed about my environment or machine. Also, this is the first time I have opened an issue on any of the homebrew repos, I looked at other issues before opening this one to see if there was a similar one elsewhere, and used information I gathered from those issues to troubleshoot before I opened this issue (and shared the config report after referring to those). I haven't worked with homebrew outside installing packages, and frequently taking a backup of my installed packages. Given that level of familiarity, I tried things I could find before opening this issue, and didn't receive any help / pointers / directions on what possible troubleshooting.

No matter what your impression of this issue was, I do not think "You will need to figure out the rest yourself." was a fair response.

**Comment by MikeMcQuaid** [comment]
> I do not think "You will need to figure out the rest yourself." was a fair response.

Sorry, it is a fair response. You're using software run by volunteers in their free time. I'd suggest reading https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/ before opening bug reports on other repositories.
