### ISSUE TITLE
Starting services as root with first argument "sh" does not work

### ISSUE THREAD

**Issue by schribl** [Homebrew/homebrew-services#219]
**What did I try:**
I wanted to start `node_exporter` as root to start it on boot time.
`sudo brew services start node_exporter`
**What did I expect:**
Node exporter started and added to services started at boot and running.
**What happend:**
`Error: No such file or directory @ realpath_rec - <cwd>/sh`
**What I did to debug this issue:**
I created the file that was missing by `touch` and then saw that `brew services` was changing the ownership of `<cwd>/sh` and `<cwd>` to `root:admin`. After looking a little bit into the files I found that in the formula (https://github.com/Homebrew/homebrew-core/blob/master/Formula/node_exporter.rb) in the plist the first argument is sh to use a file to get the arguments for `node_exporter`. After looking a little bit into this repository I found this lines (https://github.com/Homebrew/homebrew-services/blob/master/lib/services_cli.rb#L305) where the first argument is extracted to change ownership.

So I do not know if this is a issue in the formula but the error message could have been more meaningful. If plist files with first arguments like this are valid then they should be excluded from ownership change I think. Also a warning can inform the user that such plist files are not supported and he has to manually change ownership for relevant files followed by the list of arguments. Unfortunately I do not know Ruby so I could only create a bad quality PR I guess.

**Comment by MikeMcQuaid** [comment]
> Unfortunately I do not know Ruby so I could only create a bad quality PR I guess.

Would love you to try: you understand your problem and I can help you with bad Ruby for sure!

**Comment by MikeMcQuaid** [comment]
> So I do not know if this is a issue in the formula

I think the formula is weird, for sure. Does it work as non-root?

**Comment by schribl** [comment]
> > So I do not know if this is a issue in the formula
> 
> I think the formula is weird, for sure. Does it work as non-root?

I tested it as a normal user and it works fine for me. As root the error is reproducible. I checked some documentation and created a PR. I added my fork as remote and tested my changes with normal user and root and it worked as expected for me.
