### ISSUE TITLE
lib/service uses deprecated Formula#installed

### ISSUE THREAD

**Issue by jabenninghoff** [Homebrew/homebrew-services#224]
**What you were trying to do (and why)**
running `brew bundle check --global` to verify installed formulae and casks

**What happened**
receiving a warning multiple times:
```
Warning: Calling Formula#installed? is deprecated! Use Formula#latest_version_installed? (or Formula#any_version_installed? ) instead.
Please report this issue to the homebrew/services tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service.rb:53
```
the command did otherwise complete successfully

**What you expected to happen**
no warnings.

**Step-by-step reproduction instructions (with as minimal input data as possible)**
```
$ brew bundle dump --global
$ brew bundle check --global
```

This should be easy to fix; I just don't have a test environment set up to develop a PR.

**Comment by jabenninghoff** [comment]
Thanks @MikeMcQuaid !

**Comment by MikeMcQuaid** [comment]
You're welcome, thanks for the report!
