### ISSUE TITLE
Stop a service without stopping it restarting on reboot

### ISSUE THREAD

**Issue by ephexeve** [Homebrew/homebrew-services#23]
When doing a ```brew services stop x``` it stops x and removes it from starting on the next boot. Is there a way I can stop a services for my current session only? When rebooting, it starts the services back again?

Systemctl does that already, looking for the same behavior.

**Comment by mikemcquaid** [comment]
We don't support that currently and I could see the behaviour change being potentially confusing. For now I'd recommend just using `launchctl` until we have another command.

**Comment by SteveBenner** [comment]
https://github.com/eddiezane/lunchy is also pretty great

**Comment by kbrock** [comment]
Thanks for taking on `brew services` very cool.

I think this is asking the question in a different way. Is there a way to stop a service without uninstalling it?
I guess I was hoping for something more like:

command|effect
---|---
install|`ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents`
start|`launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist`
stop|`launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist`
uninstall|`rm ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist`

NOTE: I just used the `brew info postgresql`, and used only for illustration purposes. What ever you're doing now in terms of installing and starting is great - don't change.

But the distinction between installing a service and actually starting/stopping it is what I'm trying to get across. This seems closes to what linux `service` does.

Thanks again for the great tool.

**Comment by mikemcquaid** [comment]
Passing on this feature request, sorry!
