### ISSUE TITLE
Consul start script parameters

### ISSUE THREAD

**Issue by fuatkarakus** [Homebrew/homebrew-services#239]
**Expected Behavior**
When start consul with `brew services start consul` the consul key-value storage should be persist.
**Actual Behavior**
Consul KV stores is not persist because `brew services start consul` run with `-dev` parameter default in `homebrew.mxcl.consul.plist` file.

Could you please remove the `-dev` parameter from default ?

**Comment by MikeMcQuaid** [comment]
> Could you please remove the `-dev` parameter from default ?

Please submit a PR to homebrew-core to do that. Thanks!
