### ISSUE TITLE
nginx not serving from localhost

### ISSUE THREAD

**Issue by anthonybrown** [Homebrew/homebrew-services#25]
I use `brew-services` and love it but recently I noticed my `nginx` server is no longer serving files from `localhost:8080`    

It will serve from `127.0.0.1:8080`

Any ideas if this has something to do with running everything from `brew-services`?

I've installed all my software with `brew` PHP56, mysql, redis, memcached etc and things were working like expected until a couple of `brew upgrade` ago.

**Comment by anthonybrown** [comment]
I'm going to try and install `nginx` from the `Homebrew Nginx tap` repo and see if installing `nginx-full` works.

**Comment by anthonybrown** [comment]
After removing `nginx` and installing `nginx-full`

I'm getting the same behavior, files are being served from 127.0.0.1 but not loading from localhost, which is very strange because my host file says: `127.0.0.1 localhost`

**Comment by anthonybrown** [comment]
Here is the [gist](https://gist.github.com/394d69cfd9be84e2bdbf)

**Comment by mikemcquaid** [comment]
If both `nginx` and `nginx-full` are producing the same effect it seems like it's an nginx configuration issue.

**Comment by gapple** [comment]
Saw that you solved this in nginx config by adding an ipv6 listen rule

**Comment by anthonybrown** [comment]
sorry, forgot about my ticket here. Yep, quick fix, thanks @mikemcquaid
