### ISSUE TITLE
how to fix this when use brew services list?

### ISSUE THREAD

**Issue by raoxb** [Homebrew/homebrew-services#252]
Error: undefined method `named' for #<OptionParser:0x00007ff4c02f0be0>
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:65:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:48:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'

**Comment by MikeMcQuaid** [comment]
Run `brew update`.
