### ISSUE TITLE
Wrong service status reported for services with KeepAlive parameter

### ISSUE THREAD

**Issue by brfrth** [Homebrew/homebrew-services#275]
I am running the `spotifyd` service as defined [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/spotifyd.rb). When I boot my PC I need to connect to a VPN in order to gain internet access, I know this. The service definition contains KeepAlive, which will restart the service when it fails. This is exactly what I want, I'm fine with it failing, since I know it will restart. It's way more of a hassle to somehow wait for internet to attempt a start.

When the service fails, it will return exit code `101`, which is Rust's panic. Again, this is fine. Then once it starts up properly, it will stay open in the background, since it's run with the `--no-daemon` flag, as per the documentation of `spotifyd`. Though I assume staying open in the background is something a lot of services do. So the service will not exit again, but it will now have a PID and a state of `running`.

The `launchctl` reports this with the error code and the PID, since the error code is in fact the last exit status.

```
5150	101	homebrew.mxcl.spotifyd
```

But Homebrew now makes the assumption that the service is broken and shows an error.

```
spotifyd          error .../homebrew.mxcl.spotifyd.plist
```

The service is running fine, it just has not exited again after the last run. It has a PID. Why is it that Homebrew reports a service as `error` when it has a PID? This means the service is actively running and should mean that the last exit code isn't really relevant anymore. Maybe I'm understanding it wrong, but in my opinion an error exit code + a PID means the service is running fine, since it must have restarted.

**Comment by MikeMcQuaid** [comment]
Thanks for spelling this out clearly, I've wondered about this for a while and with your explanation a fix was pretty easy in https://github.com/Homebrew/homebrew-services/pull/276 (which stops my `brew services` from showing `error` on `mysql@5.7` which is running fine 😅).
