### ISSUE TITLE
Restart service on upgrade?

### ISSUE THREAD

**Issue by alindeman** [Homebrew/homebrew-services#279]
Is it possible to have a `homebrew-services`-managed service restart automatically when the formula is upgraded, if it's already been previously started/enabled by the user?

I have noticed that deleted (e.g., upgraded) binaries can no longer `fork` on macOS, so upgrading a background service that occasionally executes other processes breaks after `brew upgrade <formula>`. Right now I'm instructing our users to manually run `brew services restart <formula>` after upgrade, but it would be ideal if it could be done automatically.

I control the formula in this case, so I can add whatever is needed, but it's not clear to me how to hook into the upgrade procedure properly.

**Comment by MikeMcQuaid** [comment]
I think the main issue with this is that if there's e.g. configuration changes this may break the server that's running. 

`brew bundle` can accomplish this for you.

Will keep our eye out for more requests for this and consider it if we see more demand. Sorry!
