### ISSUE TITLE
Environment variables remplacement failed

### ISSUE THREAD

**Issue by jburdy** [Homebrew/homebrew-services#286]
Hi,
With:
`sudo brew services start XXX` we lose the environment variables ? See my post concerning telegraf.
https://github.com/influxdata/telegraf/issues/8484
Thanks for your help.

**Comment by MikeMcQuaid** [comment]
I don't know what you're asking, sorry.

**Comment by jburdy** [comment]
We cannot use environment variables in the configuration of "[telegraf](https://formulae.brew.sh/formula/telegraf)" if we go through "brew services" to launch its service.

Is there a notion of virtual environment with "brew services" ? Who would hide the environment variables?

The simple example of the "${USER}" in the default config doesn't work.

**Comment by MikeMcQuaid** [comment]
> We cannot use environment variables in the configuration of "[telegraf](https://formulae.brew.sh/formula/telegraf)" if we go through "brew services" to launch its service.

Yes, perhaps not.



> Is there a notion of virtual environment with "brew services" ?

No.



> Who would hide the environment variables?

`sudo` or `launchctl`.
