### ISSUE TITLE
Services running as root?

### ISSUE THREAD

**Issue by Coaxial** [Homebrew/homebrew-services#30]
AFAIK, running a service as root is against best practices because of the security implications. While 99% of brew's use cases are on developers machines, it still feels wrong to run services as root because it is a vector when you forget to stop said services and are on a public wifi, for instance.

Why run as root? Is there an alternative? Unless I'm mistaken, postgres runs under the postgres user when installed from brew and used with lunchy, will it start running as root if I use homebrew-services?

**Comment by mikemcquaid** [comment]
> Why run as root? Is there an alternative?

You shouldn't have to run as root. Can you confirm what is making you think you must? Thanks!

**Comment by Coaxial** [comment]
I don't want to run as root. I think I misread the README, I guess I was tired!
