### ISSUE TITLE
Support sending HUP signal

### ISSUE THREAD

**Issue by xrisk** [Homebrew/homebrew-services#315]
A lot of services support sending the HUP signal as a way to reload configuration without restarting. I see that launchctl also supports sending signals via `launchctl kill`. Can we support this please? 

I’ll be happy to write the PR if we want to have this feature.

**Comment by MikeMcQuaid** [comment]
My concern is: which services do? How do you know if they do/don't? What's the harm/advantage versus restarting the service? Why not do this directly through `launchctl`? 

Closing for now, let's keep discussing here but I wouldn't open a PR yet. Thanks!

**Comment by xrisk** [comment]
I understand that deciding whether or not a service supports reload via HUP is pretty hard. Two possibilities come to mind:

1. Allow new formulas to specify that this behavior is supported (I’m not a fan of this, it would require a large number of changes)

2. A generic solution which exposes an api of the form `brew services <SIGNAL> <service-name>`. The responsibility of passing appropriate signals is of course then on the user.

The reason for wanting this functionality in the first place is that it’s somewhat nontrivial to find the “domain” name  for a launchctl job. The solution I had to resort to involved looking up PIDs, and knowing the plist name.

If neither of these are acceptable, perhaps we can have a command that prints out the complete domain name for any service managed by us.

**Comment by MikeMcQuaid** [comment]
> If neither of these are acceptable, perhaps we can have a command that prints out the complete domain name for any service managed by us.

This seems like a better, more generic solution.
