### ISSUE TITLE
OSX brew services start errored with Bootstrap failed: 5: Input/output error when external drive

### ISSUE THREAD

**Issue by marczynski** [Homebrew/homebrew-services#321]
I installed MAMP on OSX via brew, and worked great. brew services list had green "started" statuses.
I changed my home dir to External drive using System Preferences > Users & Groups > Advanced Options > Home directory. I added Full disk access to terminal.app.I rsync everything to new destination. Still works great after rebooting.
However after brew services restart --all or ex brew services restart mariadb I got:

`
% brew services start --all
                        
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Volumes/Mini/Users/robert/Library/LaunchAgents/homebrew.mxcl.httpd.plist` exited with 5.
`

or 

`
% brew services start mariadb
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Volumes/Mini/Users/robert/Library/LaunchAgents/homebrew.mxcl.mariadb.plist` exited with 5.
`

brew services run still works only start/restart died.

When I changed Home dir to /Users back brew services works again so the case is connected with home path.

My os is Big Sur, Intel proc.

**Comment by MikeMcQuaid** [comment]
Sorry, you'll need to figure this out yourself.
