### ISSUE TITLE
dnsmasq - problem with service status on Apple Silicon M1

### ISSUE THREAD

**Issue by sb84** [Homebrew/homebrew-services#323]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.0.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed87211daa83982a6136e14d181a1550b46a0f17
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 02df6b76b81fa4e5ca13d3c7f4336d9a93c776e1
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false

% brew doctor
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I try correct start dnsmasq service.

### What happened (include all command output)?

It's start. It's working. But status is unknown.
```shell
$ brew services list
Name    Status  User    Plist
dnsmasq unknown root    /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql   started sbaczyk /Users/sbaczyk/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx   started sbaczyk /Users/sbaczyk/Library/LaunchAgents/homebrew.mxcl.nginx.plist
php     stopped
php@7.4 started sbaczyk /Users/sbaczyk/Library/LaunchAgents/homebrew.mxcl.php@7.4.plist
redis   started sbaczyk /Users/sbaczyk/Library/LaunchAgents/homebrew.mxcl.redis.plist
```
```shell
$ ping test90.local
PING test90.local (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.059 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.124 ms
^C
--- test90.local ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.059/0.091/0.124/0.033 ms
```
```shell
$ sudo lsof -nP -iUDP | grep :53
mDNSRespo   208 _mdnsresponder    6u  IPv4 0x4316bcf762302a5      0t0  UDP *:5353
mDNSRespo   208 _mdnsresponder    7u  IPv6 0x4316bcf7622d70d      0t0  UDP *:5353
Commander  5611        sbaczyk   24u  IPv4 0x4316bcf7475f9ed      0t0  UDP *:53671
dnsmasq   19828         nobody    4u  IPv4 0x4316bcf7622f705      0t0  UDP 10.0.0.222:53
dnsmasq   19828         nobody    6u  IPv4 0x4316bcf7622ffbd      0t0  UDP 127.0.0.1:53
dnsmasq   19828         nobody    8u  IPv6 0x4316bcf7622d13d      0t0  UDP [fe80:10::9f5:a4eb:80c7:478a]:53
dnsmasq   19828         nobody   10u  IPv6 0x4316bcf7622e87d      0t0  UDP [fe80:f::c6d6:4b39:3453:5eb0]:53
dnsmasq   19828         nobody   12u  IPv6 0x4316bcf7622ee4d      0t0  UDP [fe80:e::604c:88ff:feb3:f84d]:53
dnsmasq   19828         nobody   14u  IPv6 0x4316bcf7622d9f5      0t0  UDP [fe80:d::604c:88ff:feb3:f84d]:53
dnsmasq   19828         nobody   16u  IPv6 0x4316bcf7616a87d      0t0  UDP [fe80:b::140c:6b55:cf47:9a25]:53
dnsmasq   19828         nobody   18u  IPv6 0x4316bcf76169cdd      0t0  UDP [fe80:5::1c00:62ff:fe3c:4c68]:53
dnsmasq   19828         nobody   20u  IPv6 0x4316bcf7616b41d      0t0  UDP [fe80:4::1c00:62ff:fe3c:4c69]:53
dnsmasq   19828         nobody   22u  IPv6 0x4316bcf7616ab65      0t0  UDP [fe80:1::1]:53
dnsmasq   19828         nobody   24u  IPv6 0x4316bcf7616ae4d      0t0  UDP [::1]:53
```
### What did you expect to happen?

To the status of running the service was correct.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install dnsmasq
echo 'address=/.local/127.0.0.1' > /opt/homebrew/etc/dnsmasq.conf
sudo brew services start dnsmasq
brew services list
```

**Comment by SMillerDev** [comment]
It doesn't seem to be an install issue so I transfered it to the services repo

**Comment by MikeMcQuaid** [comment]
@sb84 What's the output of `launchctl list | grep dnsmasq` and `ps aux | grep dnsmasq` and `brew services list | grep dnsmasq`?

**Comment by sb84** [comment]
`sbaczyk@M1 ~ % sudo brew services start dnsmasq
Warning: Taking root:admin ownership of some dnsmasq paths:
  /opt/homebrew/Cellar/dnsmasq/2.84/sbin
  /opt/homebrew/Cellar/dnsmasq/2.84/sbin/dnsmasq
  /opt/homebrew/opt/dnsmasq
  /opt/homebrew/opt/dnsmasq/sbin
  /opt/homebrew/var/homebrew/linked/dnsmasq
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
==> Successfully started `dnsmasq` (label: homebrew.mxcl.dnsmasq)
sbaczyk@M1 ~ % launchctl list | grep dnsmasq
sbaczyk@M1 ~ % ps aux | grep dnsmasq
nobody           22799   0,0  0,0 408114032   1776 s003  T     9:30     0:00.03 /opt/homebrew/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /opt/homebrew/etc/dnsmasq.conf -7 /opt/homebrew/etc/dnsmasq.d,*.conf
root             22798   0,0  0,1 408394832  10512 s003  T     9:30     0:00.05 sudo /opt/homebrew/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /opt/homebrew/etc/dnsmasq.conf -7 /opt/homebrew/etc/dnsmasq.d,*.conf
sbaczyk          23480   0,0  0,0 408103296   1264 s003  S+   12:38     0:00.00 grep dnsmasq
sbaczyk@M1 ~ % brew services list | grep dnsmasq
dnsmasq unknown root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
sbaczyk@M1 ~ %`

**Comment by sb84** [comment]
```
sbaczyk@M1 ~ % sudo brew services start dnsmasq
Warning: Taking root:admin ownership of some dnsmasq paths:
  /opt/homebrew/Cellar/dnsmasq/2.84/sbin
  /opt/homebrew/Cellar/dnsmasq/2.84/sbin/dnsmasq
  /opt/homebrew/opt/dnsmasq
  /opt/homebrew/opt/dnsmasq/sbin
  /opt/homebrew/var/homebrew/linked/dnsmasq
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
==> Successfully started `dnsmasq` (label: homebrew.mxcl.dnsmasq)
sbaczyk@M1 ~ % launchctl list | grep dnsmasq
sbaczyk@M1 ~ % ps aux | grep dnsmasq
nobody           22799   0,0  0,0 408114032   1776 s003  T     9:30     0:00.03 /opt/homebrew/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /opt/homebrew/etc/dnsmasq.conf -7 /opt/homebrew/etc/dnsmasq.d,*.conf
root             22798   0,0  0,1 408394832  10512 s003  T     9:30     0:00.05 sudo /opt/homebrew/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /opt/homebrew/etc/dnsmasq.conf -7 /opt/homebrew/etc/dnsmasq.d,*.conf
sbaczyk          23480   0,0  0,0 408103296   1264 s003  S+   12:38     0:00.00 grep dnsmasq
sbaczyk@M1 ~ % brew services list | grep dnsmasq
dnsmasq unknown root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
sbaczyk@M1 ~ %
```

**Comment by MikeMcQuaid** [comment]
Looks like it's:
- running twice
- `launchctl` can't find the `pid`

This may be an issue with your local machine or may be an issue with the `dnsmasq` plist. It's not a Homebrew/services issue.

**Comment by sb84** [comment]
> This may be an issue with your local machine or may be an issue with the `dnsmasq` plist. It's not a Homebrew/services issue.

So where should I direct my inquiry? 
Can you refer the ticket to the appropriate section?

**Comment by MikeMcQuaid** [comment]
@sb84 You'll need to figure this out yourself for now. We'll review a pull request if you can come up with a fix.

**Comment by sb84** [comment]
> @sb84 You'll need to figure this out yourself for now. We'll review a pull request if you can come up with a fix.

Are you able to give me any advice what should I check?
Or what keywords should I dig on Google for?

**Comment by MikeMcQuaid** [comment]
Sorry, no.

**Comment by MikeMcQuaid** [comment]
Others may be able to!

**Comment by sb84** [comment]
I don't know what the reason is
but in the end, for my own needs, I solved it like this
that I run the dnsmasq service as a normal user, but on port other than 53 (for me it is 8053), and additionally I set up a local redirection of calls from port 53 to 8053

`echo "rdr pass inet proto udp from any to 127.0.0.1 port 53 -> 127.0.0.1 port 8053" | sudo pfctl -ef -`

the service is green and all calls from X.local are directed to 127.0.0.1

I don't know who is responsible for the dnsmasq package exactly,
I am also not privy enough to prepare some solutions, if you think it is right, then direct it to the right people
