### ISSUE TITLE
Services status shown as "unknown"

### ISSUE THREAD

**Issue by instanttim** [Homebrew/homebrew-services#337]
on macOS 11.3.1 (20E241), my services are listed as unknown even though the appear to be working... fully updated Homebrew, uninstalled and reinstalled all the services, same result.

```
Name      Status  User    Plist
dnsmasq   unknown root    /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql@5.7 started tmartin /Users/tmartin/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx     unknown root    /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php@7.3   unknown root    /Library/LaunchDaemons/homebrew.mxcl.php@7.3.plist
```

**Comment by instanttim** [comment]
`launchctl list | grep dnsmasq` shows no results, but `ps aux` shows dnsmasq running just fine. And it's functioning.

**Comment by MikeMcQuaid** [comment]
> `launchctl list | grep dnsmasq` shows no results

This is why it is unknown. If it's not causing you problems: don't worry about it. If you'd like to debug/fix this: you'll need to investigate why the plist isn't loading and perhaps use `brew edit dnsmasq` to fix/improve it (and submit a pull request). This is not a `brew services` issue, sorry.
