### ISSUE TITLE
dnsmasq causes `brew services list` to crash

### ISSUE THREAD

**Issue by csalch-indeed** [Homebrew/homebrew-services#339]
I've started seeing this happening today:

```
homebrew % sudo brew services start dnsmasq
Warning: Taking root:admin ownership of some dnsmasq paths:
  /opt/homebrew/Cellar/dnsmasq/2.85/sbin
  /opt/homebrew/Cellar/dnsmasq/2.85/sbin/dnsmasq
  /opt/homebrew/opt/dnsmasq
  /opt/homebrew/opt/dnsmasq/sbin
  /opt/homebrew/var/homebrew/linked/dnsmasq
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
==> Successfully started `dnsmasq` (label: homebrew.mxcl.dnsmasq)
homebrew % brew services list
Error: Failure while executing; `/bin/launchctl\ list\ \'homebrew.mxcl.dnsmasq\'` exited with 113. Here's the output:
```

It looks like it is related to https://github.com/Homebrew/homebrew-services/commit/bcf1fa6333df22b7ebdffb7833b60f5515e4bbc3#diff-642a732918ee1aeca833e8380816320040a75eb97db5c2743e56e5ad71fc3626R75

The dnsmasq package claims it needs to run as root:
```
homebrew % brew services start dnsmasq
Warning: dnsmasq must be run as root to start at system startup!
==> Successfully started `dnsmasq` (label: homebrew.mxcl.dnsmasq)
```
and it seems to be the fact that that plist was started as root that's causing it to error out ...

**Comment by mokeyish** [comment]
<img width="1369" alt="图片" src="https://user-images.githubusercontent.com/16131917/118924725-12557c00-b970-11eb-9fb4-9e1f565b3c61.png">

**Comment by mokeyish** [comment]
I use `@status ||= Utils.safe_popen_read("#{ServicesCli.launchctl} list '#{label}' || echo ''").chomp` to fixe errors.

**Comment by SMillerDev** [comment]
What is the output of this after you started dnsmasq?
```
/bin/launchctl list 'homebrew.mxcl.dnsmasq'
```

**Comment by twdnhfr** [comment]
basically the same issue here, its alternating between mysql and dnsmasq:

![bsl_issue](https://user-images.githubusercontent.com/13796752/118947567-c39be800-b957-11eb-84ed-8cf7dede9f7b.png)

**Comment by SMillerDev** [comment]
How about `/bin/launchctl list | grep 'homebrew.mxcl.dnsmasq'` in this scenario? (and can you post the output as a code block, images are much harder to work with)

**Comment by twdnhfr** [comment]
Sure: 

❯ /bin/launchctl list | grep 'homebrew.mxcl.dnsmasq'

❯ /bin/launchctl list | grep 'homebrew.mxcl.mysql'
474	0	homebrew.mxcl.mysql

dnsmasq has no output in this case

with sudo:
❯ sudo /bin/launchctl list | grep 'homebrew.mxcl.dnsmasq'
65	0	homebrew.mxcl.dnsmasq

❯ sudo brew services list
Error: Failure while executing; `/bin/launchctl\ list\ \'homebrew.mxcl.mysql\'` exited with 113. Here's the output:

**Comment by SMillerDev** [comment]
Yeah, I guess we need to allow a failing command here (without output)

**Comment by MikeMcQuaid** [comment]
@SMillerDev Yes. Can you open a PR?

**Comment by SMillerDev** [comment]
Not right now, but yes

**Comment by MikeMcQuaid** [comment]
No worries, I got you.
