### ISSUE TITLE
Support for custom plist

### ISSUE THREAD

**Issue by pgrenaud** [Homebrew/homebrew-services#349]
Greetings,

I notice with today's latest PR (b43d46eb547782f7bd4d01ee1b9df9980d88e15c) that the support for custom plist was silently dropped. Is there any reason why that feature was removed?

We have build a set of tool for our developers that rely on custom plist to be able to run two different versions of MySQL at once. The plist provided by homebrew are in conflict with one another and the only way to make them both run is to provide custom plist with different `datadir`, `socket` and `port`.

Would it be possible to revert this change and bring back custom plist support?

Thank you!

**Comment by SMillerDev** [comment]
It was never documented anywhere so I did not consider it supported. It also made the code much more complex. But if people want to add it back and actually document it I would gladly review a PR.

**Comment by MikeMcQuaid** [comment]
@SMillerDev I wasn't aware when I was reviewing that the support was being dropped so reverting based in number of 👍🏻s in here in https://github.com/Homebrew/homebrew-services/pull/352. 

@pgrenaud or others: after the revert would love to have some documentation added for this to the manpage/README and some tests. Shout if I can help with that.

**Comment by pgrenaud** [comment]
Unfortunately, I won't be able to help with the tests since my knowledge of ruby is very limited.

For the documentation, do you mean the `usage_banner` in [cmd/services.rb](https://github.com/Homebrew/homebrew-services/blob/master/cmd/services.rb)?

**Comment by MikeMcQuaid** [comment]
> For the documentation, do you mean the `usage_banner` in [cmd/services.rb](https://github.com/Homebrew/homebrew-services/blob/master/cmd/services.rb)?

Yes please! That and the README would be great.



> Unfortunately, I won't be able to help with the tests since my knowledge of ruby is very limited.

No worries!

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-services/pull/353 will actually take care of that
