### ISSUE TITLE
Can't remove service

### ISSUE THREAD

**Issue by distinctdan** [Homebrew/homebrew-services#358]
I have a service that homebrew refuses to remove.
I'm trying to remove `emqx`.
```
my.name@computer ~ % sudo brew services list         
Name    Status  User Plist
emqx    stopped      
unbound stopped   
```

However, trying to stop it errors:
```
my.name@computer ~ % sudo brew services stop emqx
Error: Service `emqx` is not started.
```

And cleanup does nothing:
```
my.name@computer ~ % sudo brew services cleanup  
All root services OK, nothing cleaned...
my.name@computer ~ % brew services cleanup
All user-space services OK, nothing cleaned...
```

Why can't I remove this service? It was added via homebrew, so it ought to be removable via homebrew.

**Comment by SMillerDev** [comment]
`brew remove emqx` will remove the formulae from your system and therefore out of this list.

**Comment by distinctdan** [comment]
So I actually do need the emqx package, I just needed it removed from the services list. Uninstalling it and reinstalling it did work, so thanks for that, although it seems like it should have been possible to remove it from the services list without reinstalling.

**Comment by SMillerDev** [comment]
> although it seems like it should have been possible to remove it from the services list without reinstalling

It shows up because it's installed. `brew services` will show any brew services that has a service installed.
