### ISSUE TITLE
Multiple services started in a row are bootstrapped using the same plist file

### ISSUE THREAD

**Issue by MrSerth** [Homebrew/homebrew-services#362]
About a month ago, I started having issues starting multiple services and registering these with launchctl. From time to time, I execute the following command:

```bash
brew services start --all
```

Having about five services, I regularly and reproducibly get the following error:

```
==> Successfully started `nginx` (label: homebrew.mxcl.nginx)
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/<username>/Library/LaunchAgents/homebrew.mxcl.nginx.plist` exited with 5.
```

When repeating the same command without doing anything in between, I get the following output:

```
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/<username>/Library/LaunchAgents/homebrew.mxcl.postgresql.plist` exited with 5.
```

I was then able to reissue the command multiple times until all services were running. However, this impedes issuing a command to all services.

Today, I was able to further narrow down the issue: The error `Bootstrap failed: 5: Input/output error` is generated with a non-root user issuing the bootstrap command. When running the same command with root privileges (after the service was requested to start):

```bash
sudo /bin/launchctl bootstrap gui/501 /Users/<username>/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
```

I get the following error:

```
/Users/<username>/Library/LaunchAgents/homebrew.mxcl.nginx.plist: service already bootstrapped
Bootstrap failed: 37: Operation already in progress
```

As the normal `bootout` and `bootstrap` commands worked as expected with the generated plist file, I concluded that brew services was actually issuing the `bootstrap` command twice. And indeed, repeating my initial request with more log output (using `brew services start --all --debug --verbose`) revealed:

```
/bin/launchctl enable gui/501/homebrew.mxcl.rabbitmq
/bin/launchctl bootstrap gui/501 /Users/<usernem>/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
==> Successfully started `rabbitmq` (label: homebrew.mxcl.rabbitmq)
/bin/launchctl enable gui/501/homebrew.mxcl.redis
/bin/launchctl bootstrap gui/501 /Users/<username>/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/<username>/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist` exited with 5.
```

Even though the correct service is *enabled* in the first with `launchctl`, the *bootstrapping* is always performed with the same service.

___

Inspecting the code reveals that probably the wrong plist is used to bootstrap services in a row. I assume, that the following lines and the lazy initialization of `@plist` is causing this issue: https://github.com/Homebrew/homebrew-services/blob/c8f71846b2ee29c46a9557f9a03f106d5d2778d8/lib/services_cli.rb#L373-L376

When two or more services are started in a row, the `@plist` variable is initialized with the plist of the first service and not changed when launching the second service. This yields to the described behaviour of `launchctl` returning exit code 5. 

For my system, I locally modified line 376 to state the following which might not cover all edge cases:

```ruby
safe_system launchctl, "bootstrap", domain_target, service.plist
```

I would be really happy to see a long-term fix in the official brew services repo! Thanks 🙂

**Comment by MikeMcQuaid** [comment]
> When two or more services are started in a row, the `@plist` variable is initialized with the plist of the first service and not changed when launching the second service. This yields to the described behaviour of `launchctl` returning exit code 5.
> 
> For my system, I locally modified line 376 to state the following which might not cover all edge cases:
> 
> ```ruby
> safe_system launchctl, "bootstrap", domain_target, service.plist
> ```
> 
> I would be really happy to see a long-term fix in the official brew services repo! Thanks 🙂

Could you try and open a pull request? We're happy to walk you through the process.

Thanks!
