### ISSUE TITLE
"Bootstrap failed: 5: Input/output error" when having not the latest version of a package

### ISSUE THREAD

**Issue by 4ndv** [Homebrew/homebrew-services#363]
Here's the problem that occurs every time a new version of redis released:

```
$ brew services run redis

Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /opt/homebrew/Cellar/redis/6.2.5/homebrew.mxcl.redis.plist` exited with 5.
```

```
$ ls /opt/homebrew/Cellar/redis

6.2.4
```

For some reason, while trying to run the service it's looking for a latest known version, instead of a version installed at the moment.

I don't know, if it's a problem with the redis formula or with a brew services itself

**Comment by MikeMcQuaid** [comment]
I presume you haven't updated `redis` yet? Can you run `brew services run --verbose --debug redis` and repost the error here?

**Comment by 4ndv** [comment]
Unfortunately, I've already updated redis by the time of opening PR
