### ISSUE TITLE
Custom plists are no longer installed in the LaunchDaemons/LaunchAgents directories

### ISSUE THREAD

**Issue by pgrenaud** [Homebrew/homebrew-services#364]
Greetings,

Sorry to bother you again about this, but an issue still remain after my last issue (#349) and I took way to much time to notice it. The PR that added the `--file` argument (#353) changed the installation behaviour of custom plist files. That change cause services to not start after a system reboot.

Normally, plist files (customs and regulars) would be installed in the `LaunchDaemons`/`LaunchAgents` directories. Now, custom plist files are installed in different directory. For example, custom mysql plist are installed in `/usr/local/opt/mysql/homebrew.mxcl.mysql.plist` instead of `/Users/USERNAME/Library/LaunchAgents/homebrew.mxcl.mysql.plist`.

Would it be possible to restore the previous behaviour to ensure that the services start after a system reboot? I would love to make a PR myself, but Ruby is not a language that I practice often enough. However, I do think the issue is around this line: https://github.com/Homebrew/homebrew-services/blob/master/lib/services_cli.rb#L237

Thanks!

**Comment by MikeMcQuaid** [comment]
@SMillerDev could you take a look at this?

**Comment by SMillerDev** [comment]
Yeah, gonna try and have a look today

**Comment by convenient** [comment]
@SMillerDev @MikeMcQuaid Is it possible this is related to the issue I am seeing where services aren't going to the `stopped` status?

```bash
$ brew --version
Homebrew 3.2.6-116-gafc5804
Homebrew/homebrew-core (git revision 529ebf5af1; last commit 2021-08-12)
Homebrew/homebrew-cask (git revision d0ac4a7962; last commit 2021-08-12)
```

I have redis service running, see that it is `started`
```bash
$ brew services list | grep -E "Name|redis"
Name            Status  User        Plist
redis           started lukerodgers /Users/lukerodgers/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

I can properly restart it, see that it stays at `started`
```bash
$ brew services restart redis; brew services list | grep -E "Name|redis"
Stopping `redis`... (might take a while)
==> Successfully stopped `redis` (label: homebrew.mxcl.redis)
==> Successfully started `redis` (label: homebrew.mxcl.redis)
Name            Status  User        Plist
redis           started lukerodgers /Users/lukerodgers/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

However when I stop the service it goes to `unknown` status rather than `stopped` 

```bash
$ brew services stop redis; brew services list | grep -E "Name|redis"
Stopping `redis`... (might take a while)
==> Successfully stopped `redis` (label: homebrew.mxcl.redis)
Name            Status  User        Plist
redis           unknown
```

**Comment by convenient** [comment]
Actually, maybe https://github.com/Homebrew/homebrew-services/pull/350 could be the cause of the above @SMillerDev ? Rather than this issue.

**Comment by pgrenaud** [comment]
Thanks to everyone involved!

I've tested on my side and everything seems to work as intended! 👌
