### ISSUE TITLE
Describe steps to make an existing formula 'brew services' aware

### ISSUE THREAD

**Issue by MichaelRueegg** [Homebrew/homebrew-services#37]
Please provide instructions on how to make an existing formula working together with brew services. I have some formulas which register a plist file in /Library/LaunchDaemons, but these are not listed when I execute `brew services list`. What do I need to do?

**Comment by mikemcquaid** [comment]
Are they listed if you run `sudo brew services list`?

**Comment by MichaelRueegg** [comment]
No, it is not. What are the requirements for a daemon to be manageable by brew services?

**Comment by mikemcquaid** [comment]
What are the filenames of the `plist`s there?

**Comment by MichaelRueegg** [comment]
The one that is not working is `/Library/LaunchDaemons/com.crashplan.engine.plist`

**Comment by mikemcquaid** [comment]
`brew services` only manages those named `homebrew.mxcl.*.plist`

**Comment by MichaelRueegg** [comment]
Can I contribute to the crashplan brew formula so that it works with brew services? If yes, are there instructions anywhere on how to achieve that?

**Comment by mikemcquaid** [comment]
@MichaelRueegg That doesn't seem to be a Homebrew formula that's in the core repository. This is our general pull request guide: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by MichaelRueegg** [comment]
@mikemcquaid Thanks for the info. Coming from Linux I would highly appreciate to be able to easily handle services with brew. But if only some of the formulas are supported, it is hard to really use it in practice. What I don't understand is why this has to be restricted to the formulas that explicitly provide `homebrew.mxcl.*.plist` files. Can brew services not just support all plist files in `/Library/LaunchDaemons`? I mean wouldn't it just have to `launchctl load` and `launchctl unload` them? Please excuse my ignorance, I'm quite new to Mac OS X and brew :-)

**Comment by MichaelRueegg** [comment]
But then I guess it will only work with formulas where the author provides
such a file explicitly. That seriously restricts its usefulness imho. Do
you know why this has been done like this? Would you accept a pull request
where all plist files in /library/launchdaemons are considered?
Am 18.03.2016 18:54 schrieb "Mike McQuaid" <notifications@github.com>:

**Comment by mikemcquaid** [comment]
`brew services` requires Homebrew and is a tool designed to manage services installed by Homebrew so we wouldn't accept a PR that handles all plist files. There's other tools available that manage all OS X plists and I think you may be better suited with one of them.

**Comment by MichaelRueegg** [comment]
I installed Crashplan with brew cask (see https://github.com/caskroom/homebrew-cask/blob/master/Casks/crashplan.rb). Are casks not supported by brew services then? Or do I need to adapt the cask formula to provide a  `homebrew.mxcl.*.plist` file?

**Comment by mikemcquaid** [comment]
@MichaelRueegg Normally these things are autoinstalled and enabled/disabled by the applications themselves. Additionally, Cask plists are not supported by `brew services` due to the aforementioned reason.
