### ISSUE TITLE
Option to stop service without unregistering

### ISSUE THREAD

**Issue by SampsonCrowley** [Homebrew/homebrew-services#375]
@MikeMcQuaid would you be interested in making the services work more like systemd style running options?

There is currently no way to stop a running service without also unregistering it from launchctl. This feels dangerous to me.

In Systemd based Linux Distros I constantly (well, not constantly, but you know) stop, start, restart, status services and it has nothing to do with whether they are enabled to be started at boot. I can stop a currently running service without fear of forgetting to enable/start it again and know if it is a service that is enabled, it will always start at boot again unless specifically disabled.

I propose that we move to this same style:

<table>
  <thead>
    <tr>
      <th>
        Command
      </th>
      <th>
        Action
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <code>enable</code>
      </td>
      <td>
        register service to start at boot
      </td>
    </tr>
    <tr>
      <td>
        <code>disable</code>
      </td>
      <td>
        unregister service from autostarting at boot; does not immediately stop
      </td>
    </tr>
    <tr>
      <td colspan="2">
        Both of these two commands have puposefully no effect on whether a service is currently running or not. 
        <br/>
        Systemd has the <code>--immediate</code> flag for <code>enable</code> to both <code>enable</code> and <code>start</code> in a single command
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <hr><hr>
      </td>
    </tr>
    <tr>
      <td>
        <code>start</code>
      </td>
      <td>
        start service; does nothing if already running
      </td>
    </tr>
    <tr>
      <td>
        <code>stop</code>
      </td>
      <td>
        stop service; does nothing if not running
      </td>
    </tr>
    <tr>
      <td>
        <code>restart</code>
      </td>
      <td>
        start service; stopping already running service and restarting, or simply starting if not already running
      </td>
    </tr>
    <tr>
      <td>
        <code>status</code>
      </td>
      <td>
        get the current status of a service; whether it is currently running or not, maybe even the last few log lines if possible
      </td>
    </tr>
  <tbody>
</table>

However since this would be a breaking change for some commands that already exist there may need to be some different aliases instead for the above effects to avoid confusion.

Thoughts?

**Comment by SampsonCrowley** [comment]
Also I've seen an issue template mentioned in other issues before; but none pull up when opening an issue and I didn't immediately find one. If you want people to use an issue template, that should be added so that its automatic and people who aren't aware it's expected don't just skip it without knowing. It's a really easy thing to add if you'd like assistance getting an auto-template setup

**Comment by SMillerDev** [comment]
Currently `start` enables and starts and `run` just starts. So I think it already does pretty much what you're describing.

There is no way to just enable something but since launchctl leaves the start trigger to the service, this will require rewriting services on the fly. It's possible but I'd say it's not worth the effort.

**Comment by SampsonCrowley** [comment]
@SMillerDev I'm aware of start and run; My concern is in `stop`

**Comment by SampsonCrowley** [comment]
There is no way to `stop` without permanently unregistering the service and requiring users to remember to start/enable it again if its a service that should always start on boot

**Comment by SampsonCrowley** [comment]
If there is no interest in changing that behavior though, that is understandable

**Comment by MikeMcQuaid** [comment]
> There is currently no way to stop a running service without also unregistering it from launchctl.

This seems desirable.

> This feels dangerous to me.

I have no idea why this would be dangerous.

> However since this would be a breaking change for some commands that already exist

We cannot do this.

> If there is no interest in changing that behavior though, that is understandable

We cannot change the behaviour of `stop` to be as you describe. We could add something like `brew services pause` which takes the approach you're proposing. We'd review a PR to implement that.

**Comment by SMillerDev** [comment]
Or `brew services kill`, which should be pretty easy to do since we already have code for it.

**Comment by SampsonCrowley** [comment]
> > This feels dangerous to me.
> 
> I have no idea why this would be dangerous.

The reason it is dangerous is because it is a permanent change with no option of a temporary kill. A dev that is relying on a service to always start on boot but needs to stop it for some reason might forget to start it again (Murphy's Law, anything that can happen will happen).

There should be an option that does not have effects that are persisted past a reboot; same as `run`; `kill` or `pause` whichever term is decided on will fill this need.

> Or `brew services kill`, which should be pretty easy to do since we already have code for it.

I like `kill`. It feels more of an opposite to `run` and it wont make people think that the process has just been paused in memory and will be just brought back like swap  space.

I will try to see if I can find time to make a PR this week for a `kill` option

**Comment by MikeMcQuaid** [comment]
> I will try to see if I can find time to make a PR this week for a `kill` option

That'd be great, thanks! ❤️

**Comment by bartekpacia** [comment]
I think that, since #464 is merged, this issue can be closed.
