### ISSUE TITLE
Running brew services [re]start results in error

### ISSUE THREAD

**Issue by thecesrom** [Homebrew/homebrew-services#376]
I have created a formula on a tap I maintain and previously any `brew services [subcommand]` worked fine.

Formula [coatl-dev/coatl-dev/ignition](https://github.com/coatl-dev/homebrew-coatl-dev/blob/coatl/Formula/ignition.rb) installs `homebrew.mxcl.ignition.plist` under `/Users/{user}/Library/LaunchAgents` but running `brew services start ignition` or `brew services restart ignition` produces the same error:

```bash
$ brew services [re]start ignition
/Users/thecesrom/Library/LaunchAgents/homebrew.mxcl.ignition.plist: service already loaded
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/thecesrom/Library/LaunchAgents/homebrew.mxcl.ignition.plist` exited with 37.
```

`homebrew.mxcl.ignition.plist`:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>RunAtLoad</key>
	<true/>
	<key>Disabled</key>
	<false/>
	<key>Label</key>
	<string>com.inductiveautomation.ignition</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/ignition</string>
		<string>start</string>
	</array>
</dict>
</plist>
```

Running `brew services` shows the following:
```bash
$ brew services
Name     Status  User Plist
black    stopped      
ignition stopped      
unbound  stopped 
```

Even though the `ignition` service started at log in, and shows the following status:

```bash
$ ignition status
Ignition-Gateway (not installed) is running: PID:1961, Wrapper:STARTED, Java:STARTED
```

`brew` version:
```bash
$ brew --version
Homebrew 3.2.11-45-g40a7a01
Homebrew/homebrew-core (git revision 4f77196f8a; last commit 2021-09-09)
Homebrew/homebrew-cask (git revision 7edff39a8e; last commit 2021-09-09)
```

Please let me know if you need further detail.

Thanks in advance.

**Comment by SMillerDev** [comment]
That's because it uses a different label and installs itself instead of letting brew do it.

**Comment by thecesrom** [comment]
Sorry, but I don't understand what you mean.

Would you please explain the recommended corrective action for this case?

As I mention, previously I had no issue running `brew services`. The last time I checked was back in August 9, and `brew services start coatl-dev/coatl-dev/ignition` worked fine.

**Comment by thecesrom** [comment]
Should I uninstall and then install the formula?

Should I not `prefix.install_symlink "#{libexec}/com.inductiveautomation.ignition.plist" => "#{plist_name}.plist"` as part of the installation process?

**Comment by thecesrom** [comment]
I created that formula back in January based on the [Formula Cookbook - launchd-plist-files](https://docs.brew.sh/Formula-Cookbook#launchd-plist-files), but I'm seeing the following line on many formulae:

```ruby
plist_options startup: true
```

Is that preferred over the recommended method from the Formula Cookbook?

Thanks.

**Comment by SMillerDev** [comment]
What if you stop and start the service manually?

---
`plist_options startup: true` just means that it must be run at startup and can't be run as a normal user.

**Comment by thecesrom** [comment]
Starting and stopping the service works just fine.

```bash
$ ignition stop
Stopping Ignition-Gateway...
Stopped Ignition-Gateway.
$ ignition status
Ignition-Gateway (not installed) is not running.
$ ignition start
Starting Ignition-Gateway...
Waiting for Ignition-Gateway......
running: PID:2575
$ ignition status
Ignition-Gateway (not installed) is running: PID:2575, Wrapper:STARTED, Java:STARTED
```

It is only `brew services [re]start` that fails with the error from the first post.

**Comment by thecesrom** [comment]
Is there any information I could provide to get this fixed?

**Comment by MikeMcQuaid** [comment]
@SMillerDev is best person to answer that question.

**Comment by SMillerDev** [comment]
So, I actually had some time to look into this, and the issue is that it doesn't use a label that brew services uses. If I rename the label from `com.inductiveautomation.ignition` to `homebrew.mxcl.ignition` because now `brew services` can provide the correct label to `launchctl`. 

I don't think going back to the old way of checking services is a good idea, but you can easily fix it in the formula by doing something like: https://github.com/theseal/homebrew-ssh-askpass/commit/23886aa8021c1f9e36ae57c2fad5b5a691070fa0

**Comment by thecesrom** [comment]
I tried this approach on my local installation before making changes to the formula and it works.

**`plist`**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>RunAtLoad</key>
	<true/>
	<key>Disabled</key>
	<false/>
	<key>Label</key>
	<string>homebrew.mxcl.ignition</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/ignition</string>
		<string>start</string>
	</array>
</dict>
</plist>
```

**`brew services`**

```bash
$ brew services start ignition
==> Successfully started `ignition` (label: homebrew.mxcl.ignition)
$ brew services
Name     Status  User      Plist
ignition started thecesrom /Users/thecesrom/Library/LaunchAgents/homebrew.mxcl.ignition.plist
unbound  stopped
```

Thanks, @SMillerDev!
