### ISSUE TITLE
Logic inverted in running services as root vs user

### ISSUE THREAD

**Issue by naturalethic** [Homebrew/homebrew-services#38]
When running as root, you need to add the UserName key to the plist, however, the key is being added when running as local user, and not when running as root, causing almost (if not all) services to fail.

**Comment by naturalethic** [comment]
https://github.com/Homebrew/homebrew-services/pull/39

**Comment by gapple** [comment]
I've copied your description to the PR, and will close this issue in favour or the pull request.
