### ISSUE TITLE
Brew services list gave me error

### ISSUE THREAD

**Issue by ExsyDev** [Homebrew/homebrew-services#384]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09b7ab2c1de3ab32f385aac922b2cd644fdd7c79
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6d6a4aa9ba0d0f2688b07ea0df3d90a9a5f40f81
Core tap last commit: 77 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-arm64
CLT: 13.0.0.0.1.1630607135
Xcode: 13.0
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I try run `brew services list` for see services list.

### What happened (include all command output)?

I get error after running command brew services list:

```
Error: undefined method `chomp' for nil:NilClass
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:53:in `user_of_process'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:139:in `block in list'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:127:in `map'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:127:in `list'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:9:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:84:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

### What did you expect to happen?

I happen see my services list.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Simple run command brew services list. 

Note: If I run command with sudo: sudo brew services list, then command working. But without sudo command is not work :(. Help me please
```

**Comment by ExsyDev** [comment]
@SMillerDev there is no error now, but when I run `brew services list` my editor opening some files: https://imgur.com/a/VJC0P3i

How I can prevent this?

**Comment by SMillerDev** [comment]
It's hard to see which files your editor opened but I don't know what could be happening there. No code change in brew services tells anything to open a file.

**Comment by ExsyDev** [comment]
> It's hard to see which files your editor opened but I don't know what could be happening there. No code change in brew services tells anything to open a file.

It was before even with that error

**Comment by SMillerDev** [comment]
if you run `ps aux`, does it show a list of running processes? If not, what does `which ps` say?

**Comment by ExsyDev** [comment]
> if you run `ps aux`, does it show a list of running processes? If not, what does `which ps` say?

If I run `ps aux`, then my editor opening file `aux` and shows nothing. If I run `which ps` it says: `/usr/local/bin/ps` and does not open any files.

**Comment by SMillerDev** [comment]
Yeah, somehow your system `ps` command is being overwritten by your editor. I'll see if there is a way we can work around it, but I would recommend just removing `/usr/local/bin/ps` to get `brew services` working

**Comment by ExsyDev** [comment]
> Yeah, somehow your system `ps` command is being overwritten by your editor. I'll see if there is a way we can work around it, but I would recommend just removing `/usr/local/bin/ps` to get `brew services` working

Yep. Now working good and does not open any files when I run `brew services list`. Thanks very much!
