### ISSUE TITLE
[macOS Monterey] "brew services list" renders incorrectly for services without a PID and zero exit status in launchctl status output

### ISSUE THREAD

**Issue by jimeh** [Homebrew/homebrew-services#392]
- OS: macOS Monterey 12.0.1 (21A559)

Examples of affected formula are `dbus` and `logrotate`:

```
$ brew services list
Name           Status  User  File
caddy          started jimeh ~/Library/LaunchAgents/homebrew.mxcl.caddy.plist
dbus            jimeh
docker-machine stopped
grafana        stopped
influxdb@1     stopped
libvirt        stopped
logrotate       jimeh
mariadb        stopped
node_exporter  started jimeh ~/Library/LaunchAgents/homebrew.mxcl.node_exporter.plist
php            stopped
postgresql     stopped
prometheus     started jimeh ~/Library/LaunchAgents/homebrew.mxcl.prometheus.plist
redis          stopped
traefik        stopped
unbound        stopped
```

From what I can tell, `Service::ServicesCli.service_get_operational_status` returns nil for both of these services, causing the not correct list output above where effectively the user is printed in status column.

The reason for this seems to be because `service.pid?`, `service.error?`, and `service.unknown_status?` all return false.

Digging a bit deeper, dbus's `FormulaWrapper` object looks like this:

```
#<Service::FormulaWrapper:0x00007fc5372d35a8
 @formula=
  #<Formula dbus (stable) /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dbus.rb>,
 @name="dbus",
 @service_file=
  #<Pathname:/usr/local/opt/dbus/org.freedesktop.dbus-session.plist>,
 @service_name="org.freedesktop.dbus-session",
 @status=
  "{\n" +
  "\t\"Sockets\" = {\n" +
  "\t\t\"unix_domain_listener\" = (\n" +
  "\t\t\tfile-descriptor-object;\n" +
  "\t\t);\n" +
  "\t};\n" +
  "\t\"LimitLoadToSessionType\" = \"Aqua\";\n" +
  "\t\"Label\" = \"org.freedesktop.dbus-session\";\n" +
  "\t\"OnDemand\" = true;\n" +
  "\t\"LastExitStatus\" = 0;\n" +
  "\t\"Program\" = \"/usr/local/Cellar/dbus/1.12.20/bin/dbus-daemon\";\n" +
  "\t\"ProgramArguments\" = (\n" +
  "\t\t\"/usr/local/Cellar/dbus/1.12.20/bin/dbus-daemon\";\n" +
  "\t\t\"--nofork\";\n" +
  "\t\t\"--session\";\n" +
  "\t);\n" +
  "};">
```

Which explains why its happening, cause there is no PID, but last exit status is zero, and status is  not blank as the `unknown_status?` method checks for.

Checking the status manually through `launchctl` yields the following when the service is "started":

```
$ launchctl list org.freedesktop.dbus-session
{
        "Sockets" = {
                "unix_domain_listener" = (
                        file-descriptor-object;
                );
        };
        "LimitLoadToSessionType" = "Aqua";
        "Label" = "org.freedesktop.dbus-session";
        "OnDemand" = true;
        "LastExitStatus" = 0;
        "Program" = "/usr/local/Cellar/dbus/1.12.20/bin/dbus-daemon";
        "ProgramArguments" = (
                "/usr/local/Cellar/dbus/1.12.20/bin/dbus-daemon";
                "--nofork";
                "--session";
        );
};
```

And the following when it's stopped:

```
$ launchctl list org.freedesktop.dbus-session
Could not find service "org.freedesktop.dbus-session" in domain for port
```

I haven't dug enough to fully understand what the correct behavior is here, as I've got all of about 10 minutes of knowledge of the homebrew-services codebase right now, but I at least wanted to provide a little bit more than just "thing is broken".

**Comment by MikeMcQuaid** [comment]
@SMillerDev can you take a look at this when you get a chance? 🙇🏻

**Comment by SMillerDev** [comment]
For logrotate I'm not really sure what the status should be. It is a service that runs on a schedule so `started` or `stopped` seems weird to me.

For dbus it's an even harder case because it doesn't get installed normally by brew, instead it tells brew where to find the plist.

**Comment by jimeh** [comment]
Maybe a new status of `loaded` makes sense? As `launchctl` uses "load" and "unload" terminology.

Or, worst case, maybe treat them as `unknown` so the `brew services list` command correctly prints a status column for them. I ran into this issue when doing a rewrite of xbar's brew-services plugin ([PR](https://github.com/matryer/xbar-plugins/pull/1717)), and had to work around it by treating anything that isn't a known status value as the username, and marking such services as "unknown".

P.S. As a side-note, support JSON output from `brew services list` would be great, though I should probably open an issue for that :)

**Comment by MikeMcQuaid** [comment]
> For logrotate I'm not really sure what the status should be. It is a service that runs on a schedule so `started` or `stopped` seems weird to me.

`scheduled` or something?

> Or, worst case, maybe treat them as `unknown` so the `brew services list` command correctly prints a status column for them.

Agreed, `unknown` is always better than skipping a column.

**Comment by jimeh** [comment]
> `scheduled` or something?

I thought of `scheduled` too, but then I wasn't sure if there's any easy way to distinguish actually scheduled services from those which aren't scheduled but still "enabled".

Speaking of which, maybe `enabled` might work as well? Cause looking at the `launchctl` manpage in Monterey at least, it looks like `load`/`unload` commands are deprecated in favor of `enable`/`disable` or `bootstrap`/`bootout`.

**Comment by SMillerDev** [comment]
We can't fully copy launchd because it works on Linux too. But `scheduled` sounds good.

**Comment by apainintheneck** [comment]
I'd be happy to work on this if no one else is currently tackling it but I do have a few questions.

**Comment by jimeh** [comment]
This largely seems addressed now, with the `scheduled` status working with `logrotate` for example.

However, there's a new `none` status which seems to be the new `stopped`. Except for `dbus`, the first time I tried starting it it changed from `none` to `stopped`.

Is it safe to treat statuses `none` and `stopped` as the same thing?

**Comment by SMillerDev** [comment]
`none` means no status so it's definitely not running (this is usually the case on a fresh install/reboot)

`stopped` means it ran before but now it stopped.

If those two are interchangeable in your use case you can treat them as the same.

**Comment by jimeh** [comment]
@SMillerDev cool, thanks :)

In my case nearly everything reverts to `none` when I stop them, I'm assuming that's expected behavior.

And it does sound like `none` and `stopped` are fine to treat as the same for the purposes of my xbar script: https://github.com/jimeh/dotfiles/blob/main/xbar/brew-services.10m.rb

![screenshot](https://share.jimeh.me/Screen-Shot-2022-03-01-19-03-19.15-cbrhFgH8zm68.png)

**Comment by jimeh** [comment]
Personally I think this issue is resolved, but I'll leave this open for now in case anyone that's been involved with fixing the issue has anything left they want to tackle related to it.

**Comment by MikeMcQuaid** [comment]
Let's close if @jimeh is happy and reopen if need be.
