### ISSUE TITLE
Error: Formula `mysql` has not implemented #plist, #service or installed a locatable service file

### ISSUE THREAD

**Issue by pgrenaud** [Homebrew/homebrew-services#398]
Greetings,

I'm trying to provision a freshly installed M1 Mac mini, and I'm having this issue that I haven't seen a couple weeks ago when I did the same thing. `brew services` does not show `mysql` services, even if the `mysql` formula is installed. Just to compared, I've installed `httpd` and `php`, and both show up in `brew services`.

When running the `brew services start mysql`, I get the following message:

```
Error: Formula `mysql` has not implemented #plist, #service or installed a locatable service file
```

I feel that this issue is somewhat related to https://github.com/Homebrew/homebrew-core/issues/79367 but I didn't find any commit that would explain why this isn't working suddenly, when it was working a couple weeks ago.

Also, I checked on an Intel Mac and I didn't get this issue with the latest version of Homebrew.

**Comment by SMillerDev** [comment]
What does `ls -al /opt/homebrew/opt/mysql/` say?

**Comment by pgrenaud** [comment]
> What does `ls -al /opt/homebrew/opt/mysql/` say?

```
% ls -al /opt/homebrew/opt/mysql/
ls: /opt/homebrew/opt/mysql/: No such file or directory
```

**Comment by SMillerDev** [comment]
Did you install in rosetta mode?

**Comment by pgrenaud** [comment]
I did not know that was even possible, so I'm guessing no.

**Comment by pgrenaud** [comment]
I don't understand. Mysql was installed using `brew install mysql`. Right now, I tried to run `brew reinstall mysql` but then I got a bunch of error. Then, I ran `brew uninstall mysql` then got `Error: No available formula or cask with the name "mysql". Did you mean mysql++?`. Finally, I ran `brew install mysql` and everything seems to be fine now.

**Comment by pgrenaud** [comment]
This is so strange. Something was definitely broken, but again this is a freshly installed system. That should not happens.

@SMillerDev Do you want me to look at something before I erase this mac and try over again to see if I can reproduce?

**Comment by MikeMcQuaid** [comment]
Run `brew doctor` and fix the problems it mentions.

**Comment by pgrenaud** [comment]
> Run `brew doctor` and fix the problems it mentions.

```
% brew doctor
Your system is ready to brew.
```

@MikeMcQuaid Do you want me to look at something else before I erase this mac and try over again to see if I can reproduce?

**Comment by MikeMcQuaid** [comment]
@pgrenaud `sudo chown -R $USER /opt/homebrew`.

**Comment by pgrenaud** [comment]
According to the result of `find /opt/homebrew ! -user $USER`, no files or directories belongs to any other user.

**Comment by pgrenaud** [comment]
After erasing the mac and reinstalling macOS, I no longer observe the issue.

However, I do notice a new issue: #399
