### ISSUE TITLE
brew services restart formula no longer start the service if it is not currently running

### ISSUE THREAD

**Issue by pgrenaud** [Homebrew/homebrew-services#399]
Previously, regardless of if a service is running or not, executing the command `brew services restart formula` would start the service (after stopping it first if it is running).

Now, if the service is not currently running, executing the command `brew services restart formula` does nothing. If the service is currently running, the command `brew services restart formula` behave as expected.

I think this recent commit caused this behaviour change: https://github.com/Homebrew/homebrew-services/commit/4746bf7263ce807f77ba01214c6992c7b041c2d7

Would it be possible to restore the previous behaviour?

**Comment by convenient** [comment]
Ah this is very likely the cause of https://github.com/Homebrew/homebrew-bundle/issues/1023 maybe?

**Comment by SMillerDev** [comment]
That could be, I'm not sure that a `restart` should silently do `start` if there was nothing to stop though

**Comment by convenient** [comment]
@SMillerDev that's how it's been working previously though?

**Comment by convenient** [comment]
@SMillerDev I cant find any official documentation, this is the closest I could get which I think is the blog post I read when we were moving off of `boxen`

https://mikemcquaid.com/2016/06/15/replacing-boxen/
> I used and improved the Homebrew Bundle tool to allow each project to have a Brewfile with Homebrew packages which are shared at a system level and have background services started automatically.

This would imply `brew bundle` handles the starting of any services that are necessary IMO

**Comment by MikeMcQuaid** [comment]
> That could be, I'm not sure that a `restart` should silently do `start` if there was nothing to stop though

@SMillerDev Yeh, it should, there's a bunch of scripts out there that rely on this behaviour (including `brew bundle`) unfortunately.

**Comment by SMillerDev** [comment]
> @SMillerDev Yeh, it should, there's a bunch of scripts out there that rely on this behaviour (including brew bundle) unfortunately.

Hey, you approved it 😄. I'll make a PR later today if nobody beats me to it

**Comment by MikeMcQuaid** [comment]
> Hey, you approved it 😄.

😅. I did not review well enough it seems.



> I'll make a PR later today if nobody beats me to it

Yes, please ❤️

**Comment by pgrenaud** [comment]
#400

**Comment by pgrenaud** [comment]
Thanks all for the quick handling!
