### ISSUE TITLE
brew services broken when a newer version is available

### ISSUE THREAD

**Issue by alanivey** [Homebrew/homebrew-services#4]
Copied from https://github.com/Homebrew/homebrew/issues/27024

I was able to see this in action by installing PHP 5.5.19 a little while ago and `brew update` had an available formula for 5.5.20 that I did not install. `brew services` attempts to load the `service.plist` from `Formula.factory(@formula)` (here)[https://github.com/gapple/homebrew-services/blob/master/cmd/brew-services.rb#L126]. When this happens, the older installed version's plist_path is never shown, instead, the not-installed version's plist_path is shown.

The end result is that if you ever run `brew update` and formula that have services-managed plists are updated but you don't upgrade, `brew services` will cease to work.

I spent some time looking at this but was stuck- instead of looking at the most recent formula, which may not even be installed, can we look for the plist of the most-recently installed version on disk?

**Comment by alanthing** [comment]
Excellent, great work!
