### ISSUE TITLE
plist file not showing with `brew services` when service was started with `brew services restart`

### ISSUE THREAD

**Issue by pgrenaud** [Homebrew/homebrew-services#401]
Hi @MikeMcQuaid and @SMillerDev, it's me again with another issue 😅 

Following #399 and #400, I noticed that the file column is empty for services started with `brew services restart`.

For instance, if I start the `mysql` service with `brew services start mysql`, I get the following:

```
$ brew services
Name    Status  User    File
mysql   started exolnet ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
redis   started exolnet ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

But if I start the `mysql` service with `brew services restart mysql`, I get the following:

```
$ brew services
Name    Status  User    File
mysql   started exolnet 
redis   started exolnet ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

In both cases, the `mysql` service is started properly. The issue occur with other services as well.

The issue only seems aesthetic, but I don't who or what would be relying on that information.

**Comment by MikeMcQuaid** [comment]
@SMillerDev can you take a look at this when you get a chance? 🙇🏻

**Comment by SMillerDev** [comment]
Yeah, It's on my list.

**Comment by pgrenaud** [comment]
Everything seems to work fine now. Thanks again!
