### ISSUE TITLE
brew services - Unknown command: services

### ISSUE THREAD

**Issue by wkb1192** [Homebrew/homebrew-services#404]
`brew update` & `brew update-reset` ←Finished

`brew config`
HOMEBREW_VERSION: 3.3.5-28-g3ab140e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3ab140e39753536b7e6f8ce337f6f000e31cbb2f
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d047c7351f2b3c7283875ec613f1c41a771b0a6b
Core tap last commit: 27 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-x86_64
CLT: 13.1.0.0.1.1633545042
Xcode: 13.1

**Comment by wkb1192** [comment]
why Closed

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by wkb1192** [comment]
`brew install httpd`
↓
`sudo brew services start httpd`
↓
Error: Unknown command: services

**Comment by wkb1192** [comment]
Please Help

**Comment by MikeMcQuaid** [comment]
You need to answer my questions or we cannot help you.

**Comment by wkb1192** [comment]
[https://tech-cookbook.com/2021/10/25/how-to-setup-mamp-macos-apache-mysql-php-on-macos-12-monterey-2021/](url)
I want to do the SetUp described in this URL.

I want to run the `brew services restart httpd` written in Starting Apache server,
but when I try to run it, I get `Error: Unknown command: services`.

Why isn't this command being executed?

**Comment by wkb1192** [comment]
[https://tech-cookbook.com/2021/10/25/how-to-setup-mamp-macos-apache-mysql-php-on-macos-12-monterey-2021/](url)
I want to do the SetUp described in this URL.

I want to run the `brew services restart httpd` written in Starting Apache server,
but when I try to run it, I get `Error: Unknown command: services`.

Why isn't this command being executed?

**Comment by MikeMcQuaid** [comment]
Try to `brew tap homebrew/services`.

**Comment by wkb1192** [comment]
`brew tap homebrew/services` & `brew update` & `brew update-reset`

I've tried, but I'm still getting an error message.

**Comment by wkb1192** [comment]
I'm crying.

**Comment by MikeMcQuaid** [comment]
Can't help you then. This is an issue specific to your machine and not a bug in Homebrew. You may have more luck in our Homebrew/discussions repository.

**Comment by wkb1192** [comment]
悲しい
