### ISSUE TITLE
status error with httpd after brew install

### ISSUE THREAD

**Issue by gstlouisgit** [Homebrew/homebrew-services#415]
I have this strange error in brew services.  

Name       Status  User           File
httpd        error    256 root    ~/Library/LaunchAgents/homebrew.mxcl.httpd.plist
mariadb   started gstlouis     ~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
php@7.4  started gstlouis     ~/Library/LaunchAgents/homebrew.mxcl.php@7.4.plist

When doing `brew services start httpd` it says it start (with the error above), but it really hasn't start.  I literally have to sudo it.

`sudo /usr/local/opt/httpd/bin/httpd -k start`

Once this is done, httpd is working.  weird.  The permissions look fine and all.

mind you, I did this after doing upgrade from high sierra, to Catalina, to Monterey.  I was using mac's native apache prior and was trying to switch everything to brew.  I had a mix of php, mysql on brew and mac native httpd because brew wasn't working properly with high sierra.  At least I'm not stuck by starting it manually sudo /usr/local/opt/httpd/bin/httpd -k start

any advice to have brew working correclty?

**Comment by SMillerDev** [comment]
> any advice to have brew working correctly?

Check what the log says for httpd? Or try running `/usr/local/opt/httpd/bin/httpd -D FOREGROUND` outside of `brew services` and see what it outputs

**Comment by gstlouisgit** [comment]
thanks 
/usr/local/opt/httpd/bin/httpd -D FOREGROUND
nothing really happens, so it looks fine and is working when I exec this.  but no errors to go on...

**Comment by PrasadChinwal** [comment]
@gstlouisgit try running `launchctl list | grep homebrew.` and track `httpd`. We are looking for a pid listed besides httpd service.

<details>
  <summary>example</summary>

 ```
 -	2	homebrew.mxcl.dnsmasq
27225	0	homebrew.mxcl.nginx
28210	0	homebrew.mxcl.php
 -	0	homebrew.mxcl.redis
 -	78	homebrew.mxcl.php@8.0
 -	-6	homebrew.mxcl.httpd
99665	-15	homebrew.mxcl.mailhog
 ```
</details>

You can try running the above steps with sudo as well because sometimes the services which are started on boot using .plist files might be interfering in starting the services.

**Comment by PrasadChinwal** [comment]
@SMillerDev I think it is safe to close this issue as I believe this is not really a bug. It is related to #433.
