### ISSUE TITLE
Feature Request: Caddy

### ISSUE THREAD

**Issue by kalebheitzman** [Homebrew/homebrew-services#43]
Would it be possible to use brew services for Caddy? 

https://caddyserver.com/

**Comment by mikemcquaid** [comment]
Yep, someone just needs to open a pull request to add a `plist` to the formula. 
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
