### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/homebrew-services#459]
Since it looks like systemctl support has been added to `homebrew services` the readme should probably be updated to reflect that. At the moment, it says that it doesn't work on linux and does not mention systemctl at all. Maybe I'm misunderstanding that though.

**Comment by apainintheneck** [comment]
Oh and also it would probably be good idea to update the about thing in the sidebar to make this project easier to find. Of course, I don't have access to that though.

![Screen Shot 2022-03-03 at 11 18 09 AM](https://user-images.githubusercontent.com/42982186/156636746-77eacd08-7c54-40fa-9ca4-e1c8d793e76d.png)

^ something like this

**Comment by Rylan12** [comment]
Updated, thanks!

I also removed the `'` after macOS which I don't think is necessary anymore (per my comment in #460). Let me know if you agree
