### ISSUE TITLE
Error: Could not read the plist for `postgresql`!

### ISSUE THREAD

**Issue by OhCoder** [Homebrew/homebrew-services#46]
### System version: 
Description:	Ubuntu 14.04.3 LTS

### Linuxbrew ( here I installed Linuxbrew not the Homebrew ):
Homebrew 0.9.5 (git revision dc1c2; last commit 2016-04-15)
source code: https://github.com/Linuxbrew/linuxbrew

#### I installed Linuxbrew, and then installed the homebrew-services with the command:

`brew tap homebrew/services`

#### I installed PostgreSQL with Linuxbrew, with the `brew info postgresql` command, got the install info:
postgresql: stable 9.5.2
Object-relational database system
https://www.postgresql.org/
Conflicts with: postgres-xc
/home/snow/.linuxbrew/Cellar/postgresql/9.5.2 (3,109 files, 36.3M) *
  Built from source with: --without-perl
From: https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/postgresql.rb
==> Dependencies
Required: openssl ✔, readline ✔, libxml2 ✔, libxslt ✔, util-linux ✔
==> Options
--32-bit
	Build 32-bit only
--with-dtrace
	Build with DTrace support
--with-python
	Build with python support
--with-tcl
	Build with Tcl support
--without-perl
	Build without Perl support
==> Caveats
If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/homebrew/issues/2510

To migrate existing data from a previous major version (pre-9.0) of PostgreSQL, see:
  http://www.postgresql.org/docs/9.5/static/upgrading.html

To migrate existing data from a previous minor version (9.0-9.4) of PosgresSQL, see:
  http://www.postgresql.org/docs/9.5/static/pgupgrade.html

  You will need your previous PostgreSQL installation from brew to perform `pg_upgrade`.
  Do not run `brew cleanup postgresql` until you have performed the migration.

#### Then with `brew services list` command, it works:
Name       Status  User Plist
postgresql stopped 

#### But with `brew services start postgresql` command, it failed:
sh: 1: list: not found
Error: Could not read the plist for `postgresql`!

**Comment by mikemcquaid** [comment]
homebrew-services does not support Linux, sorry.

**Comment by unionx** [comment]
Hi, same error on Linux. Do you have any plan to support Linuxbrew?

**Comment by MikeMcQuaid** [comment]
@unionx We'd accept pull requests but almost certainly not as it's very tightly bound currently to `launchctl`.
