### ISSUE TITLE
Update line in functional tests

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/homebrew-services#469]
I was looking at the GitHub actions because my test aren't passing (but I'm sure that's unrelated) and I found this line that probably should be updated. It's in the functional tests section and is [line 112](https://github.com/Homebrew/homebrew-services/blob/3fbd50aef0d70b690ffbc8488bb3f2210f13719b/.github/workflows/tests.yml#L112).

`if launchctl list | grep redis; then false; else true; fi`

It probably should be something like this so that it works with systemctl too.

`if brew services list | grep redis; then false; else true; fi`

**Comment by MikeMcQuaid** [comment]
Yes, good find! Could you submit a PR?

**Comment by apainintheneck** [comment]
Yeah, sure. I don't why but I thought you had to be a part of a organization to change the workflows. Otherwise I would have just done it. I'll submit a PR.

**Comment by apainintheneck** [comment]
It looks like it's a bit more complicated than just changing one line.

I wanted to just run `brew services list | grep 'redis *none'` because that should be the status when a service has been unloaded but that only worked on MacOS.

My hunch is that maybe the FormulaWrapper#loaded? command behaves differently depending on the operating system but I have nothing to back that up. It might also be related to the fact that ServicesCli#stop doesn't remove the service file on Linux like it does on MacOS.

I'll look into it a little more.
