### ISSUE TITLE
Using custom service files

### ISSUE THREAD

**Issue by apainintheneck** [Homebrew/homebrew-services#472]
Looking at the code I'm kind of confused by the support for custom service files. The help page says the following:
```--file    Use the plist file from this location to start or run the service.```

command | macOS | linux
:------------ | :-------------| :-------------
run | :x: |  :x:
start | :white_check_mark: |  :white_check_mark:
restart | ✔️ | ✔️

It seems like custom service files only work with the start command. The restart command still accepts the service file as a parameter but doesn't do anything with it (I assume there was support for that in the past and it was maybe dropped for some reason).

Another thing is that the usage of the --all option seems to clobber the --file option without giving any warning to the user.

Beyond that the restart command works by essentially calling the stop and start/run commands internally. This means that if someone had installed a custom service file it would get deleted and replaced by the default generated service file from the formula which might not be ideal.

These are all admittedly small, nitpicky sorts of things but I thought I'd at least mention them since I'd picked up on them while looking around the repo.

I see a few different options.
1. Do nothing. These are not widely used features and nobody's complaining.
2. Keep current functionality but update the readme/docs and give additional warnings to users when they try to do things that aren't allowed. Also, remove the service file parameter from the restart.run() method.
3. Add additional support for custom service files to one or both platforms.

I'm partial to option 2.

Edit: It looks like the start command allows custom service files to be installed on both platforms. Not sure why I missed that before.

**Comment by SMillerDev** [comment]
I'm fine with 2. I remember that my initial Linux support broke this option since I didn't notice it existed, but that did trigger some complaints so removing everything might not be a solution either.

I'd suggest to keep the file in the run/restart function signature for now and give a warning there that it's unsupported.

**Comment by MikeMcQuaid** [comment]
2. sounds good to me too!
