### ISSUE TITLE
"Brew services cannot run under tmux" error is misinformative

### ISSUE THREAD

**Issue by molovo** [Homebrew/homebrew-services#49]
This error message was added in commit 68c176a9.

`brew services` *can* run under tmux, provided [reattach-to-user-namespace](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard) is run.

Ideally we should either check for an attached namespace, and instruct the user to install the `reattach-to-user-namespace` formula if it's not, rather than just exiting the script.

When attached to the namespace `brew services` commands work absolutely fine under tmux (I've been using them this way for > 6 months), so we should not disable this working functionality.

Happy to try and submit a pull request myself if no one else is interested.

**Comment by mikemcquaid** [comment]
> Happy to try and submit a pull request myself if no one else is interested.

Please, that would be great. I was aware of this but had no idea how to detect it and figured someone like yourself who actually uses `tmux` would have a better idea 👍

**Comment by molovo** [comment]
I'll take a look, see what I can do

**Comment by UniqMartin** [comment]
@molovo Please have a look at #48. That's something that is being addressed in the linked PR, but hasn't been merged yet (though it seems to be ready by now).

I think you can help by testing the change and reporting back in the mentioned PR.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-services/commit/55156b7c260f9468f03d4ea8a4735bf3abed32b4
