### ISSUE TITLE
Linux (debian): requires dbus-session-bus or should retain XDG_RUNTIME_DIR for systemctl --user to function

### ISSUE THREAD

**Issue by mjpieters** [Homebrew/homebrew-services#496]
I'm using linuxbrew on Debian 10, which has systemd with `--user` support. However, none of the `brew services` commands actually work.

I tracked this down to the `XDG_RUNTIME_DIR` variable not being set; `/home/linuxbrew/.linuxbrew/Homebrew/bin/brew` has a whitelist of environment variables it keeps (unless the deprecated `HOMEBREW_NO_ENV_FILTERING` env var is set), and this list doesn't include `XDG_RUNTIME_DIR`.

The variable is crucial however, omitting it causes `systemctl --user` commands to fail:

```sh
$ env -u XDG_RUNTIME_DIR /bin/systemctl --user status
Failed to connect to bus: No such file or directory
$ /bin/systemctl --user status
● <hostname>
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Tue 2022-08-02 19:30:48 BST; 21h ago
   CGroup: /user.slice/user-<uid>.slice/user@<uid>.service
           └─init.scope
             ├─<pid> /lib/systemd/systemd --user
             └─<pid> (sd-pam)
```

(I replaced some elements with `<...>` placeholders for security reasons).

I can get `brew services` commands to work by editing the `.../bin/brew` command and adding `XDG_RUNTIME_DIR` to the whitelist. Perhaps this is something that should be made permanent?

I reported this _here_ because this issue affects the `brew services` commands only, but perhaps should be reported in the certral core repo instead.

**Comment by mjpieters** [comment]
I see that the codebase does try to preserve `DBUS_SESSION_BUS_ADDRESS`, but this is not a variable that is set on my system:

```sh
env | grep DBUS
```

nor does setting it to the common value `/run/user/$UID/bus` make `systemctl --user` work:

```sh
$ env -u XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS=/run/user/$UID/bus /bin/systemctl --user status
Failed to connect to bus: Connection refused
```

There is no `bus` entry in my `$XDG_RUNTIME_DIR` directory, only a `systemd` directory with `notify` and `private` sockets. From `strace systemctl --user status` it appears that `$XDG_RUNTIME_DIR/systemd/private` is used to communicate with the central `systemd` daemon, not D-Bus, even though that is installed on my system.

**Comment by mjpieters** [comment]
I found [`dbus-user-session`](https://packages.debian.org/buster/dbus-user-session), which gives me a dbus service on my headless system, and new sessions now have a `DBUS_SESSION_BUS_ADDRESS` env var, which is used instead of `$XDG_RUNTIME_DIR/systemd/private`.

Perhaps this (or rather,  the [virtual `dbus-session-bus` package](https://packages.debian.org/buster/dbus-session-bus) is a minimal requirement for `brew services`?

**Comment by MikeMcQuaid** [comment]
> Perhaps this (or rather, one of the virtual [`dbus-session-bus`](https://packages.debian.org/buster/dbus-session-bus) or [`default-dbus-session-bus`](https://packages.debian.org/buster/default-dbus-session-bus) packages) is a minimal requirement for `brew services`?

Yes, this seems like a good addition to the `brew services` code to error out in your circumstance better with a message suggesting installing these packages.

Alternatively, I would be fine with `XDG_RUNTIME_DIR` being passed through in the same way `DBUS_SESSION_BUS_ADDRESS` is, if you'd be open to creating a Homebrew/brew and Homebrew/homebrew-services PR to handle that, @mjpieters?

**Comment by mjpieters** [comment]
I'll see if I can find some time.

SIde note: under tmux, `systemctl --user` relies on `XDG_RUNTIME_DIR`, so making sure `XDG_RUNTIME_DIR` is passed through under homebrew also would let you drop the warning about things not working under tmux.
