### ISSUE TITLE
Services won't start or stop since 9b36e033eba6bc8fa2f42646a73125321edd656c

### ISSUE THREAD

**Issue by kvndrsslr** [Homebrew/homebrew-services#499]
Commit 9b36e033eba6bc8fa2f42646a73125321edd656c has broken services for me.
I can not start a stopped service anymore.

```sh
% brew services start yabai
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap user/501 /Users/kvn/Library/LaunchAgents/homebrew.mxcl.yabai.plist` exited with 5.
```

If I start a service and reboot, the service is running but I can't stop it in the same login session.

I have tried the following services on a completely fresh macOS 12.5 installation:

- https://github.com/koekeishiya/homebrew-formulae/blob/master/yabai.rb
- https://github.com/kvndrsslr/homebrew-formulae/blob/main/brync.rb
- https://github.com/FelixKratz/homebrew-formulae/blob/master/sketchybar.rb

all of them are throwing the same error as indicated above.

Using a commit prior to 9b36e033eba6bc8fa2f42646a73125321edd656c fixes the problem.

**Comment by MikeMcQuaid** [comment]
reverted in https://github.com/Homebrew/homebrew-services/pull/498
