### ISSUE TITLE
 `brew services` shows Status `none` in stop mode, and 'stopped' when started

### ISSUE THREAD

**Issue by shemeshg** [Homebrew/homebrew-services#511]
# brew version
```
osx@osxs-Mac-mini ~ % brew -v
Homebrew 3.6.5-2-ge89ae3c
Homebrew/homebrew-core (git revision e2b8fd0d599; last commit 2022-10-10)
Homebrew/homebrew-cask (git revision a771466c1d; last commit 2022-10-10)
osx@osxs-Mac-mini ~ %
```

# None when stoped
```
osx@osxs-Mac-mini ~ % brew services
Name    Status User File
dbus    none
unbound none
osx@osxs-Mac-mini ~ % brew services start dbus
==> Successfully started `dbus` (label: org.freedesktop.dbus-session)
osx@osxs-Mac-mini ~ % brew services stop dbus
Stopping `dbus`... (might take a while)
==> Successfully stopped `dbus` (label: org.freedesktop.dbus-session)
osx@osxs-Mac-mini ~ % brew services
Name    Status User File
dbus    none
unbound none
```

# start presented as `stopped`
```
osx@osxs-Mac-mini ~ % brew services start dbus
==> Successfully started `dbus` (label: org.freedesktop.dbus-session)
osx@osxs-Mac-mini ~ % brew services
Name    Status  User File
dbus    stopped osx  ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
unbound none
osx@osxs-Mac-mini ~ % brew services
Name    Status  User File
dbus    stopped osx  ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
unbound none
osx@osxs-Mac-mini ~ % brew services stop dbus
Stopping `dbus`... (might take a while)
==> Successfully stopped `dbus` (label: org.freedesktop.dbus-session)
osx@osxs-Mac-mini ~ % brew services
Name    Status User File
dbus    none
unbound none
osx@osxs-Mac-mini ~ %
```

# Probably because when started it is 
```
osx@osxs-Mac-mini ~ % launchctl list | grep dbus
-	0	org.freedesktop.dbus-session
```
it is not owned by `homebrew` itself.

## Probably the indication for running or not should be existence of it line in the `launchctl list`
and not filtered by process owner.

**Comment by MikeMcQuaid** [comment]
I don't understand what the supposed bug is here?

To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by shemeshg** [comment]
# What you were trying to do (and why)
Get the `list` status of my services correctly.

### Now it is presented when stoped 
|Name    |Status |User| File|
|--------|-------|-----|-----|
|dbus    |none|
|unbound |none|

### However it should have presented when stoped
|Name    |Status |User| File|
|--------|-------|----|------|
|dbus    |**stoped**|
|unbound |**stoped**|

### Now it is presented when **started** 
|Name    |Status |User| File|
|--------|-------|-----|-----|
|dbus    | stopped| osx|  ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
|unbound |none|

### However it should have presented
|Name    |Status |User| File|
|--------|-------|-----|-----|
|dbus    | started| osx|  ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
|unbound |none|

# What happened

- It present `none` for stopped services
- It present `stopped` for started services

# What you expected to happen
- for stoped service to display status 'stopped'
- for stoped service to display status 'started'

# Step-by-step reproduction instructions (with as minimal input data as possible)

* Stopped services presented as `none`
```
% brew services stop dbus
% brew services
Name    Status User File
dbus    none
unbound none
```

* started service presented as stopped
```
% brew services start dbus
% brew services
Name    Status  User File
dbus    stopped osx  ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
unbound none
```

**Comment by SMillerDev** [comment]
Is it also broken for services that aren't dbus or unbound? Because both of those are non-standard.

**Comment by shemeshg** [comment]
I don't know, I only use dbus, and not very often for development.
But, I am sure it used to work before, since I wrote UI based on that, and these where my test cases

https://github.com/shemeshg/cakebrewjs/blob/336d3eaa7dd2ac38312fe6b65affb7ab2f6945bd/src/components/Home.vue#L219

**Comment by SMillerDev** [comment]
Yes, until about year ago stopped was the state if Homebrew didn't know what the state was. Now it correctly reflects the unknown or missing state.

**Comment by shemeshg** [comment]
- It sounds reasonable argument for the `stopped` state to be presented as 'unknown',
- however  presenting `stopped` where it is started is probably bug.

especially when it can be probed using
```
% launchctl list | grep dbus
-	0	org.freedesktop.dbus-session
```

**Comment by SMillerDev** [comment]
It's not started, the first item is the PID so it's not running.

**Comment by shemeshg** [comment]
I understand now.
So it IS actually correct.

Thanks,
