### ISSUE TITLE
macOS Ventura : login item notifications

### ISSUE THREAD

**Issue by yd021976** [Homebrew/homebrew-services#519]
Since macOs ventura, each time I launch brew services (redis, mysql etc.), I get some annoying macOS notifications that said "background items have been added".
I think the reason is that since Ventura apps should implement the [SMAppService](https://developer.apple.com/documentation/servicemanagement)

Is there any homebrew-services update to solve this issue ?

**Comment by SMillerDev** [comment]
There is no update to implement this, and since Homebrew is not an app I don't think there ever will be.
