### ISSUE TITLE
Services are still started with gui/501 instead of user/501

### ISSUE THREAD

**Issue by rgaufman** [Homebrew/homebrew-services#527]
I can see in this pull request that services are meant to start with user/501 now? < https://github.com/Homebrew/homebrew-services/pull/485

However for some reason this isn't working? - How can I get homebrew-services to use user/501 please?

```
$  brew services start memcached
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Volumes/Data/home/hackeron/Library/LaunchAgents/homebrew.mxcl.memcached.plist` exited with 5.
```

**Comment by SMillerDev** [comment]
That was reverted since it broke service usage for people who did have a gui.

**Comment by rgaufman** [comment]
Oh, I need it to use user/501 - how would I achieve this?

**Comment by SMillerDev** [comment]
> Oh, maybe it would be useful to have an optional --user param for those of us that need user/501 instead of gui/501?


If you're willing to make a pull request for this I'm fine reviewing and trying this solution.
