### ISSUE TITLE
Services are not starting for user (gui/501)

### ISSUE THREAD

**Issue by rgaufman** [Homebrew/homebrew-services#528]
<!DOCTYPE html>

package | version
-- | --
macos | 13.1
Homebrew | 3.6.16
launchctl | 7.0.0
Hardware | Mac Mini M1 2020

For example:

```
$ brew services start memcached
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Volumes/Data/home/hackeron/Library/LaunchAgents/homebrew.mxcl.memcached.plist` exited with 5.
```

This happens with every single service in ~/Library/LaunchAgents/

I am logged into the GUI:

```
$ whoami
hackeron
$ echo $UID
501
$ launchctl managername
Aqua
```

The services start fine when using user/501 (I made sure to stop the service after testing this) e.g.

```
$ /bin/launchctl bootstrap user/501 /Volumes/Data/home/hackeron/Library/LaunchAgents/homebrew.mxcl.memcached.plist
$ echo $?
0
$ ps aux | grep -i memcache
hackeron          8490   0.0  0.0 409047136   3504   ??  S     1:13pm   0:00.01 /opt/homebrew/opt/memcached/bin/memcached -l localhost
```

The permissions on the services are correct:

```
$ ls -ltra /Volumes/Data/home/hackeron/Library/LaunchAgents/
-rw-r--r--@  1 hackeron  staff   994 17 Nov 20:56 homebrew.mxcl.mongodb-community@5.0.plist
-rw-r--r--@  1 hackeron  staff   743 22 Dec 20:01 homebrew.mxcl.mosquitto.plist
-rw-r--r--@  1 hackeron  staff   929 22 Dec 20:03 homebrew.mxcl.postgresql@14.plist
-rw-r--r--@  1 hackeron  staff   986 22 Dec 20:03 homebrew.mxcl.mongodb-community.plist
-rw-r--r--@  1 hackeron  staff   880 23 Dec 12:05 homebrew.mxcl.redis.plist
-rw-r--r--@  1 hackeron  staff   726 23 Dec 13:11 homebrew.mxcl.memcached.plist
```

However running with sudo complains about permissions for some reason:

```
$ sudo /bin/launchctl bootstrap gui/501 /Volumes/Data/home/hackeron/Library/LaunchAgents/homebrew.mxcl.memcached.plist
/Volumes/Data/home/hackeron/Library/LaunchAgents/homebrew.mxcl.memcached.plist: Path had bad ownership/permissions
Bootstrap failed: 122: Path had bad ownership/permissions
```

Any solution or workaround for this please?

**Comment by SMillerDev** [comment]
This doesn't look like a bug in services since none of the failing commands are from brew.

**Comment by rgaufman** [comment]
Forgive my ignorance, where is the bug originating?

**Comment by SMillerDev** [comment]
launchctl is a macOS component, it wasn't made by brew.

**Comment by rgaufman** [comment]
I see, I'll try Apple support but I have a feeling they are not nearly as responsive/helpful😆

In any case, thank you for your responses. I'll send a pull request for the ```--user``` parameter as that seems to be something quite useful in general. Often times, I want services to start at boot but some refuse to start as root so ```sudo brew services``` doesn't always work.
