### ISSUE TITLE
their error when brew services not work

### ISSUE THREAD

**Issue by aaront2000** [Homebrew/homebrew-services#541]
their's error message describe as follows:
❯ brew services
Error: undefined method `launchd_service_path' for #<Formulary::FormulaNamespacee3371ddaef5996683274db63ce61faa5::PkgConfig:0x0000000152208138>
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:58:in `service_file'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:92:in `plist?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:12:in `select'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:12:in `available_services'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `services_list'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:102:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'

i del brew services and reinstall, it's still not work.

❯ brew config
HOMEBREW_VERSION: 3.6.5
ORIGIN: https://mirrors.ustc.edu.cn/homebrew-cask.git
HEAD: fb52a12144e80118c112ea744ab65ab6ca997d67
Last commit: 4 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 92eb2057d427e3409efbd37d8d08c72f07d417dc
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false

the OS is Apple M1 Pro, macOS Monterey 12.5

**Comment by SMillerDev** [comment]
Last commit: 4 months ago

That's your problem, you need to update your Homebrew

**Comment by aaront2000** [comment]
thanks, this time, the upgrade of brew is OK.
