### ISSUE TITLE
`restart_delay` on MacOS doesn't appear to do anything

### ISSUE THREAD

**Issue by notenti** [Homebrew/homebrew-services#543]
I was whipping up a simple service today that I wanted to self-restart in the event of a crash:

```ruby
service do
    run ['run', 'these', 'things']
    keep_alive true
end
```

I was hoping to add a small delay between the crash and the restart attempt to prevent the service from spiraling should something unexpected happen. Based on the [service block methods documentation](https://docs.brew.sh/Formula-Cookbook#service-block-methods), I figured that adding a `restart_delay` would do just that:

```ruby
service do
    run ['run', 'these', 'things']
    keep_alive true
    restart_delay 5
end
```

I tested my service a few times and noticed that it seemed to be re-instantiating the service immediately after I killed it. Odd. I also tried restarting the service manually: `brew services restart <service_name>` in case I was misunderstanding the `restart_delay` keyword. Didn't seem to have any effect.

Turns out that on MacOS, the `restart_delay` value is fed to `launchd.plist`'s `TimeOut`, which we can see [here](https://github.com/Homebrew/brew/blob/10845a1122b916dc91d04f00a4d8b7b888d52654/Library/Homebrew/service.rb#L379). Checking out the `man page` for `launchd.plist`, we find this nugget:

```
TimeOut <integer>
     The recommended idle time out (in seconds) to pass to the job. This key
     never did anything interesting and is no longer implemented. Jobs seeking
     to exit when idle should use the EnablePressuredExit key to opt into the
     system mechanism for reclaiming killable jobs under memory pressure.
```

So it looks like `TimeOut` just doesn't do anything anymore, hence why `restart_delay` doesn't appear to do anything either. 

On Linux, however, it looks like the `systemd` value that `brew` [uses](https://github.com/Homebrew/brew/blob/10845a1122b916dc91d04f00a4d8b7b888d52654/Library/Homebrew/service.rb#L448) (`RestartSec`) _does_ do what `restart_delay` claims to do:

```
RestartSec=: If automatically restarting the service is enabled, this specifies the amount of time to wait before attempting to restart the service.
```

**Comment by SMillerDev** [comment]
Is there an equivalent key on macOS?

**Comment by notenti** [comment]
Doesn't look like it. `ThrottleInterval` is the closest: 

```
This key lets one override the default throttling policy imposed on jobs
by launchd.  The value is in seconds, and by default, jobs will not be
spawned more than once every 10 seconds.  The principle behind this is
that jobs should linger around just in case they are needed again in the
near future. This not only reduces the latency of responses, but it
encourages developers to amortize the cost of program invocation.
```

but I think that's to prevent programs from restarting too often --not to mandate a delay on restart.

**Comment by SMillerDev** [comment]
As far as I can tell there is nothing we can do then.

**Comment by notenti** [comment]
Yeah, that's fine. Maybe the docs could be updated? Just to save some Mac users the headache.

**Comment by MikeMcQuaid** [comment]
Happy to review a PR to the docs but closing this as WONTFIX for now.
