### ISSUE TITLE
Starting a service with sudo does allow it to run on user login

### ISSUE THREAD

**Issue by iloveitaly** [Homebrew/homebrew-services#554]
👋 Thanks for all of the amazing work on this project!

I'm using [this service definition](https://github.com/iloveitaly/homebrew-tap/blob/main/Formula/hyper-focus.rb) and running it as root using:

```shell
sudo brew service start hyper-focus
```

When I run this command I get the following output:

```
Warning: hyper-focus must be run as non-root to start at user login!
```

However, when the computer restarts, the process _does_ run as root automatically! This is actually exactly what I want. It looks like when run as `sudo` homebrew creates a `/Library/LaunchDaemons/homebrew.mxcl.hyper-focus.plist` which starts the process at login, as root, automatically.

Should this message be removed? I can submit a PR for it, but I imagine it's there for good reason.

**Comment by SMillerDev** [comment]
If you run it as root it runs on device startup. Without root it runs on user login. The difference is negligible unless you have a multi-user device.

**Comment by iloveitaly** [comment]
@SMillerDev Ah, makes sense. Maybe adjusting the error message to indicate it will run on device startup is a good idea? Could I submit a PR for that?

**Comment by SMillerDev** [comment]
I'll happily review a PR to clarify the wording
