### ISSUE TITLE
Unable to start services - "The UserName key is not supported for non-System services."

### ISSUE THREAD

**Issue by daFish** [Homebrew/homebrew-services#56]
Since upgrading to OS X 10.11.5 I can no longer start services like httpd22.

`brew services start httpd22` results in `==> Successfully started ``httpd22`` (label: homebrew.mxcl.httpd22)` which is perfectly fine.

However, when inspecting the logs using `syslog -k Sender com.apple.xpc.launchd` I noticed the following entries:
```bash
May 27 09:48:22 name com.apple.xpc.launchd[1] (homebrew.mxcl.httpd22) <Error>: The UserName key is not supported for non-System services.
May 27 09:48:22 name com.apple.xpc.launchd[1] (homebrew.mxcl.httpd22[22553]) <Warning>: Service exited with abnormal code: 1
```

The `.plist`-file contains the section in question which was perfectly fine prior the update. Anyone experienced anything like that before?

**Comment by MikeMcQuaid** [comment]
I'm also on 10.11.5 and am not able to reproduce this. The `UserName` stuff should be cleaned up at some point but it's not what's causing this error. What happens if you run `httpd22` manually? Smells like it could be a local configuration issue.

**Comment by daFish** [comment]
Running it manually works. This gets weirder and weirder.

**Comment by MikeMcQuaid** [comment]
@daFish I'm afraid this doesn't look like a Homebrew issue. If you can figure out a fix and create a PR then we'll consider it. Sorry!

**Comment by daFish** [comment]
Thanks, @MikeMcQuaid. I try to come up with a solution. However, I have the exact same issue on another machine running 10.11.5.

**Comment by MikeMcQuaid** [comment]
@daFish Try to remove the `UserName` key and then `brew reinstall`.

**Comment by daFish** [comment]
@MikeMcQuaid Still doesn't work. The `UserName` key is always readded when starting the service.

**Comment by daFish** [comment]
Starting the service with `sudo` works as expected.

**Comment by MikeMcQuaid** [comment]
@daFish You may also want to try and remove the relevant `UserName` code from `brew services` and see if that fixes it.

**Comment by MikeMcQuaid** [comment]
also CC @ilovezfs for thoughts.

**Comment by ilovezfs** [comment]
Perhaps they got stricter and made the incorrect usage an error instead of just ignoring it.

As a workaround, @daFish can you try opening brew-services.rb, and changing
```
    # Force fix UserName
    if !ServicesCli.root?
      if data =~ %r{<key>UserName</key>}
        # Replace existing UserName value with current user
        data = data.gsub(%r{(<key>UserName</key>\s*<string>)[^<]*(</string>)}, '\1' + ServicesCli.user + '\2')
      else
        # Add UserName key and value to end of plist if it doesn't already exist
        data = data.gsub(%r{(\s*</dict>\s*</plist>)}, "\n    <key>UserName</key>\n    <string>" + ServicesCli.user + "</string>\\1")
      end
    elsif data =~ %r{<key>UserName</key>}
      # Always remove UserName key entirely if running as root
      data = data.gsub(%r{(<key>UserName</key>\s*<string>)[^<]*(</string>)}, "")
    end
```
to
```
    if data =~ %r{<key>UserName</key>}
      data = data.gsub(%r{(<key>UserName</key>\s*<string>)[^<]*(</string>)}, "")
    end
```

**Comment by daFish** [comment]
@ilovezfs This worked and I was able to start the services without any problems.

**Comment by ilovezfs** [comment]
Cool. You may want to commit that change for now, since brew update will try to stash it otherwise. 

```
cd /usr/local/Library/Taps/homebrew/homebrew-services
git add cmd/brew-services.rb
git commit -m "username go away please"
```

**Comment by MikeMcQuaid** [comment]
@ilovezfs Thanks! Would you or @daFish mind making a PR for that?

**Comment by ilovezfs** [comment]
@MikeMcQuaid Sure. Let's go with that as a workaround, clean up the formulae, and then drop the section entirely.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Sounds good.

**Comment by daFish** [comment]
@MikeMcQuaid Done.
