### ISSUE TITLE
when I run `brew services`, it returned 'Error: Unknown command: services'

### ISSUE THREAD

**Issue by drooop** [Homebrew/homebrew-services#581]
brew update
brew upgrade
brew install/uninstall
works fine, but when it comes to `brew services` it failed,it says: `Error: Unknown command: services`
I tried `brew doctor`, it shows a warning, something like broken symlink on homebrew-services(forgot to take the screenshot), it suggest me to run `brew cleanup`

after that `brew doctor` shows no warning, but `brew services` still report `Error: Unknown command: services`

**Comment by SMillerDev** [comment]
What does `brew tap` say?

**Comment by drooop** [comment]
> brew tap

brew tap
cockroachdb/tap
homebrew/services

**Comment by SMillerDev** [comment]
And what is the output of `brew config` and `brew doctor`?

**Comment by drooop** [comment]
> And what is the output of `brew config` and `brew doctor`?

`brew config:`
```sh
HOMEBREW_VERSION: 4.1.5-45-g1b2294e
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1b2294e3b63346143b219c5d3a6780f65ac9ee80
Last commit: 11 hours ago
Core tap JSON: 17 Aug 06:29 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

`brew doctor:`
```sh
<return pages of *.h filenames>
no error and no warnings
```

**Comment by SMillerDev** [comment]
Can you post the actual output of `brew doctor`? I wouldn't ask for it if I didn't think it would help me.

**Comment by drooop** [comment]
> Can you post the actual output of `brew doctor`? I wouldn't ask for it if I didn't think it would help me.

list too long, I move them to: https://bob3y2gxxp.feishu.cn/docx/QvrhdLr6roJtPMxROBucm8zknif?from=from_copylink
It shows:
```sh
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/cppgc/common.h
  /usr/local/include/node/js_native_api.h
  /usr/local/include/node/js_native_api_types.h
...
...
...(about 2k lines)
```
