### ISSUE TITLE
Error: /usr/local/var/homebrew/linked/telnet is not inside a keg

### ISSUE THREAD

**Issue by summerxue1992** [Homebrew/homebrew-services#585]
when i tried : 

 
```shell
brew install telnet
``` 
I got this:
 Warning: your HOMEBREW_PREFIX is set to /usr/local but HOMEBREW_CELLAR is set
to /usr/local/Homebrew/Cellar. Your current HOMEBREW_CELLAR location will stop
you being able to use all the binary packages (bottles) Homebrew provides. We
recommend you move your HOMEBREW_CELLAR to /usr/local/Cellar which will get you
access to all bottles."
Error: /usr/local/var/homebrew/linked/telnet is not inside a keg

**Comment by summerxue1992** [comment]
then i tried :  export HOMEBREW_PREFIX=/usr/local/Homebrew

still got : 

Warning: your HOMEBREW_PREFIX is set to /usr/local but HOMEBREW_CELLAR is set
to /usr/local/Homebrew/Cellar. Your current HOMEBREW_CELLAR location will stop
you being able to use all the binary packages (bottles) Homebrew provides. We
recommend you move your HOMEBREW_CELLAR to /usr/local/Cellar which will get you
access to all bottles."

**Comment by MikeMcQuaid** [comment]
Uninstall and reinstall Homebrew. Use `brew bundle dump` and `brew bundle` to export/import packages if needed.
