### ISSUE TITLE
Services stop running after I logout system.

### ISSUE THREAD

**Issue by hel1o-wor1d** [Homebrew/homebrew-services#592]
I buy a cheap vps and install linuxbrew in it.
But I find that when I logout the ssh, my homebrew service like nginx stop running.

I test this in my mac, the same result, when I logout my mac, I cannot visit the nginx website from my mobile phone.

How to make the homebrew services keep running even after logout the system?

**Comment by SMillerDev** [comment]
Read the manpages for `brew services`. They specify that `brew service start` will start out as your user (so it won't work when that user is logged out). And `sudo brew service start` will start system wide
