### ISSUE TITLE
`sudo brew services` is broken in linux 

### ISSUE THREAD

**Issue by hel1o-wor1d** [Homebrew/homebrew-services#594]
debian@myvps01:/home/linuxbrew/.linuxbrew$ sudo brew services list
sudo: brew: command not found
debian@myvps01:/home/linuxbrew/.linuxbrew$ sudo brew services start xray
sudo: brew: command not found
debian@myvps01:/home/linuxbrew/.linuxbrew$ sudo -i
root@myvps01:~# brew services list
Error: Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.
root@myvps01:~# brew services start xray
Error: Need to download https://formulae.brew.sh/api/formula.jws.json but cannot as root! Run `brew update` without `sudo` first then try again.
root@myvps01:~#

**Comment by SMillerDev** [comment]
None of that is indicative of Linux, it's your shell configuration on Linux that is broken.
