### ISSUE TITLE
Add information about logs to help: `brew services --help`

### ISSUE THREAD

**Issue by nhooey** [Homebrew/homebrew-services#597]
It would really help if Homebrew Services displayed information in its help text about where the logs should be.

There's nothing documented currently:
```
(brew services --help && echo 'Any mention of log or logs?') | egrep '\blogs?\b'
Any mention of log or logs?
```

**Comment by SMillerDev** [comment]
`brew services` doesn't have any logs, I'm not sure what you expect this would display.

**Comment by nhooey** [comment]
@SMillerDev: Maybe that information in itself, that Brew Services doesn't have logs of its own (why not, by the way?), and information to point the user in the right direction to find the logs of the specific service.

**Comment by SMillerDev** [comment]
> Maybe that information in itself, that Brew Services doesn't have logs of its own (why not, by the way?)

What would it log? All the interactions happen where the user can see them in the console.

> and information to point the user in the right direction to find the logs of the specific service.

That's going to be a long list of possible things to check.

**Comment by MikeMcQuaid** [comment]
Thanks for the issue @nhooey! Gentle request for future: please don't open two issues in quick succession about the same (or extremely similar) issues, thanks ❤️ 

> Maybe that information in itself, that Brew Services doesn't have logs of its own

I don't think this is worth documenting, you're the first person I've seen to have this confusion. If we see more confusion over time: we'll consider documenting this. I think it's a safe assumption for most Homebrew (and Unix) commands that if logs are not mentioned: there are none.

> why not, by the way?

`brew services` is a fairly thin wrapper around existing tools (that are both mentioned, including links to their manages, in the `--help` output). These tools have radically different approaches and logging, as @SMillerDev mentioned above, varies greatly from service to service and is essentially so customisable to not be useful.
