### ISSUE TITLE
`brew services start` reports success without checking return code

### ISSUE THREAD

**Issue by samv** [Homebrew/homebrew-services#61]
I've noticed that if you start a service and that service fails, that `brew services` does not report this.  This is confusing to users who think that it has succeeded.

The status appears to be available via `launchctl list`:

```
$ launchctl list | grep home
805	0	homebrew.mxcl.elasticsearch
810	0	homebrew.mxcl.kibana
817	0	homebrew.mxcl.kafka
824	0	homebrew.mxcl.zookeeper
-	78	homebrew.mxcl.postgresql
807	0	homebrew.mxcl.redis
```

Here, postgres has failed to start, but this is not reported.

**Comment by MikeMcQuaid** [comment]
We can't do anything about this as it's a limitation of `launchctl` which `brew services` calls out too.

**Comment by jwgoh** [comment]
Hah, I faced the same problem too!

I am interested to know why _"it's a limitation of `launchctl` which brew services calls out to"_. I am not familiar with the codebase but will give it a go. Any guidance to help me understand is much appreciated. 

Thanks for the amazing project btw 😄

**Comment by samv** [comment]
At the very least, the message could read something like "Requested to start X" instead of the confidently stated "started X".

**Comment by MikeMcQuaid** [comment]
> I am interested to know why "it's a limitation of launchctl which brew services calls out to". I am not familiar with the codebase but will give it a go. Any guidance to help me understand is much appreciated.

Unfortunately this can't be fixed; it's a limitation of `launchctl` rather than `brew services`.

**Comment by MikeMcQuaid** [comment]
@samv While I agree at this point, unfortunately, it would likely break a lot of scripts that rely on the output being as-is.
