### ISSUE TITLE
Error brew services command

### ISSUE THREAD

**Issue by tobidsn** [Homebrew/homebrew-services#635]
brew config

`HOMEBREW_VERSION: 4.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 12c8778af976269344f3c0b914243e178fc4ffbd
Last commit: 6 months ago
Core tap JSON: 15 Mar 01:37 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: false`

brew services

`Error: /opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:171: syntax error, unexpected ','
        name:,
             ^
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:174: syntax error, unexpected ',', expecting end
...d:       loaded?(cached: true),
...                              ^
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:180: syntax error, unexpected ',', expecting end
...present? ? dest : service_file,
...                              ^
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service.rb:5:in `require'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service.rb:5:in `<top (required)>'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:63:in `require_relative'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:63:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'`

**Comment by SMillerDev** [comment]
> HOMEBREW_VERSION: 4.1.10
> ORIGIN: https://github.com/Homebrew/brew 
> HEAD: 12c8778af976269344f3c0b914243e178fc4ffbd Last commit: 6 months ago

That's a long time behind on new releases. Try running `brew update-reset`, it'll clear all changes to brew repositories and reset them fresh.
