### ISSUE TITLE
Make require_root option not to require existence of run

### ISSUE THREAD

**Issue by Jerry1144** [Homebrew/homebrew-services#636]
I find name+require_root perfect in "tool provides a system Daemon, and a ready-made plist to be put into /Library/LaunchDaemons" [scenario](https://github.com/Homebrew/homebrew-core/pull/166340). Like this service do:
```
service do
  name macos: "cc.chlc.batt"
  require_root true
end
```
It makes brew output the right command to run in the Caveats section, without the "or if you want to run it once, run [the run command]" latter half. 
```
==> Caveats
To start batt now and restart at startup:
  sudo brew services start [formula]
```
Therefore I think the audit rules should allow `require_root` to exist with name and without `run`.

`brew audit` currently complains that `run` must be defined to use methods other than `name` like [:require_root]. If I removed the require_root line, I'd have to ask users to ignore the subsequent non-sudo `brew services start` in Caveats. How weird would that sound!

**Comment by SMillerDev** [comment]
This repository has no control over `brew audit`. This should be moved to Homebrew/brew
