### ISSUE TITLE
tailscale service does not start

### ISSUE THREAD

**Issue by marcinjahn** [Homebrew/homebrew-services#645]
After installation of tailscale with `brew install tailscale`, I was shown an instruction:

```
To start tailscale now and restart at login:
  brew services start tailscale
```

I did exactly that and run `brew services start tailscale`. The result:

```
>: brew services start tailscale
==> Successfully started `tailscale` (label: homebrew.tailscale)
```

When I invoke `systemctl` I do not see tailscale running there. Also, when I try to launch `tailscale` with `tailscale up`, I get:

```
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)
```

I also tried:

```
>: sudo systemctl start tailscaled
Failed to start tailscaled.service: Unit tailscaled.service not found.

>: sudo systemctl start homebrew.tailscale
Failed to start homebrew.tailscale.service: Unit homebrew.tailscale.service not found.
```

Am I doing something wrong?

**Comment by SMillerDev** [comment]
Since you ran it without `sudo` you'll need to use `systemctl status --user tailscale`
