### ISSUE TITLE
error：brew services start v2raya

### ISSUE THREAD

**Issue by yxplus1116** [Homebrew/homebrew-services#649]
brew services start v2raya
Error: undefined method plist_startup' for #<Formula v2raya (stable) /usr/local/Homebrew/Library/Taps/v2raya/homebrew-v2raya/Formula/v2raya.rb> Did you mean? plist_name /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service.rb:43:inplist_startup?’
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:229:in launchctl_load' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:359:inblock in start’
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:290:in each' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:290:instart’
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:94:in run!' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:48:inservices’
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in public_send' /usr/local/Homebrew/Library/Homebrew/brew.rb:94:in

‘
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
https://github.com/homebrew/homebrew-services/issues/new

**Comment by SMillerDev** [comment]
This is an issue in https://github.com/v2raya/homebrew-v2raya
