### ISSUE TITLE
Redis reported alive, but fails to run

### ISSUE THREAD

**Issue by JackWink** [Homebrew/homebrew-services#66]
I'm having some trouble getting `brew services start redis` to work.  It seems to have generated a valid LaunchAgents plist, and I'm able to run redis manually by pointing `redis-server` at `/usr/local/etc/redis.conf`. But running `brew services start redis` reports a success without starting redis.

```
jackwink: dev $ brew services start redis
==> Successfully started `redis` (label: homebrew.mxcl.redis)
jackwink: dev $ brew services list
Name       Status  User     Plist
postgresql started jackwink /Users/jackwink/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
redis      started jackwink /Users/jackwink/Library/LaunchAgents/homebrew.mxcl.redis.plist
jackwink: dev $ ps aux | grep redis
jackwink         18306   0.0  0.0  2434840    784 s001  S+    2:22PM   0:00.00 grep redis
jackwink: dev $
```

The generated Plist looks as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>homebrew.mxcl.redis</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/opt/redis/bin/redis-server</string>
      <string>/usr/local/etc/redis.conf</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>/usr/local/var</string>
    <key>StandardErrorPath</key>
    <string>/usr/local/var/log/redis.log</string>
    <key>StandardOutPath</key>
    <string>/usr/local/var/log/redis.log</string>
  </dict>
</plist>
```

**Comment by MikeMcQuaid** [comment]
Try to run `/usr/local/opt/redis/bin/redis-server /usr/local/etc/redis.conf` and see what the output is.

**Comment by cema-sp** [comment]
@JackWink I faced the same issue today, `brew upgrade redis && brew link --overwrite redis` solved the problem.

**Comment by MikeMcQuaid** [comment]
No reply and a suggested workaround so closing.

**Comment by doitian** [comment]
Editing /usr/local/etc/redis.conf and modifying `daemonize` to `no` solved my problem.

**Comment by espen** [comment]
For me running Redis manually with daemonize=yes works fine. But to get it to start with brew services I had to change to daemonize=no as @doitian said.

**Comment by JackWink** [comment]
@MikeMcQuaid the workaround did not work for me, and daemonize was already set to `no` in the redis.conf file. I've also found postgres won't start through `brew services` as well, so I'm guessing my issue is more general than this ticket suggests.

**Comment by MikeMcQuaid** [comment]
@JackWink Unless you provide the output I requested it's not possible for me to debug this issue or help you further.

**Comment by alexdunae** [comment]
@MikeMcQuaid same issue for me, here's the output:

```
$ /usr/local/opt/redis/bin/redis-server /usr/local/etc/redis.conf

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 354
>>> 'vm-enabled no'
Bad directive or wrong number of arguments
```

**Comment by espen** [comment]
I just did a fresh install recently and I don't have that line in my redis.conf

**Comment by UnnikrishnanBhargavakurup** [comment]
Hi,

If i run the redis in command line it's working but not from brew.

`/usr/local/opt/redis/bin/redis-server /usr/local/etc/redis.conf
20046:C 11 Jun 14:48:20.446 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
20046:C 11 Jun 14:48:20.447 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=20046, just started
20046:C 11 Jun 14:48:20.447 # Configuration loaded
20046:M 11 Jun 14:48:20.448 * Increased maximum number of open files to 10032 (it was originally set to 256).
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 4.0.9 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 20046
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

20046:M 11 Jun 14:48:20.449 # Server initialized
20046:M 11 Jun 14:48:20.449 * DB loaded from disk: 0.000 seconds
20046:M 11 Jun 14:48:20.449 * Ready to accept connections`
