### ISSUE TITLE
Formula.factory is deprecated

### ISSUE THREAD

**Issue by govindpatel** [Homebrew/homebrew-services#67]
I am trying to restart nginx using `brew services restart nginx`

running that command gives the following result:
```
Warning: Calling Formula.factory is deprecated!
Use Formulary.factory instead.
/usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:169:in `run!'
Please report this to the homebrew/services tap!

Stopping `nginx`... (might take a while)
==> Successfully stopped `nginx` (label: homebrew.mxcl.nginx)
==> Successfully started `nginx` (label: homebrew.mxcl.nginx)
```
which broke something,
and then when I try to access those url configured in nginx config file. I get 
```
This site can’t be reached

localhost refused to connect.
Search Google for localhost 4200
```

also then when I ran this command `brew services list` to see the services which are running

it display a list of this warning:
```
Warning: Calling Formula#startup_plist is deprecated!
Use Formula#plist instead.
/usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:374:in `plist?'
Please report this to the homebrew/services tap!
```

and shows that nginx is running. 

But if nginx is running why I can't access the url ?

Please look at this issue, I was able to access the url before and it stopped suddenly when I tried to restart nginx

**Comment by MikeMcQuaid** [comment]
> Warning: Calling Formula.factory is deprecated!

This was fixed in https://github.com/Homebrew/homebrew-services/commit/573611593c2d9132c190d77f5f3d14d5f54cc7d5, please `brew update` and try again.

**Comment by govindpatel** [comment]
I tried to update the brew
it says `Already up-to-date`

**Comment by MikeMcQuaid** [comment]
You may have hit https://github.com/Homebrew/brew#update-bug. Can you try the instructions there and see if they help? Thanks!

**Comment by govindpatel** [comment]
hmm... that removed all the warnings,
but still the nginx problem there.

**Comment by MikeMcQuaid** [comment]
The rest is nginx configuration I'm afraid so I'm unable to help as it's unrelated to `brew services`. Sorry!

**Comment by govindpatel** [comment]
🆒  thanks for helping me out fixing those warning
