### ISSUE TITLE
help output implies functionality which is not present

### ISSUE THREAD

**Issue by ticky** [Homebrew/homebrew-services#68]
In particular;
```
   start   Start service(s)
   stop    Stop service(s)
```
seem to imply you can supply them _a list_ of services, which is not the case, the only plural case is `--all`, but that is only really made clear in the [more `man`-style help text in the source code](https://github.com/Homebrew/homebrew-services/blob/573611593c2d9132c190d77f5f3d14d5f54cc7d5/cmd/brew-services.rb#L8).

It seems like either the start and stop commands should accept a list (probably unlikely, given the "custom plist" functionality already present there!) or the help text should not imply plurality, or include the more helpful command signature from the header of the file.

I'd be happy to supply a PR if desired!

**Comment by MikeMcQuaid** [comment]
> I'd be happy to supply a PR if desired!

I agree with your critique and a PR would be 🙇

**Comment by ticky** [comment]
I'm afraid due to the caveat noted I don't suspect multi-service functionality is something I can reasonably implement (I can't think of a reasonable way to do it without breaking existing usages in a backwards-incompatible manner! Maybe once Homebrew gets the versioning a little birdy suggested was approaching) but I'll polish the help output, for sure! 😄

Is there a style guide for such things (read: command help output) within Homebrew I should be following? Otherwise I guess I'll be searching for precedent 😜

**Comment by MikeMcQuaid** [comment]
> but I'll polish the help output, for sure!

Sorry, yeh, this is all I was expecting here.

> Is there a style guide for such things (read: command help output) within Homebrew I should be following?

Not really but https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Prose-Style-Guidelines.md and `brew --help` and `man brew` are probably your best examples. Thanks again!
