### ISSUE TITLE
【brew services start nginx】can not start nginx

### ISSUE THREAD

**Issue by laughwong** [Homebrew/homebrew-services#693]
homebrew.nginx.service

[Unit]
Description=Homebrew generated unit for nginx

[Install]
WantedBy=default.target

[Service]
Type=simple
ExecStart=/home/linuxbrew/.linuxbrew/opt/nginx/bin/nginx -g daemon\ off\;
WorkingDirectory=/home/linuxbrew/.linuxbrew

nginx error.log

2024/07/11 18:39:05 [emerg] 10978#0: unexpected end of parameter, expecting ";" in command line

maybe the ExecStart be like this?

**ExecStart=/home/linuxbrew/.linuxbrew/opt/nginx/bin/nginx -g 'daemon off;'**

**Comment by MikeMcQuaid** [comment]
What `brew services` command are you running that doesn't work?

**Comment by laughwong** [comment]
**brew services start nginx**

but nginx didn't start.

**Comment by MikeMcQuaid** [comment]
Sorry, there's not enough information to help you here.
