### ISSUE TITLE
osquery fails to start

### ISSUE THREAD

**Issue by simonweil** [Homebrew/homebrew-services#7]
Error:
```bash
$ brew services start osquery
/Users/simonweil/Library/LaunchAgents/homebrew.mxcl.osquery.plist: Invalid property list
==> Successfully started `osquery` (label: homebrew.mxcl.osquery)
$ brew services list
Warning: No user-space services controlled by `brew services` running...
$
```

**Comment by alanthing** [comment]
Are you able to `launchctl load /Users/simonweil/Library/LaunchAgents/homebrew.mxcl.osquery.plist` successfully?

**Comment by simonweil** [comment]
No as it's the wrong command.
The `info` stats that the command to run is:
`launchctl load /Users/simonweil/Library/LaunchAgents/homebrew.mxcl.osquery.plist`

Running the command as defined in the info works fine.

**Comment by namelessnotion** [comment]
@simonweil are you using `tmux`? I've found that `brew services list` doesn't work since `launchctl` commands do not play nicely with `tmux`.

**Comment by simonweil** [comment]
Nop, no `tmux`.

**Comment by gapple** [comment]
I'm not quite sure how you're encountering the output you are; osquery doesn't provide a plist for `brew services` to make use of, and for me it provides the corresponding error.

```
geoff:~$ brew install osquery
==> Downloading https://homebrew.bintray.com/bottles/osquery-1.4.7.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring osquery-1.4.7.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/osquery/1.4.7: 23 files, 22M\
geoff:~$ brew services start osquery
Error: Formula `osquery` not installed, #startup_plist not implemented or no plist file found
```

Using the updated `list` command from pull request #12, osquery doesn't appear as a controllable service:
```
geoff:~$ brew services list
Name      Status  User  Plist
dnsmasq   started root  /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
memcached started geoff /Users/geoff/Library/LaunchAgents/homebrew.mxcl.memcached.plist
mysql     started geoff /Users/geoff/Library/LaunchAgents/homebrew.mxcl.mysql.plist
php56     stopped
```

The [osquery documentation](https://osquery.readthedocs.org/en/stable/installation/install-osx/) recommends using `osqueryctl`, which unfortunately seems to not be symlinked in `/usr/local/bin`

--

I experimented with implementing the `plist` method on the osquery formula, but it errors with the default plist, so a modified plist for homebrew is necessary.
Running `osqueryd` manually:
```
geoff:~$ sudo /usr/local/bin/osqueryd
You are using default configurations for osqueryd for one or more of the following
flags: pidfile, db_path.

These options create files in /var/osquery but it looks like that path has not
been created. Please consider explicitly defining those options as a different
path. Additionally, review the "using osqueryd" wiki page:
 - https://osquery.readthedocs.org/en/latest/introduction/using-osqueryd/

E0714 12:55:02.169795 2060223232 init.cpp:228] osqueryd initialize failed: Could not create file: /var/osquery/osqueryd.pidfile
```

The snippet I included in the `osquery.rb` formula:
```
  def plist
    (prefix + "share/osquery/com.facebook.osqueryd.plist").read
      .gsub(%r{(<key>Label</key>\s*<string>)[^<]*(</string>)}, '\1' + plist_name + '\2')
  end
```

**Comment by gapple** [comment]
It is up to the osquery formula to implement the needed plist configuration
