### ISSUE TITLE
Have brew service started with sudo use a different user than root

### ISSUE THREAD

**Issue by BrianHawley** [Homebrew/homebrew-services#70]
If you do `sudo brew services start ...` it creates a plist in the "/Library/LaunchDaemons/" directory, but that plist doesn't have the UserName specified. If you manually add the UserName setting to that plist, restarting the service erases your changes.

I want an option to specify a user to run a global launch daemon with. In particular, I want to run elasticsearch at startup, but it doesn't run properly if you run it as root.

**Comment by MikeMcQuaid** [comment]
@ilovezfs worked on this so is probably the best person to ask here.

**Comment by ilovezfs** [comment]
Yep this is currently the intended behavior. I'd suggest trying `sudo -u bob elasticsearch` in the program arguments array and see if that does the trick without modifying brew services.

**Comment by gapple** [comment]
There are a bunch of other relevant issues to plist user handling, but #44 was one of the final ones.  It was determined that there currently isn't (yet) a strong reason for an option to set the plist user through `brew services`.

If a formula such as elasticsearch always requires being run as a non-root user, the formula's plist should be modified.  Setting it to a specific user for all installations is straightforward, and there is also a pattern for setting the plist user when the formula is installed to the user that installed the formula.
