### ISSUE TITLE
uninitialized constant Homebrew::Service

### ISSUE THREAD

**Issue by jiangyuening** [Homebrew/homebrew-services#704]
/usr/local/Homebrew/Library/Homebrew/formula.rb:1267:in `service'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1238:in `plist_name'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1250:in `launchd_service_path'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:58:in `service_file'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:92:in `plist?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:14:in `block in available_services'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:14:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:14:in `available_services'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:25:in `services_list'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:129:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:97:in `public_send'
/usr/local/Homebrew/Library/Homebrew/brew.rb:97:in `<main>'

**Comment by MikeMcQuaid** [comment]
`brew update`
