### ISSUE TITLE
Restart a service without reinitialising the plist?

### ISSUE THREAD

**Issue by jaspertandy** [Homebrew/homebrew-services#71]
I'm not sure what's happening internally here, but when I restart MySQL, any changes I make to the launchagent are overwritten. What's the best way to make changes to the plist file that persist between restarts?

**Comment by MikeMcQuaid** [comment]
Either use `launchctl` directly or have a custom formula which specifies the plist of your choice.

**Comment by jaspertandy** [comment]
Surely the point of this is to remove the need to access `launchctl` directly? Like I could do all the things that homebrew-services does with launchctl.

**Comment by MikeMcQuaid** [comment]
The point of this is to start Homebrew's formulae plists in launchctl. Note we also don't support starting/stopping non-Homebrew plists.

**Comment by jaspertandy** [comment]
Right, but what I'm asking here isn't related to starting/stopping non-Homebrew plists - it's related to stopping a homebrew plist which homebrew-services _created_ without deleting it first. I don't think that's unreasonable.

**Comment by MikeMcQuaid** [comment]
Sure, to be clear I don't think it's an unreasonable ask but it's just out of scope for us currently given we want `brew services` to respond to formulae plist changes.

**Comment by jaspertandy** [comment]
Right OK cool. I thought I was being crazy for a second there. I've forked and added the functionality to be able to reload without deleting the plist.
