### ISSUE TITLE
brew services restart Hangs on SSH

### ISSUE THREAD

**Issue by fishcharlie** [Homebrew/homebrew-services#743]
I'm having the same issue as #601. Reading through all of that #638 was supposed to improve that, but it isn't working for me. The same issue in #601 still persists.

I'm running `Homebrew 4.3.20-36-gf0be97f`. Am I missing something to get this working?

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)
