### ISSUE TITLE
Brew services tmux

### ISSUE THREAD

**Issue by arthurlm44** [Homebrew/homebrew-services#75]
In a tmux session, when running `brew services list`, I get `Error: brew services cannot run under tmux!` on OSX Sierra.
This is not the case in El Capitan.

Current behavior: brew services does not work while in a tmux session under OSX Sierra.
Desired behavior: brew services should work while in a tmux session.

**Comment by MikeMcQuaid** [comment]
This is not something we can fix, sorry.

**Comment by diclophis** [comment]
@arthurlm44 brew is community maintained, you should see if you can make a patch to fix it

**Comment by armandocerna** [comment]
@MikeMcQuaid Could you possibly shed a little more light into why exactly this is the case.  I am both an avid brew and tmux user and would love if they could work together

**Comment by MikeMcQuaid** [comment]
It's not `brew services` that's the issue, it's `launchd` which is provided by Apple. You'll need to ask the `tmux` developers why those two things don't play nicely.

**Comment by dunn** [comment]
FYI installing `reattach-to-user-namespace` is one workaround: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

**Comment by dunn** [comment]
Related issue: https://github.com/Homebrew/homebrew-services/pull/48
