### ISSUE TITLE
possible to customize plist on start

### ISSUE THREAD

**Issue by itcarroll** [Homebrew/homebrew-services#759]
Is it possible to use any kind of variables or templating in a formula's service block that wouldn't get interpolated until writing the service file during `brew services start ...`?

The jupyterlab formula defines a service that includes `log_path var/"log/jupyterlab.log"`. I'm trying to get the per-user plist files (i.e. what homebrew-services writes into `~/Library/LaunchAgents/`) to have the `StandardOutPath` set to `~/Library/Logs/` rather than into the (write protected) homebrew prefix.

**Comment by MikeMcQuaid** [comment]
Sorry, this is not possible in `brew services`. It may be possible through pull requests to Homebrew/brew. Opening a pull request there may be your best bet.

[This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!
