### ISSUE TITLE
anomaly with httpd24

### ISSUE THREAD

**Issue by kernel-task** [Homebrew/homebrew-services#78]
**Preamble:**

Have taken to starting all brew related processes with '**sudo brew services**' rather than directly with launchctl.

Current output from **brew services list**

> _bind      started root /Library/LaunchDaemons/homebrew.mxcl.bind.plist
> httpd24 started root /Library/LaunchDaemons/homebrew.mxcl.httpd24.plist
> mariadb started root /Library/LaunchDaemons/homebrew.mxcl.mariadb.plist
> nginx     stopped
> php70   stopped
> proftpd stopped_

**Issue:**
Upon login to system apache fails to start - always.
**sudo brew services restart httpd24** fixes this - each time - but is a bit of a pain as _all other processes behave as expected._
No error messages, brew doctor is clear etc. No obvious clues!

Only difference I can see is in the preferences of the relevant **.plst** file itself.
All are **-rw-r--r--** 
httpd24 is **-rw-------**
Is this correct?

Is this startup behaviour of httpd24 actually an issue or am I just missing something.
Many thank in advance for any help given.

Oh yes - have disabled default OSX (Sierra) apache service (lanuchctl -w etc)

Regards.
FC

**Comment by MikeMcQuaid** [comment]
> Have taken to starting all brew related processes with 'sudo brew services' rather than directly with launchctl.

That is a very bad idea; you're going to end up running a lot of services as `root` that need not be and, at least in this case, are accessible to the network.

> Upon login to system apache fails to start - always.

This is likely related to `sudo brew services start` which starts on system start rather than user login. Resources that may be required may not be available.

**Comment by karlshea** [comment]
That's not really an answer to the question. "brew services list" shows httpd24 as "started" and there is no httpd process running. The same thing happens when running "brew service start httpd24" without root.

**Comment by MikeMcQuaid** [comment]
> That's not really an answer to the question. "brew services list" shows httpd24 as "started" and there is no httpd process running.

That's because `brew services` is a thin wrapper around `launchctl` which in this case would also report that a plist has been loaded. It's up to the user to debug why it hasn't started; we can't provide a general solution or detection.

**Comment by edrozenberg** [comment]
Noticed the same issue. I built httpd24 with option "--with-privileged-ports". Running httpd as a regular user does not have permission to use these privileged ports (80/443), so httpd probably gives up and does not start.

**Comment by edrozenberg** [comment]
Figured out what it takes to run httpd24 as a regular user with ports 8080/8443:

Build without option "--with-privileged-ports"

Edit the config file:
```vim /usr/local/etc/apache2/2.4/httpd.conf```

In the config file, change the listen line to:
``` Listen 8080```

In the config file, set a ServerName:
```ServerName myserver.mynetwork:8080```

Restart the service:
```brew services restart httpd24```

**Comment by rezashamdani** [comment]
thanks @edrozenberg , that's works for me too

**Comment by staceymosier** [comment]
edrozenberg's solution to switch from port 80 to 8080 works for me, also,  however I'm not sure why my vhost sites have stopped working on 80 from 2 days ago. 

my system.log console shows:
(homebrew.mxcl.httpd24[373]): Service exited with abnormal code: 1

curl -I -L localhost
curl: (7) Failed to connect to localhost port 80: Connection refused

curl -I -L localhost:8080
HTTP/1.1 200 OK
