### ISSUE TITLE
brew services command issue

### ISSUE THREAD

**Issue by Aerdax** [Homebrew/homebrew-services#785]
brew services list
Warning: Calling `brew services'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.
Please report this issue to the Homebrew/homebrew-services tap, or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:9

Error: uninitialized constant Homebrew::Service
/opt/homebrew/Library/Homebrew/formula.rb:1273:in `service'
/opt/homebrew/Library/Homebrew/formula.rb:1244:in `plist_name'
/opt/homebrew/Library/Homebrew/formula.rb:1256:in `launchd_service_path'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:58:in `service_file'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:92:in `plist?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:14:in `block in available_services'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:14:in `select'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:14:in `available_services'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:25:in `services_list'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:129:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:96:in `public_send'
/opt/homebrew/Library/Homebrew/brew.rb:96:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/homebrew/homebrew-services/issues/new

**Comment by Aerdax** [comment]
macos 15.0.1 (24A348)
----------------------------------------------------------
brew config
HOMEBREW_VERSION: 4.4.2-71-g91f3671
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91f3671b16fe62121364c465c14e0dfd088d7ead
Last commit: 10 hours ago
Core tap JSON: 28 Oct 01:29 UTC
Core cask tap JSON: 28 Oct 01:35 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0.1-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Rosetta 2: false

**Comment by MikeMcQuaid** [comment]
Run `brew update-reset`.

**Comment by Aerdax** [comment]
> brew update-reset
==> Fetching /opt/homebrew...

==> Resetting /opt/homebrew...
Reset branch 'stable'

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-services...

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-services...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
-------------------------------------------------------then another error
brew services list
Error: Cannot find a vendored version of ruby for your arm
processor on Homebrew!
Error: Failed to upgrade vendor Ruby.
/opt/homebrew/Library/Homebrew/version.rb:369:in `initialize': Version value must be a string; got a NilClass () (TypeError)

      raise TypeError, "Version value must be a string; got a #{val.class} (#{val})"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /opt/homebrew/Library/Homebrew/os/mac/version.rb:29:in `initialize'
	from /opt/homebrew/Library/Homebrew/os/mac.rb:18:in `new'
	from /opt/homebrew/Library/Homebrew/os/mac.rb:18:in `version'
	from /opt/homebrew/Library/Homebrew/os/mac.rb:48:in `prerelease?'
	from /opt/homebrew/Library/Homebrew/os.rb:17:in `<module:OS>'
	from /opt/homebrew/Library/Homebrew/os.rb:1:in `<top (required)>'
	from <internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /opt/homebrew/Library/Homebrew/global.rb:118:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/brew.rb:15:in `require_relative'
	from /opt/homebrew/Library/Homebrew/brew.rb:15:in `<main>'

**Comment by Aerdax** [comment]
> Run `brew update-reset`.

thanks for your answer, here another error

**Comment by MikeMcQuaid** [comment]
@Aerdax Your Homebrew is badly broken. I can't help you any more, I'm afraid, this is not a Homebrew bug.

**Comment by Aerdax** [comment]
the broken just happened after run brew update-reset,but when i run brew update, it fixed,and the Warning show again Calling brew services'. This command needs to be refactored, as it is written in a style that is deprecated!...

**Comment by Aerdax** [comment]
fixed! this problem happend because of wrong homebrew/services version.follow steps to fix it
uninstall
```
brew untap homebrew/services
```
install
```
brew tap homebrew/services
```
check the origin should point to the official github repository:https://github.com/Homebrew/homebrew-services
```
brew tap-info homebrew/services
```
