### ISSUE TITLE
"brew service status $service" support

### ISSUE THREAD

**Issue by MikeLund** [Homebrew/homebrew-services#80]
Hi, is it a good idea to have some kind of command like `brew services status $SERVICENAME` ? An enhancement to make brew services a bit more like other init-daemons.

I was a bit tired and tried to see the status of a service, so I type `brew services status $SERVICENAME`. Unknown command.
Expected behavior would be to return something even as simple as `brew services list|grep $SERVICENAME`.

Am I missing something, or could this be a useful enhancement for the future? Thanks!

**Comment by MikeMcQuaid** [comment]
`brew services list` provides this information. We'd accept a PR that filters this for a given service but `brew services list | grep $SERVICENAME` will currently do this.

**Comment by bitdivine** [comment]
If someone were to write a list of the standard verbs for service management systems I am pretty sure that status would be in the list of core verbs, right alongside start and stop.  I appreciate that from your perspective this is already covered but insofar as a language is an interface between a human and a computer and a language is better for communicating well with the human, I think that supporting the standard verbs would be a good thing.  I would like to suggest that this request be reopened.

**Comment by MikeMcQuaid** [comment]
@bitdivine Sorry, we disagree.
