### ISSUE TITLE
brew service start/restart covers ~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist

### ISSUE THREAD

**Issue by SuperMarioBean** [Homebrew/homebrew-services#81]
I found every time I use the brew service start/restart the file(~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist) will be covered by the original file(/usr/local/Cellar/jenkins/homebrew.mxcl.jenkins.plist), so I can not change the ~/Library/LaunchAgents/homebrew.mxcl.jenkins.plist.

**Comment by MikeMcQuaid** [comment]
This is intentional behaviour. If you wish to modify the plist edit the formula or use `launchctl` instead of `brew services`.
