### ISSUE TITLE
Warning: Calling `brew services'. This command needs to be refactored, as it is written in a style that is deprecated!

### ISSUE THREAD

**Issue by developan** [Homebrew/homebrew-services#824]
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:9

Error: uninitialized constant Homebrew::Service
/usr/local/Homebrew/Library/Homebrew/formulary.rb:396:in `block in load_formula_from_api'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `load_formula_from_api'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:971:in `load_from_api'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:964:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:572:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:1018:in `factory'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:113:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:97:in `public_send'
/usr/local/Homebrew/Library/Homebrew/brew.rb:97:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/homebrew/homebrew-services/issues/new

**Comment by ZhongRuoyu** [comment]
What's the output of `brew config` and `brew doctor`? Your Homebrew installation seems to be quite outdated and you should run `brew update`.
