### ISSUE TITLE
plist files written to /Library/LaunchDaemons are empty

### ISSUE THREAD

**Issue by chrisantonellis** [Homebrew/homebrew-services#83]
plist files written to /Library/LaunchDaemons are empty when opened in an editor.
Services start correctly when using ```sudo brew services start <service>``` but plist files are empty, so daemons are not started on reboot.
OSX 10.11.16

**Comment by MikeMcQuaid** [comment]
Can I see your `brew config`? What service are you starting this way?

**Comment by chrisantonellis** [comment]
```
HOMEBREW_VERSION: 1.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: edf042ee97f80955b077724119e717a51eb25e29
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2ab48fcd080ef7160a28e7b8d8693a87df42b7f7
Core tap last commit: 58 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.10.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A
```

trying to start the following: **httpd24, rabbitmq, mongodb**

**Comment by MikeMcQuaid** [comment]
Do they launch without `sudo`? What's the output of `sudo brew services start <service> --debug --verbose`? Thanks!

**Comment by chrisantonellis** [comment]
```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mongodb.rb
==> Generated plist for mongodb:
   <?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
   <plist version="1.0">
   <dict>
     <key>Label</key>
     <string>homebrew.mxcl.mongodb</string>
     <key>ProgramArguments</key>
     <array>
       <string>/usr/local/opt/mongodb/bin/mongod</string>
       <string>--config</string>
       <string>/usr/local/etc/mongod.conf</string>
     </array>
     <key>RunAtLoad</key>
     <true/>
     <key>KeepAlive</key>
     <false/>
     <key>WorkingDirectory</key>
     <string>/usr/local</string>
     <key>StandardErrorPath</key>
     <string>/usr/local/var/log/mongodb/output.log</string>
     <key>StandardOutPath</key>
     <string>/usr/local/var/log/mongodb/output.log</string>
     <key>HardResourceLimits</key>
     <dict>
       <key>NumberOfFiles</key>
       <integer>4096</integer>
     </dict>
     <key>SoftResourceLimits</key>
     <dict>
       <key>NumberOfFiles</key>
       <integer>4096</integer>
     </dict>
   </dict>
   </plist>


/bin/launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.mongodb.plist
==> Successfully started `mongodb` (label: homebrew.mxcl.mongodb)
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `exit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

if I ```cat /Library/LaunchDaemons/homebrew.mxcl.mongodb.plist``` i see the file contents, but opening the file via ```nano``` shows an empty file. This is not the case for other files in ```/Library/LaunchDaemons/``` which do show file contents when opened with ```nano```.

I found this issue by investigating why services started by brew services ran fine after running ```brew service start <service>``` but were not running after reboot, even though ```brew services list``` showed all services as **started**. After a reboot, these services were inaccessible until manually calling ```sudo brew services start <service>``` or ```sudo brew services restart <services>```.  

I was able to repeat this behavior by:  
1. calling ```sudo brew service start httpd24```
2. rebooting
3. pulling up localhost, seeing an address unreachable error
4. manually starting httpd24 via brew services
5. reloading localhost, seeing my local web directory.

please let me know how i can help further debug this issue.

**Comment by MikeMcQuaid** [comment]
> if I cat /Library/LaunchDaemons/homebrew.mxcl.mongodb.plist i see the file contents, but opening the file via nano shows an empty file. This is not the case for other files in /Library/LaunchDaemons/ which do show file contents when opened with nano.

This strongly indicates permission issues. `ls -lha /Library/LaunchDaemons/`.

**Comment by chrisantonellis** [comment]
Yes that was the problem! all homebrew .plist files were created with permission of ```600```. How can I correct or prevent this behavior? If this is my fault, can you speculate on how I screwed up the permissions so I can avoid this in the future?

Thanks very much for your help, it is greatly appreciated!

**Comment by MikeMcQuaid** [comment]
No permissions are set explicitly so setting the `umask` or fixing the permissions manually afterwards is probably the best bet.
