### ISSUE TITLE
No errors for services that aren't installed

### ISSUE THREAD

**Issue by ekmartin** [Homebrew/homebrew-services#84]
If I'm not completely off it seems like all the commands complete successfully even if the target service isn't installed, as long as it is a valid brew service.

Example (I don't have RabbitMQ installed):
![image](https://cloud.githubusercontent.com/assets/3536982/20546581/18bace0e-b0e4-11e6-8633-1745bc8f4769.png)

`brew services start` successfully creates the `plist`, but it doesn't seem like it checks that the target program actually starts.

**Comment by MikeMcQuaid** [comment]
As we just call `launchctl` we can't detect or handle if the application was actually started just that the start attempt was completed.

**Comment by MikeMcQuaid** [comment]
Ah, I see you mean if it's not installed via Homebrew rather than the plist not being installed.
