### ISSUE TITLE
Move to Homebrew organisation

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-services#9]
Would you be happy to move this repository to the official Homebrew organisation and continue maintaining it there? I've spoken to enough people who want this tool back that I'd love to make it an official tool despite not including it in Homebrew/homebrew.

**Comment by alanthing** [comment]
:thumbsup: I'm a big fan of this project and I think moving it under the Homebrew organization would be a great idea.

**Comment by mikemcquaid** [comment]
Would need @gapple to confirm if he's up for this.

**Comment by gapple** [comment]
@mikemcquaid I would be glad to transfer it

**Comment by mikemcquaid** [comment]
@gapple I've added you to the Homebrew organisation so you should be able to migrate this repository there now. When you've done that I'll give you admin access there.

**Comment by gapple** [comment]
Migration is done, and I was able to push a commit to update the tap instructions :+1:

**Comment by mikemcquaid** [comment]
Nice one, thanks!
