### ISSUE TITLE
The service mariadb show status 'error',but it works well

### ISSUE THREAD

**Issue by maxadjsky** [Homebrew/homebrew-services#93]
When I type the command `brew services list`,the result of mariadb is :
`mariadb    error   mofeng /Users/mofeng/Library/LaunchAgents/homebrew.mxcl.mariadb.plist`
But when I type `mysql -uroot`,It can login the mariadb server and  work very well.
So why the service show `error`,and how to see details about the error message.Thanks!

**Comment by maxadjsky** [comment]
the same with the service `dnsmasq`

**Comment by Mluboroscev** [comment]
+ mysql

`mysql      error   Mluboroscev /Users/Mluboroscev/Library/LaunchAgents/homebrew.mxcl.mysql.plist`

**Comment by MikeMcQuaid** [comment]
Closing as duplicate of https://github.com/Homebrew/homebrew-services/issues/92
