### ISSUE TITLE
Error when running brew services

### ISSUE THREAD

**Issue by vedmant** [Homebrew/homebrew-services#98]
I have a huge error report while running brew services starting with "Error: ERROR: Failed to build gem native extension." could you help me? I attached the file
[log.txt](https://github.com/Homebrew/homebrew-services/files/719006/log.txt)

**Comment by MikeMcQuaid** [comment]
This doesn't seem related to `brew services`. You seem to have issues with your system Ruby, sorry.

**Comment by vedmant** [comment]
Thanks, for other cases homebrew works fine, just suddenly stopped to work with services.
